use sea_orm_migration::{prelude::*, schema::*};

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20260808_034545_schema_feeder_master_table_biodata_mahasiswa"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared("CREATE SCHEMA IF NOT EXISTS feeder_master")
            .await?;

        manager
            .create_table(
                Table::create()
                    .table((Alias::new("feeder_master"), Alias::new("biodata_mahasiswa")))
                    .if_not_exists()
                    .col(
                        ColumnDef::new("id").uuid().not_null().default(Expr::cust("public.uuid_generate_v7()")),
                    )
                    .col(
                        ColumnDef::new("nama_mahasiswa").string_len(255),
                    )
                    .col(
                        ColumnDef::new("jenis_kelamin").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tempat_lahir").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tanggal_lahir").date(),
                    )
                    .col(
                        ColumnDef::new("id_mahasiswa").uuid(),
                    )
                    .col(
                        ColumnDef::new("id_agama").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_agama").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nik").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nisn").string_len(255),
                    )
                    .col(
                        ColumnDef::new("npwp").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_negara").string_len(255),
                    )
                    .col(
                        ColumnDef::new("kewarganegaraan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("jalan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("dusun").string_len(255),
                    )
                    .col(
                        ColumnDef::new("rt").integer(),
                    )
                    .col(
                        ColumnDef::new("rw").integer(),
                    )
                    .col(
                        ColumnDef::new("kelurahan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("kode_pos").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_wilayah").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_wilayah").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_jenis_tinggal").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_jenis_tinggal").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_alat_transportasi").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_alat_transportasi").string_len(255),
                    )
                    .col(
                        ColumnDef::new("telepon").string_len(255),
                    )
                    .col(
                        ColumnDef::new("handphone").string_len(255),
                    )
                    .col(
                        ColumnDef::new("email").string_len(255),
                    )
                    .col(
                        ColumnDef::new("penerima_kps").boolean(),
                    )
                    .col(
                        ColumnDef::new("nomor_kps").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nik_ayah").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_ayah").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tanggal_lahir_ayah").date(),
                    )
                    .col(
                        ColumnDef::new("id_pendidikan_ayah").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_pendidikan_ayah").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_pekerjaan_ayah").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_pekerjaan_ayah").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_penghasilan_ayah").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_penghasilan_ayah").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nik_ibu").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_ibu_kandung").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tanggal_lahir_ibu").date(),
                    )
                    .col(
                        ColumnDef::new("id_pendidikan_ibu").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_pendidikan_ibu").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_pekerjaan_ibu").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_pekerjaan_ibu").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_penghasilan_ibu").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_penghasilan_ibu").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_wali").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tanggal_lahir_wali").date(),
                    )
                    .col(
                        ColumnDef::new("id_pendidikan_wali").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_pendidikan_wali").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_pekerjaan_wali").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_pekerjaan_wali").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_penghasilan_wali").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_penghasilan_wali").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_kebutuhan_khusus_mahasiswa").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_kebutuhan_khusus_mahasiswa").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_kebutuhan_khusus_ayah").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_kebutuhan_khusus_ayah").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_kebutuhan_khusus_ibu").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_kebutuhan_khusus_ibu").string_len(255),
                    )
                    .col(
                        ColumnDef::new("status_sync").string_len(255),
                    )
                    .col(
                        ColumnDef::new("created_at").date_time().default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new("updated_at").date_time().default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new("deleted_at").date_time(),
                    )
                    .col(
                        ColumnDef::new("sync_at").date_time(),
                    )
                    .col(
                        ColumnDef::new("created_by").uuid().default(Expr::cust("'00000000-0000-0000-0000-000000000000'::uuid")),
                    )
                    .col(
                        ColumnDef::new("updated_by").uuid().default(Expr::cust("'00000000-0000-0000-0000-000000000000'::uuid")),
                    )
                    .primary_key(
                        Index::create()
                            .name("feeder_master_biodata_mahasiswa_pkey")
                            .col(Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table((Alias::new("feeder_master"), Alias::new("biodata_mahasiswa")))
                    .if_exists()
                    .to_owned(),
            )
            .await
    }
}
