use sea_orm_migration::prelude::*;

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20260808_034545_schema_feeder_master_table_biodata_dosen"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared("CREATE SCHEMA IF NOT EXISTS feeder_master")
            .await?;

        manager
            .create_table(
                Table::create()
                    .table((Alias::new("feeder_master"), Alias::new("biodata_dosen")))
                    .if_not_exists()
                    .col(
                        ColumnDef::new("id").uuid().not_null().default(Expr::cust("public.uuid_generate_v7()")),
                    )
                    .col(
                        ColumnDef::new("id_dosen").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_dosen").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tempat_lahir").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tanggal_lahir").date(),
                    )
                    .col(
                        ColumnDef::new("jenis_kelamin").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_agama").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_agama").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_status_aktif").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_status_aktif").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nidn").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_ibu_kandung").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nik").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nip").string_len(255),
                    )
                    .col(
                        ColumnDef::new("npwp").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_jenis_sdm").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_jenis_sdm").string_len(255),
                    )
                    .col(
                        ColumnDef::new("no_sk_cpns").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tanggal_sk_cpns").date(),
                    )
                    .col(
                        ColumnDef::new("no_sk_pengangkatan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("mulai_sk_pengangkatan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_lembaga_pengangkatan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_lembaga_pengangkatan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_pangkat_golongan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_pangkat_golongan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_sumber_gaji").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_sumber_gaji").string_len(255),
                    )
                    .col(
                        ColumnDef::new("jalan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("dusun").string_len(255),
                    )
                    .col(
                        ColumnDef::new("rt").string_len(255),
                    )
                    .col(
                        ColumnDef::new("rw").string_len(255),
                    )
                    .col(
                        ColumnDef::new("ds_kel").string_len(255),
                    )
                    .col(
                        ColumnDef::new("kode_pos").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_wilayah").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_wilayah").string_len(255),
                    )
                    .col(
                        ColumnDef::new("telepon").string_len(255),
                    )
                    .col(
                        ColumnDef::new("handphone").string_len(255),
                    )
                    .col(
                        ColumnDef::new("email").string_len(255),
                    )
                    .col(
                        ColumnDef::new("status_pernikahan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_suami_istri").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nip_suami_istri").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tanggal_mulai_pns").date(),
                    )
                    .col(
                        ColumnDef::new("nama_pekerjaan_suami_istri").string_len(255),
                    )
                    .col(
                        ColumnDef::new("created_at").date_time().default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new("updated_at").date_time().default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new("deleted_at").date_time(),
                    )
                    .col(
                        ColumnDef::new("sync_at").date_time(),
                    )
                    .col(
                        ColumnDef::new("created_by").uuid().default(Expr::cust("'00000000-0000-0000-0000-000000000000'::uuid")),
                    )
                    .col(
                        ColumnDef::new("updated_by").uuid().default(Expr::cust("'00000000-0000-0000-0000-000000000000'::uuid")),
                    )
                    .col(
                        ColumnDef::new("id_pekerjaan_suami_istri").integer().default(0),
                    )
                    .primary_key(
                        Index::create()
                            .name("feeder_master_biodata_dosen_pkey")
                            .col(Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table((Alias::new("feeder_master"), Alias::new("biodata_dosen")))
                    .if_exists()
                    .to_owned(),
            )
            .await
    }
}
