use sea_orm_migration::prelude::*;

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20260808_034545_schema_feeder_master_table_mahasiswa_lulusan_dropout"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared("CREATE SCHEMA IF NOT EXISTS feeder_master")
            .await?;

        manager
            .create_table(
                Table::create()
                    .table((Alias::new("feeder_master"), Alias::new("mahasiswa_lulusan_dropout")))
                    .if_not_exists()
                    .col(
                        ColumnDef::new("id").uuid().not_null().default(Expr::cust("public.uuid_generate_v7()")),
                    )
                    .col(
                        ColumnDef::new("created_at").date_time().default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new("updated_at").date_time().default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new("deleted_at").date_time(),
                    )
                    .col(
                        ColumnDef::new("sync_at").date_time(),
                    )
                    .col(
                        ColumnDef::new("created_by").uuid().default(Expr::cust("'00000000-0000-0000-0000-000000000000'::uuid")),
                    )
                    .col(
                        ColumnDef::new("updated_by").uuid().default(Expr::cust("'00000000-0000-0000-0000-000000000000'::uuid")),
                    )
                    .col(
                        ColumnDef::new("id_registrasi_mahasiswa").uuid(),
                    )
                    .col(
                        ColumnDef::new("id_mahasiswa").uuid(),
                    )
                    .col(
                        ColumnDef::new("id_perguruan_tinggi").uuid(),
                    )
                    .col(
                        ColumnDef::new("id_prodi").uuid(),
                    )
                    .col(
                        ColumnDef::new("nama_program_studi").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nim").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_mahasiswa").string_len(255),
                    )
                    .col(
                        ColumnDef::new("angkatan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tgl_masuk_sp").date(),
                    )
                    .col(
                        ColumnDef::new("tgl_create").date(),
                    )
                    .col(
                        ColumnDef::new("tgl_keluar").date(),
                    )
                    .col(
                        ColumnDef::new("tanggal_keluar").date(),
                    )
                    .col(
                        ColumnDef::new("id_jenis_keluar").string_len(255).not_null(),
                    )
                    .col(
                        ColumnDef::new("nama_jenis_keluar").string_len(255).not_null(),
                    )
                    .col(
                        ColumnDef::new("id_periode_keluar").string_len(255).not_null(),
                    )
                    .col(
                        ColumnDef::new("keterangan").text(),
                    )
                    .col(
                        ColumnDef::new("nomor_sk_yudisium").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tanggal_sk_yudisium").date(),
                    )
                    .col(
                        ColumnDef::new("ipk").float().default(0),
                    )
                    .col(
                        ColumnDef::new("nomor_ijazah").string_len(255),
                    )
                    .col(
                        ColumnDef::new("asal_ijazah").string_len(10).not_null(),
                    )
                    .col(
                        ColumnDef::new("no_sertifikat_profesi").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tanggal_terbit_ijazah").date(),
                    )
                    .col(
                        ColumnDef::new("jalur_skripsi").string_len(255),
                    )
                    .col(
                        ColumnDef::new("judul_skripsi").text(),
                    )
                    .col(
                        ColumnDef::new("bulan_awal_bimbingan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("bulan_akhir_bimbingan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_dosen").uuid(),
                    )
                    .col(
                        ColumnDef::new("nidn").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nuptk").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_dosen").string_len(255),
                    )
                    .col(
                        ColumnDef::new("pembimbing_ke").integer(),
                    )
                    .col(
                        ColumnDef::new("skhun").string_len(255),
                    )
                    .col(
                        ColumnDef::new("no_peserta_ujian").string_len(255),
                    )
                    .col(
                        ColumnDef::new("sks_diakui").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_jns_daftar").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nm_jns_daftar").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_jalur_masuk").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_pembiayaan").string_len(255),
                    )
                    .col(
                        ColumnDef::new("biaya_masuk_kuliah").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_minat_bidang").string_len(255),
                    )
                    .col(
                        ColumnDef::new("bidang_mayor").string_len(255),
                    )
                    .col(
                        ColumnDef::new("bidang_minor").string_len(255),
                    )
                    .col(
                        ColumnDef::new("a_pindah_mhs_asing").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_pt_asal").uuid(),
                    )
                    .col(
                        ColumnDef::new("id_prodi_asal").uuid(),
                    )
                    .col(
                        ColumnDef::new("nm_pt_asal").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nm_prodi_asal").string_len(255),
                    )
                    .col(
                        ColumnDef::new("namapt").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_jur").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nm_smt").string_len(255),
                    )
                    .col(
                        ColumnDef::new("status_sync").string_len(255),
                    )
                    .primary_key(
                        Index::create()
                            .name("feeder_master_mahasiswa_lulusan_dropout_pkey")
                            .col(Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table((Alias::new("feeder_master"), Alias::new("mahasiswa_lulusan_dropout")))
                    .if_exists()
                    .to_owned(),
            )
            .await
    }
}
