use sea_orm_migration::prelude::*;

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20260808_034546_schema_feeder_master_table_riwayat_pendidikan_mahasiswa"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared("CREATE SCHEMA IF NOT EXISTS feeder_master")
            .await?;

        manager
            .create_table(
                Table::create()
                    .table((Alias::new("feeder_master"), Alias::new("riwayat_pendidikan_mahasiswa")))
                    .if_not_exists()
                    .col(
                        ColumnDef::new("id").uuid().not_null().default(Expr::cust("public.uuid_generate_v7()")),
                    )
                    .col(
                        ColumnDef::new("id_registrasi_mahasiswa").uuid(),
                    )
                    .col(
                        ColumnDef::new("id_mahasiswa").uuid(),
                    )
                    .col(
                        ColumnDef::new("nim").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_mahasiswa").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_jenis_daftar").integer(),
                    )
                    .col(
                        ColumnDef::new("nama_jenis_daftar").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_jalur_daftar").integer(),
                    )
                    .col(
                        ColumnDef::new("id_periode_masuk").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_periode_masuk").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_jenis_keluar").integer(),
                    )
                    .col(
                        ColumnDef::new("keterangan_keluar").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_perguruan_tinggi").uuid(),
                    )
                    .col(
                        ColumnDef::new("nama_perguruan_tinggi").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_prodi").uuid(),
                    )
                    .col(
                        ColumnDef::new("nama_program_studi").string_len(255),
                    )
                    .col(
                        ColumnDef::new("sks_diakui").float(),
                    )
                    .col(
                        ColumnDef::new("id_perguruan_tinggi_asal").uuid(),
                    )
                    .col(
                        ColumnDef::new("nama_perguruan_tinggi_asal").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_prodi_asal").uuid(),
                    )
                    .col(
                        ColumnDef::new("nama_program_studi_asal").string_len(255),
                    )
                    .col(
                        ColumnDef::new("jenis_kelamin").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tanggal_daftar").date(),
                    )
                    .col(
                        ColumnDef::new("nama_ibu_kandung").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_pembiayaan").integer(),
                    )
                    .col(
                        ColumnDef::new("biaya_masuk").integer(),
                    )
                    .col(
                        ColumnDef::new("id_bidang_minat").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nm_bidang_minat").string_len(255),
                    )
                    .col(
                        ColumnDef::new("id_periode_keluar").string_len(255),
                    )
                    .col(
                        ColumnDef::new("tanggal_keluar").date(),
                    )
                    .col(
                        ColumnDef::new("last_update").date(),
                    )
                    .col(
                        ColumnDef::new("tgl_create").date(),
                    )
                    .col(
                        ColumnDef::new("status_sync").string_len(255),
                    )
                    .col(
                        ColumnDef::new("nama_pembiayaan_awal").string_len(255),
                    )
                    .col(
                        ColumnDef::new("created_at").date_time().default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new("updated_at").date_time().default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new("deleted_at").date_time(),
                    )
                    .col(
                        ColumnDef::new("sync_at").date_time(),
                    )
                    .col(
                        ColumnDef::new("created_by").uuid().default(Expr::cust("'00000000-0000-0000-0000-000000000000'::uuid")),
                    )
                    .col(
                        ColumnDef::new("updated_by").uuid().default(Expr::cust("'00000000-0000-0000-0000-000000000000'::uuid")),
                    )
                    .primary_key(
                        Index::create()
                            .name("feeder_master_riwayat_pendidikan_mahasiswa_pkey")
                            .col(Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table((Alias::new("feeder_master"), Alias::new("riwayat_pendidikan_mahasiswa")))
                    .if_exists()
                    .to_owned(),
            )
            .await
    }
}
