import fs from "node:fs";
import path from "node:path";
import { defineConfig, type Plugin } from "vite";
import { solidStart } from "@solidjs/start/config";
import tailwindcss from "@tailwindcss/vite";

function syncInstitutionAssets() {
  const publicLogoDir = path.resolve(import.meta.dirname, "public/img/logo");
  const targetFile = path.resolve(import.meta.dirname, "src/config/institutionAssets.ts");

  const logoCodes: string[] = [];
  const faviconCodes: string[] = [];

  if (fs.existsSync(publicLogoDir)) {
    const entries = fs.readdirSync(publicLogoDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        const code = entry.name;
        const logoPath = path.join(publicLogoDir, code, "android-chrome-512x512.png");
        const faviconPath = path.join(publicLogoDir, code, "favicon.ico");
        if (fs.existsSync(logoPath)) {
          logoCodes.push(code);
        }
        if (fs.existsSync(faviconPath)) {
          faviconCodes.push(code);
        }
      }
    }
  }

  logoCodes.sort();
  faviconCodes.sort();

  const content = `// This file is auto-generated by vite.config.ts. Do not edit directly.
export const availableLogoCodes = ${JSON.stringify(logoCodes, null, 2)} as const;

export const availableFaviconCodes = ${JSON.stringify(faviconCodes, null, 2)} as const;
`;

  if (!fs.existsSync(targetFile) || fs.readFileSync(targetFile, "utf-8") !== content) {
    fs.mkdirSync(path.dirname(targetFile), { recursive: true });
    fs.writeFileSync(targetFile, content, "utf-8");
  }
}

// Ensure assets are synced when config loads
syncInstitutionAssets();

function institutionAssetsPlugin(): Plugin {
  return {
    name: "institution-assets-watcher",
    buildStart() {
      syncInstitutionAssets();
    },
    configureServer(server) {
      const publicLogoDir = path.resolve(import.meta.dirname, "public/img/logo");
      server.watcher.add(publicLogoDir);
      server.watcher.on("all", (event, filePath) => {
        if (filePath.includes("public/img/logo")) {
          syncInstitutionAssets();
        }
      });
    },
  };
}

export default defineConfig({
  envPrefix: ['VITE_', 'CURRENT_'],
  plugins: [
    institutionAssetsPlugin(),
    solidStart({ devOverlay: false }),
    tailwindcss(),
  ],
  server: {
    proxy: {
      '/api': {
        target: 'http://127.0.0.1:5800',
        changeOrigin: true,
      },
    },
  },
});

