//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::categories::Entity as Categories;
pub use super::conditions::Entity as Conditions;
pub use super::room_types::Entity as RoomTypes;
pub use super::varieties::Entity as Varieties;
