//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::categories::Entity as BuildingReferenceCategories;
pub use super::conditions::Entity as BuildingReferenceConditions;
pub use super::room_types::Entity as BuildingReferenceRoomTypes;
pub use super::varieties::Entity as BuildingReferenceVarieties;
