//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod adviser_categories;
pub mod approval_types;
pub mod categories;
pub mod requirements;
pub mod stages;
pub mod varieties;
