//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::adviser_categories::Entity as AdviserCategories;
pub use super::approval_types::Entity as ApprovalTypes;
pub use super::categories::Entity as Categories;
pub use super::requirements::Entity as Requirements;
pub use super::stages::Entity as Stages;
pub use super::varieties::Entity as Varieties;
