//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::adviser_categories::Entity as AcademicStudentFinalAssignmentReferenceAdviserCategories;
pub use super::approval_types::Entity as AcademicStudentFinalAssignmentReferenceApprovalTypes;
pub use super::categories::Entity as AcademicStudentFinalAssignmentReferenceCategories;
pub use super::requirements::Entity as AcademicStudentFinalAssignmentReferenceRequirements;
pub use super::stages::Entity as AcademicStudentFinalAssignmentReferenceStages;
pub use super::varieties::Entity as AcademicStudentFinalAssignmentReferenceVarieties;
