//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_lecturer_transaction",
    table_name = "academic_groups"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub decree_number: Option<String>,
    pub decree_date: Option<Date>,
    pub lecturer_id: Uuid,
    pub group_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    #[sea_orm(belongs_to, from = "lecturer_id", to = "id")]
    pub lecturer: BelongsTo<crate::models::academic::lecturer::master::lecturers::Entity>,
    #[sea_orm(belongs_to, from = "group_id", to = "id")]
    pub group: BelongsTo<crate::models::academic::lecturer::reference::groups::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
