//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_lecturer_transaction",
    table_name = "homebases"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub lecturer_id: Uuid,
    pub unit_id: Uuid,
    pub institution_id: Uuid,
    pub status_id: Uuid,
    pub contract_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "lecturer_id", to = "id")]
    pub lecturer: BelongsTo<crate::models::academic::lecturer::master::lecturers::Entity>,
    #[sea_orm(belongs_to, from = "unit_id", to = "id")]
    pub unit: BelongsTo<crate::models::institution::master::units::Entity>,
    #[sea_orm(belongs_to, from = "institution_id", to = "id")]
    pub institution: BelongsTo<crate::models::institution::master::institutions::Entity>,
    #[sea_orm(belongs_to, from = "status_id", to = "id")]
    pub status: BelongsTo<crate::models::academic::lecturer::reference::statuses::Entity>,
    #[sea_orm(belongs_to, from = "contract_id", to = "id")]
    pub contract: BelongsTo<crate::models::academic::lecturer::reference::contracts::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
