//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::academic_groups::Entity as AcademicLecturerTransactionAcademicGroups;
pub use super::academic_ranks::Entity as AcademicLecturerTransactionAcademicRanks;
pub use super::homebases::Entity as AcademicLecturerTransactionHomebases;
