//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::academic_groups::Entity as AcademicGroups;
pub use super::academic_ranks::Entity as AcademicRanks;
pub use super::homebases::Entity as Homebases;
