//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "institution_reference", table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: i32,
    pub alphabet_code: String,
    pub name: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub sync_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub institutions: HasMany<crate::models::institution::master::institutions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
