//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod categories;
pub mod position_type;
pub mod unit_types;
pub mod varieties;

pub use crate::models::auth::user_position_type;
