//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::categories::Entity as Categories;
pub use super::position_types::Entity as PositionTypes;
pub use super::unit_types::Entity as UnitTypes;
pub use super::varieties::Entity as Varieties;
