//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::categories::Entity as InstitutionReferenceCategories;
pub use super::position_type::Entity as InstitutionReferencePositionTypes;
pub use super::unit_types::Entity as InstitutionReferenceUnitTypes;
pub use super::varieties::Entity as InstitutionReferenceVarieties;
