//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_survey_transaction", table_name = "conducts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub alphabet_code: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub bundle_id: Uuid,
    pub conductable_type: String,
    pub conductable_id: Uuid,
    pub is_finish: bool,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "bundle_id", to = "id")]
    pub bundle: BelongsTo<crate::models::academic::survey::master::bundles::Entity>,
    #[sea_orm(has_many)]
    pub responds: HasMany<crate::models::academic::survey::transaction::responds::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
