//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_survey_transaction", table_name = "responds")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    pub conduct_id: Uuid,
    pub bundle_id: Uuid,
    pub question_id: Uuid,
    pub answer_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "conduct_id", to = "id")]
    pub conduct: BelongsTo<crate::models::academic::survey::transaction::conducts::Entity>,
    #[sea_orm(belongs_to, from = "bundle_id", to = "id")]
    pub bundle: BelongsTo<crate::models::academic::survey::master::bundles::Entity>,
    #[sea_orm(belongs_to, from = "question_id", to = "id")]
    pub question: BelongsTo<crate::models::academic::survey::master::questions::Entity>,
    #[sea_orm(belongs_to, from = "answer_id", to = "id")]
    pub answer: BelongsTo<Option<crate::models::academic::survey::master::answers::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
