//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_student_master", table_name = "students")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: String,
    pub name: String,
    pub selection_type_id: Uuid,
    pub registered: Date,
    pub individual_id: Uuid,
    pub status_id: Uuid,
    pub unit_id: Uuid,
    pub academic_year_id: Uuid,
    pub registration_id: Uuid,
    pub nisn: Option<String>,
    pub resign_status_id: Uuid,
    pub concentration_id: Uuid,
    pub curriculum_id: Uuid,
    pub class_code_id: Uuid,
    pub transfer_code: Option<String>,
    pub transfer_unit_id: Uuid,
    pub id_mahasiswa: Option<Uuid>,
    pub id_registrasi_mahasiswa: Option<Uuid>,
    #[sea_orm(column_type = "Double", nullable)]
    pub finance_fee: Option<f64>,
    pub finance_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
