use salvo::prelude::*;

pub mod agama;
pub mod alat_transportasi;
pub mod bentuk_pendidikan;
pub mod ikatan_kerja_sumber_daya_manusia;
pub mod jabatan_fungsional;
pub mod jalur_masuk;
pub mod jenis_aktifitas_mahasiswa;
pub mod jenis_evaluasi;
pub mod jenis_keluar;
pub mod jenis_pendaftaran;
pub mod jenis_prestasi;
pub mod jenis_satuan_manajemen_sumberdaya;
pub mod jenis_sertifikasi;
pub mod jenis_substansi;
pub mod jenis_tinggal;
pub mod jenjang_pendidikan;
pub mod kategori_kegiatan;
pub mod kebutuhan_khusus;
pub mod lembaga_pengangkat;
pub mod level_wilayah;
pub mod negara;
pub mod pangkat_golongan;
pub mod pekerjaan;
pub mod pembiayaan;
pub mod penghasilan;
pub mod periode_lampau;
pub mod semester;
pub mod status_keaktifan_pegawai;
pub mod status_kepegawaian;
pub mod status_mahasiswa;
pub mod tahun_ajaran;
pub mod tingkat_prestasi;
pub mod wilayah;

pub fn router() -> Router {
    Router::with_path("referensi")
        .push(
            Router::with_path("agama")
                .get(agama::list_agama)
                .post(agama::create_agama)
                .push(
                    Router::with_path("{id}")
                        .get(agama::get_agama)
                        .put(agama::update_agama)
                        .delete(agama::delete_agama),
                ),
        )
        .push(
            Router::with_path("alat-transportasi")
                .get(alat_transportasi::list_alat_transportasi)
                .post(alat_transportasi::create_alat_transportasi)
                .push(
                    Router::with_path("{id}")
                        .get(alat_transportasi::get_alat_transportasi)
                        .put(alat_transportasi::update_alat_transportasi)
                        .delete(alat_transportasi::delete_alat_transportasi),
                ),
        )
        .push(
            Router::with_path("bentuk-pendidikan")
                .get(bentuk_pendidikan::list_bentuk_pendidikan)
                .post(bentuk_pendidikan::create_bentuk_pendidikan)
                .push(
                    Router::with_path("{id}")
                        .get(bentuk_pendidikan::get_bentuk_pendidikan)
                        .put(bentuk_pendidikan::update_bentuk_pendidikan)
                        .delete(bentuk_pendidikan::delete_bentuk_pendidikan),
                ),
        )
        .push(
            Router::with_path("ikatan-kerja-sumber-daya-manusia")
                .get(ikatan_kerja_sumber_daya_manusia::list_ikatan_kerja_sumber_daya_manusia)
                .post(ikatan_kerja_sumber_daya_manusia::create_ikatan_kerja_sumber_daya_manusia)
                .push(
                    Router::with_path("{id}")
                        .get(ikatan_kerja_sumber_daya_manusia::get_ikatan_kerja_sumber_daya_manusia)
                        .put(ikatan_kerja_sumber_daya_manusia::update_ikatan_kerja_sumber_daya_manusia)
                        .delete(ikatan_kerja_sumber_daya_manusia::delete_ikatan_kerja_sumber_daya_manusia),
                ),
        )
        .push(
            Router::with_path("jabatan-fungsional")
                .get(jabatan_fungsional::list_jabatan_fungsional)
                .post(jabatan_fungsional::create_jabatan_fungsional)
                .push(
                    Router::with_path("{id}")
                        .get(jabatan_fungsional::get_jabatan_fungsional)
                        .put(jabatan_fungsional::update_jabatan_fungsional)
                        .delete(jabatan_fungsional::delete_jabatan_fungsional),
                ),
        )
        .push(
            Router::with_path("jalur-masuk")
                .get(jalur_masuk::list_jalur_masuk)
                .post(jalur_masuk::create_jalur_masuk)
                .push(
                    Router::with_path("{id}")
                        .get(jalur_masuk::get_jalur_masuk)
                        .put(jalur_masuk::update_jalur_masuk)
                        .delete(jalur_masuk::delete_jalur_masuk),
                ),
        )
        .push(
            Router::with_path("jenis-aktifitas-mahasiswa")
                .get(jenis_aktifitas_mahasiswa::list_jenis_aktifitas_mahasiswa)
                .post(jenis_aktifitas_mahasiswa::create_jenis_aktifitas_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(jenis_aktifitas_mahasiswa::get_jenis_aktifitas_mahasiswa)
                        .put(jenis_aktifitas_mahasiswa::update_jenis_aktifitas_mahasiswa)
                        .delete(jenis_aktifitas_mahasiswa::delete_jenis_aktifitas_mahasiswa),
                ),
        )
        .push(
            Router::with_path("jenis-evaluasi")
                .get(jenis_evaluasi::list_jenis_evaluasi)
                .post(jenis_evaluasi::create_jenis_evaluasi)
                .push(
                    Router::with_path("{id}")
                        .get(jenis_evaluasi::get_jenis_evaluasi)
                        .put(jenis_evaluasi::update_jenis_evaluasi)
                        .delete(jenis_evaluasi::delete_jenis_evaluasi),
                ),
        )
        .push(
            Router::with_path("jenis-keluar")
                .get(jenis_keluar::list_jenis_keluar)
                .post(jenis_keluar::create_jenis_keluar)
                .push(
                    Router::with_path("{id}")
                        .get(jenis_keluar::get_jenis_keluar)
                        .put(jenis_keluar::update_jenis_keluar)
                        .delete(jenis_keluar::delete_jenis_keluar),
                ),
        )
        .push(
            Router::with_path("jenis-pendaftaran")
                .get(jenis_pendaftaran::list_jenis_pendaftaran)
                .post(jenis_pendaftaran::create_jenis_pendaftaran)
                .push(
                    Router::with_path("{id}")
                        .get(jenis_pendaftaran::get_jenis_pendaftaran)
                        .put(jenis_pendaftaran::update_jenis_pendaftaran)
                        .delete(jenis_pendaftaran::delete_jenis_pendaftaran),
                ),
        )
        .push(
            Router::with_path("jenis-prestasi")
                .get(jenis_prestasi::list_jenis_prestasi)
                .post(jenis_prestasi::create_jenis_prestasi)
                .push(
                    Router::with_path("{id}")
                        .get(jenis_prestasi::get_jenis_prestasi)
                        .put(jenis_prestasi::update_jenis_prestasi)
                        .delete(jenis_prestasi::delete_jenis_prestasi),
                ),
        )
        .push(
            Router::with_path("jenis-satuan-manajemen-sumberdaya")
                .get(jenis_satuan_manajemen_sumberdaya::list_jenis_satuan_manajemen_sumberdaya)
                .post(jenis_satuan_manajemen_sumberdaya::create_jenis_satuan_manajemen_sumberdaya)
                .push(
                    Router::with_path("{id}")
                        .get(jenis_satuan_manajemen_sumberdaya::get_jenis_satuan_manajemen_sumberdaya)
                        .put(jenis_satuan_manajemen_sumberdaya::update_jenis_satuan_manajemen_sumberdaya)
                        .delete(jenis_satuan_manajemen_sumberdaya::delete_jenis_satuan_manajemen_sumberdaya),
                ),
        )
        .push(
            Router::with_path("jenis-sertifikasi")
                .get(jenis_sertifikasi::list_jenis_sertifikasi)
                .post(jenis_sertifikasi::create_jenis_sertifikasi)
                .push(
                    Router::with_path("{id}")
                        .get(jenis_sertifikasi::get_jenis_sertifikasi)
                        .put(jenis_sertifikasi::update_jenis_sertifikasi)
                        .delete(jenis_sertifikasi::delete_jenis_sertifikasi),
                ),
        )
        .push(
            Router::with_path("jenis-substansi")
                .get(jenis_substansi::list_jenis_substansi)
                .post(jenis_substansi::create_jenis_substansi)
                .push(
                    Router::with_path("{id}")
                        .get(jenis_substansi::get_jenis_substansi)
                        .put(jenis_substansi::update_jenis_substansi)
                        .delete(jenis_substansi::delete_jenis_substansi),
                ),
        )
        .push(
            Router::with_path("jenis-tinggal")
                .get(jenis_tinggal::list_jenis_tinggal)
                .post(jenis_tinggal::create_jenis_tinggal)
                .push(
                    Router::with_path("{id}")
                        .get(jenis_tinggal::get_jenis_tinggal)
                        .put(jenis_tinggal::update_jenis_tinggal)
                        .delete(jenis_tinggal::delete_jenis_tinggal),
                ),
        )
        .push(
            Router::with_path("jenjang-pendidikan")
                .get(jenjang_pendidikan::list_jenjang_pendidikan)
                .post(jenjang_pendidikan::create_jenjang_pendidikan)
                .push(
                    Router::with_path("{id}")
                        .get(jenjang_pendidikan::get_jenjang_pendidikan)
                        .put(jenjang_pendidikan::update_jenjang_pendidikan)
                        .delete(jenjang_pendidikan::delete_jenjang_pendidikan),
                ),
        )
        .push(
            Router::with_path("kategori-kegiatan")
                .get(kategori_kegiatan::list_kategori_kegiatan)
                .post(kategori_kegiatan::create_kategori_kegiatan)
                .push(
                    Router::with_path("{id}")
                        .get(kategori_kegiatan::get_kategori_kegiatan)
                        .put(kategori_kegiatan::update_kategori_kegiatan)
                        .delete(kategori_kegiatan::delete_kategori_kegiatan),
                ),
        )
        .push(
            Router::with_path("kebutuhan-khusus")
                .get(kebutuhan_khusus::list_kebutuhan_khusus)
                .post(kebutuhan_khusus::create_kebutuhan_khusu)
                .push(
                    Router::with_path("{id}")
                        .get(kebutuhan_khusus::get_kebutuhan_khusu)
                        .put(kebutuhan_khusus::update_kebutuhan_khusu)
                        .delete(kebutuhan_khusus::delete_kebutuhan_khusu),
                ),
        )
        .push(
            Router::with_path("lembaga-pengangkat")
                .get(lembaga_pengangkat::list_lembaga_pengangkat)
                .post(lembaga_pengangkat::create_lembaga_pengangkat)
                .push(
                    Router::with_path("{id}")
                        .get(lembaga_pengangkat::get_lembaga_pengangkat)
                        .put(lembaga_pengangkat::update_lembaga_pengangkat)
                        .delete(lembaga_pengangkat::delete_lembaga_pengangkat),
                ),
        )
        .push(
            Router::with_path("level-wilayah")
                .get(level_wilayah::list_level_wilayah)
                .post(level_wilayah::create_level_wilayah)
                .push(
                    Router::with_path("{id}")
                        .get(level_wilayah::get_level_wilayah)
                        .put(level_wilayah::update_level_wilayah)
                        .delete(level_wilayah::delete_level_wilayah),
                ),
        )
        .push(
            Router::with_path("negara")
                .get(negara::list_negara)
                .post(negara::create_negara)
                .push(
                    Router::with_path("{id}")
                        .get(negara::get_negara)
                        .put(negara::update_negara)
                        .delete(negara::delete_negara),
                ),
        )
        .push(
            Router::with_path("pangkat-golongan")
                .get(pangkat_golongan::list_pangkat_golongan)
                .post(pangkat_golongan::create_pangkat_golongan)
                .push(
                    Router::with_path("{id}")
                        .get(pangkat_golongan::get_pangkat_golongan)
                        .put(pangkat_golongan::update_pangkat_golongan)
                        .delete(pangkat_golongan::delete_pangkat_golongan),
                ),
        )
        .push(
            Router::with_path("pekerjaan")
                .get(pekerjaan::list_pekerjaan)
                .post(pekerjaan::create_pekerjaan)
                .push(
                    Router::with_path("{id}")
                        .get(pekerjaan::get_pekerjaan)
                        .put(pekerjaan::update_pekerjaan)
                        .delete(pekerjaan::delete_pekerjaan),
                ),
        )
        .push(
            Router::with_path("pembiayaan")
                .get(pembiayaan::list_pembiayaan)
                .post(pembiayaan::create_pembiayaan)
                .push(
                    Router::with_path("{id}")
                        .get(pembiayaan::get_pembiayaan)
                        .put(pembiayaan::update_pembiayaan)
                        .delete(pembiayaan::delete_pembiayaan),
                ),
        )
        .push(
            Router::with_path("penghasilan")
                .get(penghasilan::list_penghasilan)
                .post(penghasilan::create_penghasilan)
                .push(
                    Router::with_path("{id}")
                        .get(penghasilan::get_penghasilan)
                        .put(penghasilan::update_penghasilan)
                        .delete(penghasilan::delete_penghasilan),
                ),
        )
        .push(
            Router::with_path("periode-lampau")
                .get(periode_lampau::list_periode_lampau)
                .post(periode_lampau::create_periode_lampau)
                .push(
                    Router::with_path("{id}")
                        .get(periode_lampau::get_periode_lampau)
                        .put(periode_lampau::update_periode_lampau)
                        .delete(periode_lampau::delete_periode_lampau),
                ),
        )
        .push(
            Router::with_path("semester")
                .get(semester::list_semester)
                .post(semester::create_semester)
                .push(
                    Router::with_path("{id}")
                        .get(semester::get_semester)
                        .put(semester::update_semester)
                        .delete(semester::delete_semester),
                ),
        )
        .push(
            Router::with_path("status-keaktifan-pegawai")
                .get(status_keaktifan_pegawai::list_status_keaktifan_pegawai)
                .post(status_keaktifan_pegawai::create_status_keaktifan_pegawai)
                .push(
                    Router::with_path("{id}")
                        .get(status_keaktifan_pegawai::get_status_keaktifan_pegawai)
                        .put(status_keaktifan_pegawai::update_status_keaktifan_pegawai)
                        .delete(status_keaktifan_pegawai::delete_status_keaktifan_pegawai),
                ),
        )
        .push(
            Router::with_path("status-kepegawaian")
                .get(status_kepegawaian::list_status_kepegawaian)
                .post(status_kepegawaian::create_status_kepegawaian)
                .push(
                    Router::with_path("{id}")
                        .get(status_kepegawaian::get_status_kepegawaian)
                        .put(status_kepegawaian::update_status_kepegawaian)
                        .delete(status_kepegawaian::delete_status_kepegawaian),
                ),
        )
        .push(
            Router::with_path("status-mahasiswa")
                .get(status_mahasiswa::list_status_mahasiswa)
                .post(status_mahasiswa::create_status_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(status_mahasiswa::get_status_mahasiswa)
                        .put(status_mahasiswa::update_status_mahasiswa)
                        .delete(status_mahasiswa::delete_status_mahasiswa),
                ),
        )
        .push(
            Router::with_path("tahun-ajaran")
                .get(tahun_ajaran::list_tahun_ajaran)
                .post(tahun_ajaran::create_tahun_ajaran)
                .push(
                    Router::with_path("{id}")
                        .get(tahun_ajaran::get_tahun_ajaran)
                        .put(tahun_ajaran::update_tahun_ajaran)
                        .delete(tahun_ajaran::delete_tahun_ajaran),
                ),
        )
        .push(
            Router::with_path("tingkat-prestasi")
                .get(tingkat_prestasi::list_tingkat_prestasi)
                .post(tingkat_prestasi::create_tingkat_prestasi)
                .push(
                    Router::with_path("{id}")
                        .get(tingkat_prestasi::get_tingkat_prestasi)
                        .put(tingkat_prestasi::update_tingkat_prestasi)
                        .delete(tingkat_prestasi::delete_tingkat_prestasi),
                ),
        )
        .push(
            Router::with_path("wilayah")
                .get(wilayah::list_wilayah)
                .post(wilayah::create_wilayah)
                .push(
                    Router::with_path("{id}")
                        .get(wilayah::get_wilayah)
                        .put(wilayah::update_wilayah)
                        .delete(wilayah::delete_wilayah),
                ),
        )
}
