[package]
name = "test_macro"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"

[dependencies]
sea-orm = { version = "2.0.0", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
    "debug-print",
    "mock",
    "rbac",
    "schema-sync",
    "with-chrono",
    "with-time",
    "with-json",
    "with-rust_decimal",
    "with-bigdecimal",
    "with-uuid",
    "postgres-vector",
    "postgres-array",
    "with-arrow",
] }
uuid = "1"
chrono = "0.4"
