//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_prior_learning_recognition_transaction",
    table_name = "decrees"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub decree_number: String,
    pub decree_date: Date,
    pub evaluation_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "evaluation_id", to = "id")]
    pub evaluation: BelongsTo<Option<crate::models::academic::prior_learning_recognition::transaction::evaluations::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
