//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_prior_learning_recognition_transaction",
    table_name = "evaluators"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub individual_id: Option<Uuid>,
    pub evaluator_type_id: Option<Uuid>,
    pub recognition_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "individual_id", to = "id")]
    pub individual: BelongsTo<Option<crate::models::person::master::individual::Entity>>,
    #[sea_orm(belongs_to, from = "evaluator_type_id", to = "id")]
    pub evaluator_type: BelongsTo<Option<crate::models::academic::prior_learning_recognition::reference::evaluator_types::Entity>>,
    #[sea_orm(belongs_to, from = "recognition_id", to = "id")]
    pub recognition: BelongsTo<Option<crate::models::academic::prior_learning_recognition::transaction::recognitions::Entity>>,
    #[sea_orm(has_many)]
    pub evaluations: HasMany<crate::models::academic::prior_learning_recognition::transaction::evaluations::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
