//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::decrees::Entity as AcademicPriorLearningRecognitionTransactionDecrees;
pub use super::evaluation_details::Entity as AcademicPriorLearningRecognitionTransactionEvaluationDetails;
pub use super::evaluations::Entity as AcademicPriorLearningRecognitionTransactionEvaluations;
pub use super::evaluators::Entity as AcademicPriorLearningRecognitionTransactionEvaluators;
pub use super::recognitions::Entity as AcademicPriorLearningRecognitionTransactionRecognitions;
