//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::decrees::Entity as Decrees;
pub use super::evaluation_details::Entity as EvaluationDetails;
pub use super::evaluations::Entity as Evaluations;
pub use super::evaluators::Entity as Evaluators;
pub use super::recognitions::Entity as Recognitions;
