//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_prior_learning_recognition_transaction",
    table_name = "recognitions"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub candidate_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub curriculum_id: Uuid,
    pub unit_id: Uuid,
    #[sea_orm(belongs_to, from = "candidate_id", to = "id")]
    pub candidate: BelongsTo<Option<crate::models::academic::candidate::master::candidates::Entity>>,
    #[sea_orm(belongs_to, from = "curriculum_id", to = "id")]
    pub curriculum: BelongsTo<crate::models::academic::course::master::curriculums::Entity>,
    #[sea_orm(belongs_to, from = "unit_id", to = "id")]
    pub unit: BelongsTo<crate::models::institution::master::units::Entity>,
    #[sea_orm(has_many)]
    pub evaluations: HasMany<crate::models::academic::prior_learning_recognition::transaction::evaluations::Entity>,
    #[sea_orm(has_many)]
    pub evaluators: HasMany<crate::models::academic::prior_learning_recognition::transaction::evaluators::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
