//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_survey_master", table_name = "answers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: i32,
    pub alphabet_code: Option<String>,
    pub name: String,
    pub question_id: Uuid,
    #[sea_orm(column_type = "Double")]
    pub point: f64,
    #[sea_orm(column_type = "Text", nullable)]
    pub suggestion: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "question_id", to = "id")]
    pub question: BelongsTo<crate::models::academic::survey::master::questions::Entity>,
    #[sea_orm(has_many)]
    pub responds: HasMany<crate::models::academic::survey::transaction::responds::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
