//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_survey_master", table_name = "bundle_question")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub bundle_id: Uuid,
    pub question_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "bundle_id", to = "id")]
    pub bundle: BelongsTo<crate::models::academic::survey::master::bundles::Entity>,
    #[sea_orm(belongs_to, from = "question_id", to = "id")]
    pub question: BelongsTo<crate::models::academic::survey::master::questions::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
