//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::answers::Entity as AcademicSurveyMasterAnswers;
pub use super::bundle_question::Entity as AcademicSurveyMasterBundleQuestion;
pub use super::bundles::Entity as AcademicSurveyMasterBundles;
pub use super::questions::Entity as AcademicSurveyMasterQuestions;
