//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::answers::Entity as Answers;
pub use super::bundle_question::Entity as BundleQuestion;
pub use super::bundles::Entity as Bundles;
pub use super::questions::Entity as Questions;
