//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_survey_master", table_name = "questions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: i32,
    pub alphabet_code: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub institution_id: Uuid,
    pub question_variety_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub suggestion: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "institution_id", to = "id")]
    pub institution: BelongsTo<crate::models::institution::master::institutions::Entity>,
    #[sea_orm(belongs_to, from = "question_variety_id", to = "id")]
    pub question_variety: BelongsTo<Option<crate::models::academic::survey::reference::question_varieties::Entity>>,
    #[sea_orm(has_many)]
    pub answers: HasMany<crate::models::academic::survey::master::answers::Entity>,
    #[sea_orm(has_many)]
    pub bundle_question: HasMany<crate::models::academic::survey::master::bundle_question::Entity>,
    #[sea_orm(has_many)]
    pub responds: HasMany<crate::models::academic::survey::transaction::responds::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
