use serde::{Deserialize, Serialize};
use salvo::oapi::ToSchema;
use uuid::Uuid;
use validator::Validate;
use chrono::{NaiveDate, NaiveDateTime, NaiveTime};


#[derive(Serialize, Deserialize, ToSchema, Debug, Clone, Default)]
pub struct BiodataMahasiswaQuery {
    pub page: Option<u64>,
    pub page_size: Option<u64>,
}

#[derive(Serialize, Deserialize, ToSchema, Debug, Clone)]
pub struct BiodataMahasiswaResponse {
    pub id: Uuid,
    pub nama_mahasiswa: Option<String>,
    pub jenis_kelamin: Option<String>,
    pub tempat_lahir: Option<String>,
    pub tanggal_lahir: Option<NaiveDate>,
    pub id_mahasiswa: Option<Uuid>,
    pub id_agama: Option<i32>,
    pub nama_agama: Option<String>,
    pub nik: Option<String>,
    pub nisn: Option<String>,
    pub npwp: Option<String>,
    pub id_negara: Option<String>,
    pub kewarganegaraan: Option<String>,
    pub jalan: Option<String>,
    pub dusun: Option<String>,
    pub rt: Option<i32>,
    pub rw: Option<i32>,
    pub kelurahan: Option<String>,
    pub kode_pos: Option<String>,
    pub id_wilayah: Option<String>,
    pub nama_wilayah: Option<String>,
    pub id_jenis_tinggal: Option<String>,
    pub nama_jenis_tinggal: Option<String>,
    pub id_alat_transportasi: Option<String>,
    pub nama_alat_transportasi: Option<String>,
    pub telepon: Option<String>,
    pub handphone: Option<String>,
    pub email: Option<String>,
    pub penerima_kps: Option<bool>,
    pub nomor_kps: Option<String>,
    pub nik_ayah: Option<String>,
    pub nama_ayah: Option<String>,
    pub tanggal_lahir_ayah: Option<NaiveDate>,
    pub id_pendidikan_ayah: Option<i32>,
    pub nama_pendidikan_ayah: Option<String>,
    pub id_pekerjaan_ayah: Option<i32>,
    pub nama_pekerjaan_ayah: Option<String>,
    pub id_penghasilan_ayah: Option<i32>,
    pub nama_penghasilan_ayah: Option<String>,
    pub nik_ibu: Option<String>,
    pub nama_ibu_kandung: Option<String>,
    pub tanggal_lahir_ibu: Option<NaiveDate>,
    pub id_pendidikan_ibu: Option<i32>,
    pub nama_pendidikan_ibu: Option<String>,
    pub id_pekerjaan_ibu: Option<i32>,
    pub nama_pekerjaan_ibu: Option<String>,
    pub id_penghasilan_ibu: Option<i32>,
    pub nama_penghasilan_ibu: Option<String>,
    pub nama_wali: Option<String>,
    pub tanggal_lahir_wali: Option<NaiveDate>,
    pub id_pendidikan_wali: Option<i32>,
    pub nama_pendidikan_wali: Option<String>,
    pub id_pekerjaan_wali: Option<i32>,
    pub nama_pekerjaan_wali: Option<String>,
    pub id_penghasilan_wali: Option<i32>,
    pub nama_penghasilan_wali: Option<String>,
    pub id_kebutuhan_khusus_mahasiswa: Option<i32>,
    pub nama_kebutuhan_khusus_mahasiswa: Option<String>,
    pub id_kebutuhan_khusus_ayah: Option<i32>,
    pub nama_kebutuhan_khusus_ayah: Option<String>,
    pub id_kebutuhan_khusus_ibu: Option<i32>,
    pub nama_kebutuhan_khusus_ibu: Option<String>,
    pub status_sync: Option<String>,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub sync_at: Option<NaiveDateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

#[derive(Serialize, Deserialize, ToSchema, Debug, Clone, Validate)]
pub struct CreateBiodataMahasiswaRequest {
    pub nama_mahasiswa: Option<String>,
    pub jenis_kelamin: Option<String>,
    pub tempat_lahir: Option<String>,
    pub tanggal_lahir: Option<NaiveDate>,
    pub id_mahasiswa: Option<Uuid>,
    pub id_agama: Option<i32>,
    pub nama_agama: Option<String>,
    pub nik: Option<String>,
    pub nisn: Option<String>,
    pub npwp: Option<String>,
    pub id_negara: Option<String>,
    pub kewarganegaraan: Option<String>,
    pub jalan: Option<String>,
    pub dusun: Option<String>,
    pub rt: Option<i32>,
    pub rw: Option<i32>,
    pub kelurahan: Option<String>,
    pub kode_pos: Option<String>,
    pub id_wilayah: Option<String>,
    pub nama_wilayah: Option<String>,
    pub id_jenis_tinggal: Option<String>,
    pub nama_jenis_tinggal: Option<String>,
    pub id_alat_transportasi: Option<String>,
    pub nama_alat_transportasi: Option<String>,
    pub telepon: Option<String>,
    pub handphone: Option<String>,
    pub email: Option<String>,
    pub penerima_kps: Option<bool>,
    pub nomor_kps: Option<String>,
    pub nik_ayah: Option<String>,
    pub nama_ayah: Option<String>,
    pub tanggal_lahir_ayah: Option<NaiveDate>,
    pub id_pendidikan_ayah: Option<i32>,
    pub nama_pendidikan_ayah: Option<String>,
    pub id_pekerjaan_ayah: Option<i32>,
    pub nama_pekerjaan_ayah: Option<String>,
    pub id_penghasilan_ayah: Option<i32>,
    pub nama_penghasilan_ayah: Option<String>,
    pub nik_ibu: Option<String>,
    pub nama_ibu_kandung: Option<String>,
    pub tanggal_lahir_ibu: Option<NaiveDate>,
    pub id_pendidikan_ibu: Option<i32>,
    pub nama_pendidikan_ibu: Option<String>,
    pub id_pekerjaan_ibu: Option<i32>,
    pub nama_pekerjaan_ibu: Option<String>,
    pub id_penghasilan_ibu: Option<i32>,
    pub nama_penghasilan_ibu: Option<String>,
    pub nama_wali: Option<String>,
    pub tanggal_lahir_wali: Option<NaiveDate>,
    pub id_pendidikan_wali: Option<i32>,
    pub nama_pendidikan_wali: Option<String>,
    pub id_pekerjaan_wali: Option<i32>,
    pub nama_pekerjaan_wali: Option<String>,
    pub id_penghasilan_wali: Option<i32>,
    pub nama_penghasilan_wali: Option<String>,
    pub id_kebutuhan_khusus_mahasiswa: Option<i32>,
    pub nama_kebutuhan_khusus_mahasiswa: Option<String>,
    pub id_kebutuhan_khusus_ayah: Option<i32>,
    pub nama_kebutuhan_khusus_ayah: Option<String>,
    pub id_kebutuhan_khusus_ibu: Option<i32>,
    pub nama_kebutuhan_khusus_ibu: Option<String>,
    pub status_sync: Option<String>,
}

#[derive(Serialize, Deserialize, ToSchema, Debug, Clone, Validate)]
pub struct UpdateBiodataMahasiswaRequest {
    pub nama_mahasiswa: Option<String>,
    pub jenis_kelamin: Option<String>,
    pub tempat_lahir: Option<String>,
    pub tanggal_lahir: Option<NaiveDate>,
    pub id_mahasiswa: Option<Uuid>,
    pub id_agama: Option<i32>,
    pub nama_agama: Option<String>,
    pub nik: Option<String>,
    pub nisn: Option<String>,
    pub npwp: Option<String>,
    pub id_negara: Option<String>,
    pub kewarganegaraan: Option<String>,
    pub jalan: Option<String>,
    pub dusun: Option<String>,
    pub rt: Option<i32>,
    pub rw: Option<i32>,
    pub kelurahan: Option<String>,
    pub kode_pos: Option<String>,
    pub id_wilayah: Option<String>,
    pub nama_wilayah: Option<String>,
    pub id_jenis_tinggal: Option<String>,
    pub nama_jenis_tinggal: Option<String>,
    pub id_alat_transportasi: Option<String>,
    pub nama_alat_transportasi: Option<String>,
    pub telepon: Option<String>,
    pub handphone: Option<String>,
    pub email: Option<String>,
    pub penerima_kps: Option<bool>,
    pub nomor_kps: Option<String>,
    pub nik_ayah: Option<String>,
    pub nama_ayah: Option<String>,
    pub tanggal_lahir_ayah: Option<NaiveDate>,
    pub id_pendidikan_ayah: Option<i32>,
    pub nama_pendidikan_ayah: Option<String>,
    pub id_pekerjaan_ayah: Option<i32>,
    pub nama_pekerjaan_ayah: Option<String>,
    pub id_penghasilan_ayah: Option<i32>,
    pub nama_penghasilan_ayah: Option<String>,
    pub nik_ibu: Option<String>,
    pub nama_ibu_kandung: Option<String>,
    pub tanggal_lahir_ibu: Option<NaiveDate>,
    pub id_pendidikan_ibu: Option<i32>,
    pub nama_pendidikan_ibu: Option<String>,
    pub id_pekerjaan_ibu: Option<i32>,
    pub nama_pekerjaan_ibu: Option<String>,
    pub id_penghasilan_ibu: Option<i32>,
    pub nama_penghasilan_ibu: Option<String>,
    pub nama_wali: Option<String>,
    pub tanggal_lahir_wali: Option<NaiveDate>,
    pub id_pendidikan_wali: Option<i32>,
    pub nama_pendidikan_wali: Option<String>,
    pub id_pekerjaan_wali: Option<i32>,
    pub nama_pekerjaan_wali: Option<String>,
    pub id_penghasilan_wali: Option<i32>,
    pub nama_penghasilan_wali: Option<String>,
    pub id_kebutuhan_khusus_mahasiswa: Option<i32>,
    pub nama_kebutuhan_khusus_mahasiswa: Option<String>,
    pub id_kebutuhan_khusus_ayah: Option<i32>,
    pub nama_kebutuhan_khusus_ayah: Option<String>,
    pub id_kebutuhan_khusus_ibu: Option<i32>,
    pub nama_kebutuhan_khusus_ibu: Option<String>,
    pub status_sync: Option<String>,
}

#[derive(Serialize, Deserialize, ToSchema, Debug, Clone)]
pub struct PaginatedBiodataMahasiswaResponse {
    pub data: Vec<BiodataMahasiswaResponse>,
    pub total: u64,
    pub page: u64,
    pub page_size: u64,
    pub total_pages: u64,
}
