use serde::{Deserialize, Serialize};
use salvo::oapi::ToSchema;
use uuid::Uuid;
use validator::Validate;
use chrono::{NaiveDate, NaiveDateTime};


#[derive(Serialize, Deserialize, ToSchema, Debug, Clone, Default)]
pub struct MahasiswaLulusanDropoutQuery {
    pub page: Option<u64>,
    pub page_size: Option<u64>,
}

#[derive(Serialize, Deserialize, ToSchema, Debug, Clone)]
pub struct MahasiswaLulusanDropoutResponse {
    pub id: Uuid,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub sync_at: Option<NaiveDateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub id_registrasi_mahasiswa: Option<Uuid>,
    pub id_mahasiswa: Option<Uuid>,
    pub id_perguruan_tinggi: Option<Uuid>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub nim: Option<String>,
    pub nama_mahasiswa: Option<String>,
    pub angkatan: Option<String>,
    pub tgl_masuk_sp: Option<NaiveDate>,
    pub tgl_create: Option<NaiveDate>,
    pub tgl_keluar: Option<NaiveDate>,
    pub tanggal_keluar: Option<NaiveDate>,
    pub id_jenis_keluar: String,
    pub nama_jenis_keluar: String,
    pub id_periode_keluar: String,
    pub keterangan: Option<String>,
    pub nomor_sk_yudisium: Option<String>,
    pub tanggal_sk_yudisium: Option<NaiveDate>,
    pub ipk: Option<f32>,
    pub nomor_ijazah: Option<String>,
    pub asal_ijazah: String,
    pub no_sertifikat_profesi: Option<String>,
    pub tanggal_terbit_ijazah: Option<NaiveDate>,
    pub jalur_skripsi: Option<String>,
    pub judul_skripsi: Option<String>,
    pub bulan_awal_bimbingan: Option<String>,
    pub bulan_akhir_bimbingan: Option<String>,
    pub id_dosen: Option<Uuid>,
    pub nidn: Option<String>,
    pub nuptk: Option<String>,
    pub nama_dosen: Option<String>,
    pub pembimbing_ke: Option<i32>,
    pub skhun: Option<String>,
    pub no_peserta_ujian: Option<String>,
    pub sks_diakui: Option<String>,
    pub id_jns_daftar: Option<String>,
    pub nm_jns_daftar: Option<String>,
    pub id_jalur_masuk: Option<String>,
    pub id_pembiayaan: Option<String>,
    pub biaya_masuk_kuliah: Option<String>,
    pub id_minat_bidang: Option<String>,
    pub bidang_mayor: Option<String>,
    pub bidang_minor: Option<String>,
    pub a_pindah_mhs_asing: Option<String>,
    pub id_pt_asal: Option<Uuid>,
    pub id_prodi_asal: Option<Uuid>,
    pub nm_pt_asal: Option<String>,
    pub nm_prodi_asal: Option<String>,
    pub namapt: Option<String>,
    pub id_jur: Option<String>,
    pub nm_smt: Option<String>,
    pub status_sync: Option<String>,
}

#[derive(Serialize, Deserialize, ToSchema, Debug, Clone, Validate)]
pub struct CreateMahasiswaLulusanDropoutRequest {
    pub id_registrasi_mahasiswa: Option<Uuid>,
    pub id_mahasiswa: Option<Uuid>,
    pub id_perguruan_tinggi: Option<Uuid>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub nim: Option<String>,
    pub nama_mahasiswa: Option<String>,
    pub angkatan: Option<String>,
    pub tgl_masuk_sp: Option<NaiveDate>,
    pub tgl_create: Option<NaiveDate>,
    pub tgl_keluar: Option<NaiveDate>,
    pub tanggal_keluar: Option<NaiveDate>,
    pub id_jenis_keluar: String,
    pub nama_jenis_keluar: String,
    pub id_periode_keluar: String,
    pub keterangan: Option<String>,
    pub nomor_sk_yudisium: Option<String>,
    pub tanggal_sk_yudisium: Option<NaiveDate>,
    pub ipk: Option<f32>,
    pub nomor_ijazah: Option<String>,
    pub asal_ijazah: String,
    pub no_sertifikat_profesi: Option<String>,
    pub tanggal_terbit_ijazah: Option<NaiveDate>,
    pub jalur_skripsi: Option<String>,
    pub judul_skripsi: Option<String>,
    pub bulan_awal_bimbingan: Option<String>,
    pub bulan_akhir_bimbingan: Option<String>,
    pub id_dosen: Option<Uuid>,
    pub nidn: Option<String>,
    pub nuptk: Option<String>,
    pub nama_dosen: Option<String>,
    pub pembimbing_ke: Option<i32>,
    pub skhun: Option<String>,
    pub no_peserta_ujian: Option<String>,
    pub sks_diakui: Option<String>,
    pub id_jns_daftar: Option<String>,
    pub nm_jns_daftar: Option<String>,
    pub id_jalur_masuk: Option<String>,
    pub id_pembiayaan: Option<String>,
    pub biaya_masuk_kuliah: Option<String>,
    pub id_minat_bidang: Option<String>,
    pub bidang_mayor: Option<String>,
    pub bidang_minor: Option<String>,
    pub a_pindah_mhs_asing: Option<String>,
    pub id_pt_asal: Option<Uuid>,
    pub id_prodi_asal: Option<Uuid>,
    pub nm_pt_asal: Option<String>,
    pub nm_prodi_asal: Option<String>,
    pub namapt: Option<String>,
    pub id_jur: Option<String>,
    pub nm_smt: Option<String>,
    pub status_sync: Option<String>,
}

#[derive(Serialize, Deserialize, ToSchema, Debug, Clone, Validate)]
pub struct UpdateMahasiswaLulusanDropoutRequest {
    pub id_registrasi_mahasiswa: Option<Uuid>,
    pub id_mahasiswa: Option<Uuid>,
    pub id_perguruan_tinggi: Option<Uuid>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub nim: Option<String>,
    pub nama_mahasiswa: Option<String>,
    pub angkatan: Option<String>,
    pub tgl_masuk_sp: Option<NaiveDate>,
    pub tgl_create: Option<NaiveDate>,
    pub tgl_keluar: Option<NaiveDate>,
    pub tanggal_keluar: Option<NaiveDate>,
    pub id_jenis_keluar: Option<String>,
    pub nama_jenis_keluar: Option<String>,
    pub id_periode_keluar: Option<String>,
    pub keterangan: Option<String>,
    pub nomor_sk_yudisium: Option<String>,
    pub tanggal_sk_yudisium: Option<NaiveDate>,
    pub ipk: Option<f32>,
    pub nomor_ijazah: Option<String>,
    pub asal_ijazah: Option<String>,
    pub no_sertifikat_profesi: Option<String>,
    pub tanggal_terbit_ijazah: Option<NaiveDate>,
    pub jalur_skripsi: Option<String>,
    pub judul_skripsi: Option<String>,
    pub bulan_awal_bimbingan: Option<String>,
    pub bulan_akhir_bimbingan: Option<String>,
    pub id_dosen: Option<Uuid>,
    pub nidn: Option<String>,
    pub nuptk: Option<String>,
    pub nama_dosen: Option<String>,
    pub pembimbing_ke: Option<i32>,
    pub skhun: Option<String>,
    pub no_peserta_ujian: Option<String>,
    pub sks_diakui: Option<String>,
    pub id_jns_daftar: Option<String>,
    pub nm_jns_daftar: Option<String>,
    pub id_jalur_masuk: Option<String>,
    pub id_pembiayaan: Option<String>,
    pub biaya_masuk_kuliah: Option<String>,
    pub id_minat_bidang: Option<String>,
    pub bidang_mayor: Option<String>,
    pub bidang_minor: Option<String>,
    pub a_pindah_mhs_asing: Option<String>,
    pub id_pt_asal: Option<Uuid>,
    pub id_prodi_asal: Option<Uuid>,
    pub nm_pt_asal: Option<String>,
    pub nm_prodi_asal: Option<String>,
    pub namapt: Option<String>,
    pub id_jur: Option<String>,
    pub nm_smt: Option<String>,
    pub status_sync: Option<String>,
}

#[derive(Serialize, Deserialize, ToSchema, Debug, Clone)]
pub struct PaginatedMahasiswaLulusanDropoutResponse {
    pub data: Vec<MahasiswaLulusanDropoutResponse>,
    pub total: u64,
    pub page: u64,
    pub page_size: u64,
    pub total_pages: u64,
}
