use serde::{Deserialize, Serialize};
use salvo::oapi::ToSchema;
use uuid::Uuid;
use validator::Validate;
use chrono::{NaiveDate, NaiveDateTime, NaiveTime};


#[derive(Serialize, Deserialize, ToSchema, Debug, Clone, Default)]
pub struct RiwayatPendidikanMahasiswaQuery {
    pub page: Option<u64>,
    pub page_size: Option<u64>,
}

#[derive(Serialize, Deserialize, ToSchema, Debug, Clone)]
pub struct RiwayatPendidikanMahasiswaResponse {
    pub id: Uuid,
    pub id_registrasi_mahasiswa: Option<Uuid>,
    pub id_mahasiswa: Option<Uuid>,
    pub nim: Option<String>,
    pub nama_mahasiswa: Option<String>,
    pub id_jenis_daftar: Option<i32>,
    pub nama_jenis_daftar: Option<String>,
    pub id_jalur_daftar: Option<i32>,
    pub id_periode_masuk: Option<String>,
    pub nama_periode_masuk: Option<String>,
    pub id_jenis_keluar: Option<i32>,
    pub keterangan_keluar: Option<String>,
    pub id_perguruan_tinggi: Option<Uuid>,
    pub nama_perguruan_tinggi: Option<String>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub sks_diakui: Option<f32>,
    pub id_perguruan_tinggi_asal: Option<Uuid>,
    pub nama_perguruan_tinggi_asal: Option<String>,
    pub id_prodi_asal: Option<Uuid>,
    pub nama_program_studi_asal: Option<String>,
    pub jenis_kelamin: Option<String>,
    pub tanggal_daftar: Option<NaiveDate>,
    pub nama_ibu_kandung: Option<String>,
    pub id_pembiayaan: Option<i32>,
    pub biaya_masuk: Option<i32>,
    pub id_bidang_minat: Option<String>,
    pub nm_bidang_minat: Option<String>,
    pub id_periode_keluar: Option<String>,
    pub tanggal_keluar: Option<NaiveDate>,
    pub last_update: Option<NaiveDate>,
    pub tgl_create: Option<NaiveDate>,
    pub status_sync: Option<String>,
    pub nama_pembiayaan_awal: Option<String>,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub sync_at: Option<NaiveDateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

#[derive(Serialize, Deserialize, ToSchema, Debug, Clone, Validate)]
pub struct CreateRiwayatPendidikanMahasiswaRequest {
    pub id_registrasi_mahasiswa: Option<Uuid>,
    pub id_mahasiswa: Option<Uuid>,
    pub nim: Option<String>,
    pub nama_mahasiswa: Option<String>,
    pub id_jenis_daftar: Option<i32>,
    pub nama_jenis_daftar: Option<String>,
    pub id_jalur_daftar: Option<i32>,
    pub id_periode_masuk: Option<String>,
    pub nama_periode_masuk: Option<String>,
    pub id_jenis_keluar: Option<i32>,
    pub keterangan_keluar: Option<String>,
    pub id_perguruan_tinggi: Option<Uuid>,
    pub nama_perguruan_tinggi: Option<String>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub sks_diakui: Option<f32>,
    pub id_perguruan_tinggi_asal: Option<Uuid>,
    pub nama_perguruan_tinggi_asal: Option<String>,
    pub id_prodi_asal: Option<Uuid>,
    pub nama_program_studi_asal: Option<String>,
    pub jenis_kelamin: Option<String>,
    pub tanggal_daftar: Option<NaiveDate>,
    pub nama_ibu_kandung: Option<String>,
    pub id_pembiayaan: Option<i32>,
    pub biaya_masuk: Option<i32>,
    pub id_bidang_minat: Option<String>,
    pub nm_bidang_minat: Option<String>,
    pub id_periode_keluar: Option<String>,
    pub tanggal_keluar: Option<NaiveDate>,
    pub last_update: Option<NaiveDate>,
    pub tgl_create: Option<NaiveDate>,
    pub status_sync: Option<String>,
    pub nama_pembiayaan_awal: Option<String>,
}

#[derive(Serialize, Deserialize, ToSchema, Debug, Clone, Validate)]
pub struct UpdateRiwayatPendidikanMahasiswaRequest {
    pub id_registrasi_mahasiswa: Option<Uuid>,
    pub id_mahasiswa: Option<Uuid>,
    pub nim: Option<String>,
    pub nama_mahasiswa: Option<String>,
    pub id_jenis_daftar: Option<i32>,
    pub nama_jenis_daftar: Option<String>,
    pub id_jalur_daftar: Option<i32>,
    pub id_periode_masuk: Option<String>,
    pub nama_periode_masuk: Option<String>,
    pub id_jenis_keluar: Option<i32>,
    pub keterangan_keluar: Option<String>,
    pub id_perguruan_tinggi: Option<Uuid>,
    pub nama_perguruan_tinggi: Option<String>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub sks_diakui: Option<f32>,
    pub id_perguruan_tinggi_asal: Option<Uuid>,
    pub nama_perguruan_tinggi_asal: Option<String>,
    pub id_prodi_asal: Option<Uuid>,
    pub nama_program_studi_asal: Option<String>,
    pub jenis_kelamin: Option<String>,
    pub tanggal_daftar: Option<NaiveDate>,
    pub nama_ibu_kandung: Option<String>,
    pub id_pembiayaan: Option<i32>,
    pub biaya_masuk: Option<i32>,
    pub id_bidang_minat: Option<String>,
    pub nm_bidang_minat: Option<String>,
    pub id_periode_keluar: Option<String>,
    pub tanggal_keluar: Option<NaiveDate>,
    pub last_update: Option<NaiveDate>,
    pub tgl_create: Option<NaiveDate>,
    pub status_sync: Option<String>,
    pub nama_pembiayaan_awal: Option<String>,
}

#[derive(Serialize, Deserialize, ToSchema, Debug, Clone)]
pub struct PaginatedRiwayatPendidikanMahasiswaResponse {
    pub data: Vec<RiwayatPendidikanMahasiswaResponse>,
    pub total: u64,
    pub page: u64,
    pub page_size: u64,
    pub total_pages: u64,
}
