//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "contact_master", table_name = "electronic_mails")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub email_address: String,
    pub electronic_mail_type_id: Option<Uuid>,
    pub electronic_mailable_id: Uuid,
    pub electronic_mailable_type: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "electronic_mail_type_id", to = "id")]
    pub electronic_mail_type: BelongsTo<crate::models::contact::reference::electronic_mail_types::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
