//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "contact_master", table_name = "phones")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub phone_number: String,
    pub phone_type_id: Option<Uuid>,
    pub phoneable_id: Uuid,
    pub phoneable_type: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "phone_type_id", to = "id")]
    pub phone_type: BelongsTo<Option<crate::models::contact::reference::phone_types::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
