//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::electronic_mails::Entity as ElectronicMails;
pub use super::phones::Entity as Phones;
pub use super::residences::Entity as Residences;
pub use super::websites::Entity as Websites;
