//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::electronic_mails::Entity as ContactMasterElectronicMails;
pub use super::phones::Entity as ContactMasterPhones;
pub use super::residences::Entity as ContactMasterResidences;
pub use super::websites::Entity as ContactMasterWebsites;
