//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "contact_master", table_name = "residences")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub street: String,
    pub citizens_association: i32,
    pub neighborhood_association: i32,
    pub province_id: Option<Uuid>,
    pub regency_id: Option<Uuid>,
    pub sub_district_id: Option<Uuid>,
    pub village_id: Option<Uuid>,
    pub residence_type_id: Option<Uuid>,
    pub residenceable_type: Option<String>,
    pub residenceable_id: Option<Uuid>,
    #[sea_orm(column_type = "Double", nullable)]
    pub latitude: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub longitude: Option<f64>,
    pub zoom: Option<i32>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "residence_type_id", to = "id")]
    pub residence_type: BelongsTo<Option<crate::models::contact::reference::residence_types::Entity>>,
    #[sea_orm(belongs_to, from = "province_id", to = "id")]
    pub province: BelongsTo<Option<crate::models::location::provinces::Entity>>,
    #[sea_orm(belongs_to, from = "regency_id", to = "id")]
    pub regency: BelongsTo<Option<crate::models::location::regencies::Entity>>,
    #[sea_orm(belongs_to, from = "sub_district_id", to = "id")]
    pub sub_district: BelongsTo<Option<crate::models::location::sub_districts::Entity>>,
    #[sea_orm(belongs_to, from = "village_id", to = "id")]
    pub village: BelongsTo<Option<crate::models::location::villages::Entity>>,
    #[sea_orm(has_many)]
    pub buildings: HasMany<crate::models::building::master::buildings::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
