//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_student_campaign", table_name = "convertions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub student_id: Uuid,
    pub course_id: Uuid,
    pub grade_id: Uuid,
    pub transfer_code: String,
    pub transfer_name: String,
    #[sea_orm(column_type = "Double")]
    pub transfer_credit: f64,
    pub transfer_grade: String,
    pub is_lock: Option<DateTime>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub feeder_id: Option<Uuid>,
    pub name: Option<String>,
    pub academic_year_id: Option<Uuid>,
    pub origin_code: Option<String>,
    pub origin_name: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub origin_credit: Option<f64>,
    pub origin_grade: Option<String>,
    #[sea_orm(belongs_to, from = "student_id", to = "id")]
    pub student: BelongsTo<crate::models::academic::student::master::students::Entity>,
    #[sea_orm(belongs_to, from = "course_id", to = "id")]
    pub course: BelongsTo<crate::models::academic::course::master::courses::Entity>,
    #[sea_orm(belongs_to, from = "grade_id", to = "id")]
    pub grade: BelongsTo<crate::models::academic::campaign::transaction::grades::Entity>,
    #[sea_orm(belongs_to, from = "academic_year_id", to = "id")]
    pub academic_year: BelongsTo<Option<crate::models::academic::general::reference::academic_years::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
