//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_student_campaign",
    table_name = "detail_activities"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Double", nullable)]
    pub mark: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub credit: Option<f64>,
    pub grade_id: Option<Uuid>,
    pub course_id: Uuid,
    pub activity_id: Uuid,
    pub teach_id: Option<Uuid>,
    pub is_lock: Option<bool>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub feeder_id: Option<Uuid>,
    pub name: Option<String>,
    pub feeder_grade_id: Option<Uuid>,
    pub curiculum_detail_sequence: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
