//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_student_campaign",
    table_name = "detail_activities"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Double", nullable)]
    pub mark: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub credit: Option<f64>,
    pub grade_id: Option<Uuid>,
    pub course_id: Uuid,
    pub activity_id: Uuid,
    pub teach_id: Option<Uuid>,
    pub is_lock: Option<bool>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub feeder_id: Option<Uuid>,
    pub name: Option<String>,
    pub feeder_grade_id: Option<Uuid>,
    pub curiculum_detail_sequence: Option<i32>,
    #[sea_orm(belongs_to, from = "grade_id", to = "id")]
    pub grade: BelongsTo<Option<crate::models::academic::campaign::transaction::grades::Entity>>,
    #[sea_orm(belongs_to, from = "course_id", to = "id")]
    pub course: BelongsTo<crate::models::academic::course::master::courses::Entity>,
    #[sea_orm(belongs_to, from = "activity_id", to = "id")]
    pub activity: BelongsTo<crate::models::academic::campaign::transaction::activities::Entity>,
    #[sea_orm(belongs_to, from = "teach_id", to = "id")]
    pub teach: BelongsTo<Option<crate::models::academic::campaign::transaction::teaches::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
