//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::convertions::Entity as Convertions;
pub use super::detail_activities::Entity as DetailActivities;
pub use super::detail_activity_evaluation_components::Entity as DetailActivityEvaluationComponents;
pub use super::student_activities::Entity as StudentActivities;
