//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::convertions::Entity as AcademicStudentCampaignConvertions;
pub use super::detail_activities::Entity as AcademicStudentCampaignDetailActivities;
pub use super::detail_activity_evaluation_components::Entity as AcademicStudentCampaignDetailActivityEvaluationComponents;
pub use super::student_activities::Entity as AcademicStudentCampaignStudentActivities;
