//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_student_campaign",
    table_name = "student_activities"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub cumulative_index: f64,
    #[sea_orm(column_type = "Double")]
    pub grand_cumulative_index: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub total_credit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub grand_total_credit: Option<f64>,
    pub student_id: Uuid,
    pub unit_activity_id: Uuid,
    pub status_id: Uuid,
    pub resign_status_id: Option<Uuid>,
    pub unit_id: Option<Uuid>,
    pub is_lock: Option<bool>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub feeder_id: Option<Uuid>,
    pub finance_id: Option<Uuid>,
    #[sea_orm(column_type = "Double", nullable)]
    pub finance_fee: Option<f64>,
    #[sea_orm(belongs_to, from = "student_id", to = "id")]
    pub student: BelongsTo<crate::models::academic::student::master::students::Entity>,
    #[sea_orm(belongs_to, from = "status_id", to = "id")]
    pub status: BelongsTo<crate::models::academic::student::reference::statuses::Entity>,
    #[sea_orm(belongs_to, from = "resign_status_id", to = "id")]
    pub resign_status: BelongsTo<Option<crate::models::academic::student::reference::resign_statuses::Entity>>,
    #[sea_orm(belongs_to, from = "unit_id", to = "id")]
    pub unit: BelongsTo<Option<crate::models::institution::master::units::Entity>>,
    #[sea_orm(belongs_to, from = "finance_id", to = "id")]
    pub finance: BelongsTo<Option<crate::models::academic::student::reference::finances::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
