//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_student_campaign",
    table_name = "student_activities"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub cumulative_index: f64,
    #[sea_orm(column_type = "Double")]
    pub grand_cumulative_index: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub total_credit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub grand_total_credit: Option<f64>,
    pub student_id: Uuid,
    pub unit_activity_id: Uuid,
    pub status_id: Uuid,
    pub resign_status_id: Option<Uuid>,
    pub unit_id: Option<Uuid>,
    pub is_lock: Option<bool>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub feeder_id: Option<Uuid>,
    pub finance_id: Option<Uuid>,
    #[sea_orm(column_type = "Double", nullable)]
    pub finance_fee: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
