//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "literate", table_name = "educations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: i32,
    pub alphabet_code: String,
    pub abbreviation: String,
    pub name: String,
    pub level_id: Uuid,
    pub group_id: Uuid,
    pub category_id: Uuid,
    pub variety_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "level_id", to = "id")]
    pub level: BelongsTo<crate::models::literate::levels::Entity>,
    #[sea_orm(belongs_to, from = "group_id", to = "id")]
    pub group: BelongsTo<crate::models::literate::groups::Entity>,
    #[sea_orm(belongs_to, from = "category_id", to = "id")]
    pub category: BelongsTo<crate::models::literate::categories::Entity>,
    #[sea_orm(belongs_to, from = "variety_id", to = "id")]
    pub variety: BelongsTo<crate::models::literate::varieties::Entity>,
    #[sea_orm(has_many)]
    pub individuals: HasMany<crate::models::person::master::individual::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
