//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::categories::Entity as Categories;
pub use super::educations::Entity as Educations;
pub use super::groups::Entity as Groups;
pub use super::levels::Entity as Levels;
pub use super::varieties::Entity as Varieties;
