//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::categories::Entity as LiterateCategories;
pub use super::educations::Entity as LiterateEducations;
pub use super::groups::Entity as LiterateGroups;
pub use super::levels::Entity as LiterateLevels;
pub use super::varieties::Entity as LiterateVarieties;
