//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::indeks_prestasi_sementara_mahasiswa::Entity as IndeksPrestasiSementaraMahasiswa;
pub use super::jumlah_dosen::Entity as JumlahDosen;
pub use super::jumlah_mahasiswa::Entity as JumlahMahasiswa;
pub use super::kartu_hasil_studi_mahasiswa::Entity as KartuHasilStudiMahasiswa;
pub use super::kartu_rencana_studi_mahasiswa::Entity as KartuRencanaStudiMahasiswa;
pub use super::laporan::Entity as Laporan;
