//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::indeks_prestasi_sementara_mahasiswa::Entity as FeederRekapitulasiIndeksPrestasiSementaraMahasiswa;
pub use super::jumlah_dosen::Entity as FeederRekapitulasiJumlahDosen;
pub use super::jumlah_mahasiswa::Entity as FeederRekapitulasiJumlahMahasiswa;
pub use super::kartu_hasil_studi_mahasiswa::Entity as FeederRekapitulasiKartuHasilStudiMahasiswa;
pub use super::kartu_rencana_studi_mahasiswa::Entity as FeederRekapitulasiKartuRencanaStudiMahasiswa;
pub use super::laporan::Entity as FeederRekapitulasiLaporan;
