use salvo::prelude::*;

pub mod aktifitas_kuliah_mahasiswa;
pub mod aktifitas_mahasiswa;
pub mod aktifitas_mengajar_dosen;
pub mod anggota_aktifitas_mahasiswa;
pub mod bidang_minat_perguruan_tinggi;
pub mod bimbing_mahasiswa;
pub mod biodata_dosen;
pub mod biodata_mahasiswa;
pub mod detail_nilai_perkuliahan_kelas;
pub mod dosen;
pub mod dosen_pembimbing;
pub mod dosen_pengajar_kelas_kuliah;
pub mod fakultas;
pub mod hitung_transkrip_angkatan_mahasiswa;
pub mod kartu_rencana_studi_mahasiswa;
pub mod kelas_kuliah;
pub mod komponen_evaluasi_kelas;
pub mod konsistensi_data;
pub mod konversi_kampus_merdeka;
pub mod kurikulum;
pub mod mahasiswa;
pub mod mahasiswa_bimbingan_dosen;
pub mod mahasiswa_lulusan_dropout;
pub mod matakuliah;
pub mod matakuliah_kurikulum;
pub mod nilai_perkuliahan_kelas;
pub mod nilai_transfer_pendidikan_mahasiswa;
pub mod penugasan_dosen;
pub mod perguruan_tinggi;
pub mod periode_aktif;
pub mod periode_perkuliahan;
pub mod perkuliahan_mahasiswa;
pub mod peserta_kelas_kuliah;
pub mod prestasi_mahasiswa;
pub mod profil_perguruan_tinggi;
pub mod program_studi;
pub mod rencana_evaluasi;
pub mod rencana_pembelajaran;
pub mod riwayat_fungsional_dosen;
pub mod riwayat_nilai_mahasiswa;
pub mod riwayat_pangkat_dosen;
pub mod riwayat_pendidikan_dosen;
pub mod riwayat_pendidikan_mahasiswa;
pub mod riwayat_penelitian_dosen;
pub mod riwayat_sertifikasi_dosen;
pub mod skala_nilai_program_studi;
pub mod substansi_matakuliah;
pub mod transkrip_mahasiswa;
pub mod uji_mahasiswa;

pub fn router() -> Router {
    Router::with_path("master")
        .push(
            Router::with_path("aktifitas-kuliah-mahasiswa")
                .get(aktifitas_kuliah_mahasiswa::list_aktifitas_kuliah_mahasiswa)
                .post(aktifitas_kuliah_mahasiswa::create_aktifitas_kuliah_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(aktifitas_kuliah_mahasiswa::get_aktifitas_kuliah_mahasiswa)
                        .put(aktifitas_kuliah_mahasiswa::update_aktifitas_kuliah_mahasiswa)
                        .delete(aktifitas_kuliah_mahasiswa::delete_aktifitas_kuliah_mahasiswa),
                ),
        )
        .push(
            Router::with_path("aktifitas-mahasiswa")
                .get(aktifitas_mahasiswa::list_aktifitas_mahasiswa)
                .post(aktifitas_mahasiswa::create_aktifitas_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(aktifitas_mahasiswa::get_aktifitas_mahasiswa)
                        .put(aktifitas_mahasiswa::update_aktifitas_mahasiswa)
                        .delete(aktifitas_mahasiswa::delete_aktifitas_mahasiswa),
                ),
        )
        .push(
            Router::with_path("aktifitas-mengajar-dosen")
                .get(aktifitas_mengajar_dosen::list_aktifitas_mengajar_dosen)
                .post(aktifitas_mengajar_dosen::create_aktifitas_mengajar_dosen)
                .push(
                    Router::with_path("{id}")
                        .get(aktifitas_mengajar_dosen::get_aktifitas_mengajar_dosen)
                        .put(aktifitas_mengajar_dosen::update_aktifitas_mengajar_dosen)
                        .delete(aktifitas_mengajar_dosen::delete_aktifitas_mengajar_dosen),
                ),
        )
        .push(
            Router::with_path("anggota-aktifitas-mahasiswa")
                .get(anggota_aktifitas_mahasiswa::list_anggota_aktifitas_mahasiswa)
                .post(anggota_aktifitas_mahasiswa::create_anggota_aktifitas_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(anggota_aktifitas_mahasiswa::get_anggota_aktifitas_mahasiswa)
                        .put(anggota_aktifitas_mahasiswa::update_anggota_aktifitas_mahasiswa)
                        .delete(anggota_aktifitas_mahasiswa::delete_anggota_aktifitas_mahasiswa),
                ),
        )
        .push(
            Router::with_path("bidang-minat-perguruan-tinggi")
                .get(bidang_minat_perguruan_tinggi::list_bidang_minat_perguruan_tinggi)
                .post(bidang_minat_perguruan_tinggi::create_bidang_minat_perguruan_tinggi)
                .push(
                    Router::with_path("{id}")
                        .get(bidang_minat_perguruan_tinggi::get_bidang_minat_perguruan_tinggi)
                        .put(bidang_minat_perguruan_tinggi::update_bidang_minat_perguruan_tinggi)
                        .delete(bidang_minat_perguruan_tinggi::delete_bidang_minat_perguruan_tinggi),
                ),
        )
        .push(
            Router::with_path("bimbing-mahasiswa")
                .get(bimbing_mahasiswa::list_bimbing_mahasiswa)
                .post(bimbing_mahasiswa::create_bimbing_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(bimbing_mahasiswa::get_bimbing_mahasiswa)
                        .put(bimbing_mahasiswa::update_bimbing_mahasiswa)
                        .delete(bimbing_mahasiswa::delete_bimbing_mahasiswa),
                ),
        )
        .push(
            Router::with_path("biodata-dosen")
                .get(biodata_dosen::list_biodata_dosen)
                .post(biodata_dosen::create_biodata_dosen)
                .push(
                    Router::with_path("{id}")
                        .get(biodata_dosen::get_biodata_dosen)
                        .put(biodata_dosen::update_biodata_dosen)
                        .delete(biodata_dosen::delete_biodata_dosen),
                ),
        )
        .push(
            Router::with_path("biodata-mahasiswa")
                .get(biodata_mahasiswa::list_biodata_mahasiswa)
                .post(biodata_mahasiswa::create_biodata_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(biodata_mahasiswa::get_biodata_mahasiswa)
                        .put(biodata_mahasiswa::update_biodata_mahasiswa)
                        .delete(biodata_mahasiswa::delete_biodata_mahasiswa),
                ),
        )
        .push(
            Router::with_path("detail-nilai-perkuliahan-kelas")
                .get(detail_nilai_perkuliahan_kelas::list_detail_nilai_perkuliahan_kelas)
                .post(detail_nilai_perkuliahan_kelas::create_detail_nilai_perkuliahan_kela)
                .push(
                    Router::with_path("{id}")
                        .get(detail_nilai_perkuliahan_kelas::get_detail_nilai_perkuliahan_kela)
                        .put(detail_nilai_perkuliahan_kelas::update_detail_nilai_perkuliahan_kela)
                        .delete(detail_nilai_perkuliahan_kelas::delete_detail_nilai_perkuliahan_kela),
                ),
        )
        .push(
            Router::with_path("dosen")
                .get(dosen::list_dosen)
                .post(dosen::create_dosen)
                .push(
                    Router::with_path("{id}")
                        .get(dosen::get_dosen)
                        .put(dosen::update_dosen)
                        .delete(dosen::delete_dosen),
                ),
        )
        .push(
            Router::with_path("dosen-pembimbing")
                .get(dosen_pembimbing::list_dosen_pembimbing)
                .post(dosen_pembimbing::create_dosen_pembimbing)
                .push(
                    Router::with_path("{id}")
                        .get(dosen_pembimbing::get_dosen_pembimbing)
                        .put(dosen_pembimbing::update_dosen_pembimbing)
                        .delete(dosen_pembimbing::delete_dosen_pembimbing),
                ),
        )
        .push(
            Router::with_path("dosen-pengajar-kelas-kuliah")
                .get(dosen_pengajar_kelas_kuliah::list_dosen_pengajar_kelas_kuliah)
                .post(dosen_pengajar_kelas_kuliah::create_dosen_pengajar_kelas_kuliah)
                .push(
                    Router::with_path("{id}")
                        .get(dosen_pengajar_kelas_kuliah::get_dosen_pengajar_kelas_kuliah)
                        .put(dosen_pengajar_kelas_kuliah::update_dosen_pengajar_kelas_kuliah)
                        .delete(dosen_pengajar_kelas_kuliah::delete_dosen_pengajar_kelas_kuliah),
                ),
        )
        .push(
            Router::with_path("fakultas")
                .get(fakultas::list_fakultas)
                .post(fakultas::create_fakulta)
                .push(
                    Router::with_path("{id}")
                        .get(fakultas::get_fakulta)
                        .put(fakultas::update_fakulta)
                        .delete(fakultas::delete_fakulta),
                ),
        )
        .push(
            Router::with_path("hitung-transkrip-angkatan-mahasiswa")
                .get(hitung_transkrip_angkatan_mahasiswa::list_hitung_transkrip_angkatan_mahasiswa)
                .post(hitung_transkrip_angkatan_mahasiswa::create_hitung_transkrip_angkatan_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(hitung_transkrip_angkatan_mahasiswa::get_hitung_transkrip_angkatan_mahasiswa)
                        .put(hitung_transkrip_angkatan_mahasiswa::update_hitung_transkrip_angkatan_mahasiswa)
                        .delete(hitung_transkrip_angkatan_mahasiswa::delete_hitung_transkrip_angkatan_mahasiswa),
                ),
        )
        .push(
            Router::with_path("kartu-rencana-studi-mahasiswa")
                .get(kartu_rencana_studi_mahasiswa::list_kartu_rencana_studi_mahasiswa)
                .post(kartu_rencana_studi_mahasiswa::create_kartu_rencana_studi_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(kartu_rencana_studi_mahasiswa::get_kartu_rencana_studi_mahasiswa)
                        .put(kartu_rencana_studi_mahasiswa::update_kartu_rencana_studi_mahasiswa)
                        .delete(kartu_rencana_studi_mahasiswa::delete_kartu_rencana_studi_mahasiswa),
                ),
        )
        .push(
            Router::with_path("kelas-kuliah")
                .get(kelas_kuliah::list_kelas_kuliah)
                .post(kelas_kuliah::create_kelas_kuliah)
                .push(
                    Router::with_path("{id}")
                        .get(kelas_kuliah::get_kelas_kuliah)
                        .put(kelas_kuliah::update_kelas_kuliah)
                        .delete(kelas_kuliah::delete_kelas_kuliah),
                ),
        )
        .push(
            Router::with_path("komponen-evaluasi-kelas")
                .get(komponen_evaluasi_kelas::list_komponen_evaluasi_kelas)
                .post(komponen_evaluasi_kelas::create_komponen_evaluasi_kela)
                .push(
                    Router::with_path("{id}")
                        .get(komponen_evaluasi_kelas::get_komponen_evaluasi_kela)
                        .put(komponen_evaluasi_kelas::update_komponen_evaluasi_kela)
                        .delete(komponen_evaluasi_kelas::delete_komponen_evaluasi_kela),
                ),
        )
        .push(
            Router::with_path("konsistensi-data")
                .get(konsistensi_data::list_konsistensi_data)
                .post(konsistensi_data::create_konsistensi_data)
                .push(
                    Router::with_path("{id}")
                        .get(konsistensi_data::get_konsistensi_data)
                        .put(konsistensi_data::update_konsistensi_data)
                        .delete(konsistensi_data::delete_konsistensi_data),
                ),
        )
        .push(
            Router::with_path("konversi-kampus-merdeka")
                .get(konversi_kampus_merdeka::list_konversi_kampus_merdeka)
                .post(konversi_kampus_merdeka::create_konversi_kampus_merdeka)
                .push(
                    Router::with_path("{id}")
                        .get(konversi_kampus_merdeka::get_konversi_kampus_merdeka)
                        .put(konversi_kampus_merdeka::update_konversi_kampus_merdeka)
                        .delete(konversi_kampus_merdeka::delete_konversi_kampus_merdeka),
                ),
        )
        .push(
            Router::with_path("kurikulum")
                .get(kurikulum::list_kurikulum)
                .post(kurikulum::create_kurikulum)
                .push(
                    Router::with_path("{id}")
                        .get(kurikulum::get_kurikulum)
                        .put(kurikulum::update_kurikulum)
                        .delete(kurikulum::delete_kurikulum),
                ),
        )
        .push(
            Router::with_path("mahasiswa")
                .get(mahasiswa::list_mahasiswa)
                .post(mahasiswa::create_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(mahasiswa::get_mahasiswa)
                        .put(mahasiswa::update_mahasiswa)
                        .delete(mahasiswa::delete_mahasiswa),
                ),
        )
        .push(
            Router::with_path("mahasiswa-bimbingan-dosen")
                .get(mahasiswa_bimbingan_dosen::list_mahasiswa_bimbingan_dosen)
                .post(mahasiswa_bimbingan_dosen::create_mahasiswa_bimbingan_dosen)
                .push(
                    Router::with_path("{id}")
                        .get(mahasiswa_bimbingan_dosen::get_mahasiswa_bimbingan_dosen)
                        .put(mahasiswa_bimbingan_dosen::update_mahasiswa_bimbingan_dosen)
                        .delete(mahasiswa_bimbingan_dosen::delete_mahasiswa_bimbingan_dosen),
                ),
        )
        .push(
            Router::with_path("mahasiswa-lulusan-dropout")
                .get(mahasiswa_lulusan_dropout::list_mahasiswa_lulusan_dropout)
                .post(mahasiswa_lulusan_dropout::create_mahasiswa_lulusan_dropout)
                .push(
                    Router::with_path("{id}")
                        .get(mahasiswa_lulusan_dropout::get_mahasiswa_lulusan_dropout)
                        .put(mahasiswa_lulusan_dropout::update_mahasiswa_lulusan_dropout)
                        .delete(mahasiswa_lulusan_dropout::delete_mahasiswa_lulusan_dropout),
                ),
        )
        .push(
            Router::with_path("matakuliah")
                .get(matakuliah::list_matakuliah)
                .post(matakuliah::create_matakuliah)
                .push(
                    Router::with_path("{id}")
                        .get(matakuliah::get_matakuliah)
                        .put(matakuliah::update_matakuliah)
                        .delete(matakuliah::delete_matakuliah),
                ),
        )
        .push(
            Router::with_path("matakuliah-kurikulum")
                .get(matakuliah_kurikulum::list_matakuliah_kurikulum)
                .post(matakuliah_kurikulum::create_matakuliah_kurikulum)
                .push(
                    Router::with_path("{id}")
                        .get(matakuliah_kurikulum::get_matakuliah_kurikulum)
                        .put(matakuliah_kurikulum::update_matakuliah_kurikulum)
                        .delete(matakuliah_kurikulum::delete_matakuliah_kurikulum),
                ),
        )
        .push(
            Router::with_path("nilai-perkuliahan-kelas")
                .get(nilai_perkuliahan_kelas::list_nilai_perkuliahan_kelas)
                .post(nilai_perkuliahan_kelas::create_nilai_perkuliahan_kela)
                .push(
                    Router::with_path("{id}")
                        .get(nilai_perkuliahan_kelas::get_nilai_perkuliahan_kela)
                        .put(nilai_perkuliahan_kelas::update_nilai_perkuliahan_kela)
                        .delete(nilai_perkuliahan_kelas::delete_nilai_perkuliahan_kela),
                ),
        )
        .push(
            Router::with_path("nilai-transfer-pendidikan-mahasiswa")
                .get(nilai_transfer_pendidikan_mahasiswa::list_nilai_transfer_pendidikan_mahasiswa)
                .post(nilai_transfer_pendidikan_mahasiswa::create_nilai_transfer_pendidikan_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(nilai_transfer_pendidikan_mahasiswa::get_nilai_transfer_pendidikan_mahasiswa)
                        .put(nilai_transfer_pendidikan_mahasiswa::update_nilai_transfer_pendidikan_mahasiswa)
                        .delete(nilai_transfer_pendidikan_mahasiswa::delete_nilai_transfer_pendidikan_mahasiswa),
                ),
        )
        .push(
            Router::with_path("penugasan-dosen")
                .get(penugasan_dosen::list_penugasan_dosen)
                .post(penugasan_dosen::create_penugasan_dosen)
                .push(
                    Router::with_path("{id}")
                        .get(penugasan_dosen::get_penugasan_dosen)
                        .put(penugasan_dosen::update_penugasan_dosen)
                        .delete(penugasan_dosen::delete_penugasan_dosen),
                ),
        )
        .push(
            Router::with_path("perguruan-tinggi")
                .get(perguruan_tinggi::list_perguruan_tinggi)
                .post(perguruan_tinggi::create_perguruan_tinggi)
                .push(
                    Router::with_path("{id}")
                        .get(perguruan_tinggi::get_perguruan_tinggi)
                        .put(perguruan_tinggi::update_perguruan_tinggi)
                        .delete(perguruan_tinggi::delete_perguruan_tinggi),
                ),
        )
        .push(
            Router::with_path("periode-aktif")
                .get(periode_aktif::list_periode_aktif)
                .post(periode_aktif::create_periode_aktif)
                .push(
                    Router::with_path("{id}")
                        .get(periode_aktif::get_periode_aktif)
                        .put(periode_aktif::update_periode_aktif)
                        .delete(periode_aktif::delete_periode_aktif),
                ),
        )
        .push(
            Router::with_path("periode-perkuliahan")
                .get(periode_perkuliahan::list_periode_perkuliahan)
                .post(periode_perkuliahan::create_periode_perkuliahan)
                .push(
                    Router::with_path("{id}")
                        .get(periode_perkuliahan::get_periode_perkuliahan)
                        .put(periode_perkuliahan::update_periode_perkuliahan)
                        .delete(periode_perkuliahan::delete_periode_perkuliahan),
                ),
        )
        .push(
            Router::with_path("perkuliahan-mahasiswa")
                .get(perkuliahan_mahasiswa::list_perkuliahan_mahasiswa)
                .post(perkuliahan_mahasiswa::create_perkuliahan_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(perkuliahan_mahasiswa::get_perkuliahan_mahasiswa)
                        .put(perkuliahan_mahasiswa::update_perkuliahan_mahasiswa)
                        .delete(perkuliahan_mahasiswa::delete_perkuliahan_mahasiswa),
                ),
        )
        .push(
            Router::with_path("peserta-kelas-kuliah")
                .get(peserta_kelas_kuliah::list_peserta_kelas_kuliah)
                .post(peserta_kelas_kuliah::create_peserta_kelas_kuliah)
                .push(
                    Router::with_path("{id}")
                        .get(peserta_kelas_kuliah::get_peserta_kelas_kuliah)
                        .put(peserta_kelas_kuliah::update_peserta_kelas_kuliah)
                        .delete(peserta_kelas_kuliah::delete_peserta_kelas_kuliah),
                ),
        )
        .push(
            Router::with_path("prestasi-mahasiswa")
                .get(prestasi_mahasiswa::list_prestasi_mahasiswa)
                .post(prestasi_mahasiswa::create_prestasi_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(prestasi_mahasiswa::get_prestasi_mahasiswa)
                        .put(prestasi_mahasiswa::update_prestasi_mahasiswa)
                        .delete(prestasi_mahasiswa::delete_prestasi_mahasiswa),
                ),
        )
        .push(
            Router::with_path("profil-perguruan-tinggi")
                .get(profil_perguruan_tinggi::list_profil_perguruan_tinggi)
                .post(profil_perguruan_tinggi::create_profil_perguruan_tinggi)
                .push(
                    Router::with_path("{id}")
                        .get(profil_perguruan_tinggi::get_profil_perguruan_tinggi)
                        .put(profil_perguruan_tinggi::update_profil_perguruan_tinggi)
                        .delete(profil_perguruan_tinggi::delete_profil_perguruan_tinggi),
                ),
        )
        .push(
            Router::with_path("program-studi")
                .get(program_studi::list_program_studi)
                .post(program_studi::create_program_studi)
                .push(
                    Router::with_path("{id}")
                        .get(program_studi::get_program_studi)
                        .put(program_studi::update_program_studi)
                        .delete(program_studi::delete_program_studi),
                ),
        )
        .push(
            Router::with_path("rencana-evaluasi")
                .get(rencana_evaluasi::list_rencana_evaluasi)
                .post(rencana_evaluasi::create_rencana_evaluasi)
                .push(
                    Router::with_path("{id}")
                        .get(rencana_evaluasi::get_rencana_evaluasi)
                        .put(rencana_evaluasi::update_rencana_evaluasi)
                        .delete(rencana_evaluasi::delete_rencana_evaluasi),
                ),
        )
        .push(
            Router::with_path("rencana-pembelajaran")
                .get(rencana_pembelajaran::list_rencana_pembelajaran)
                .post(rencana_pembelajaran::create_rencana_pembelajaran)
                .push(
                    Router::with_path("{id}")
                        .get(rencana_pembelajaran::get_rencana_pembelajaran)
                        .put(rencana_pembelajaran::update_rencana_pembelajaran)
                        .delete(rencana_pembelajaran::delete_rencana_pembelajaran),
                ),
        )
        .push(
            Router::with_path("riwayat-fungsional-dosen")
                .get(riwayat_fungsional_dosen::list_riwayat_fungsional_dosen)
                .post(riwayat_fungsional_dosen::create_riwayat_fungsional_dosen)
                .push(
                    Router::with_path("{id}")
                        .get(riwayat_fungsional_dosen::get_riwayat_fungsional_dosen)
                        .put(riwayat_fungsional_dosen::update_riwayat_fungsional_dosen)
                        .delete(riwayat_fungsional_dosen::delete_riwayat_fungsional_dosen),
                ),
        )
        .push(
            Router::with_path("riwayat-nilai-mahasiswa")
                .get(riwayat_nilai_mahasiswa::list_riwayat_nilai_mahasiswa)
                .post(riwayat_nilai_mahasiswa::create_riwayat_nilai_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(riwayat_nilai_mahasiswa::get_riwayat_nilai_mahasiswa)
                        .put(riwayat_nilai_mahasiswa::update_riwayat_nilai_mahasiswa)
                        .delete(riwayat_nilai_mahasiswa::delete_riwayat_nilai_mahasiswa),
                ),
        )
        .push(
            Router::with_path("riwayat-pangkat-dosen")
                .get(riwayat_pangkat_dosen::list_riwayat_pangkat_dosen)
                .post(riwayat_pangkat_dosen::create_riwayat_pangkat_dosen)
                .push(
                    Router::with_path("{id}")
                        .get(riwayat_pangkat_dosen::get_riwayat_pangkat_dosen)
                        .put(riwayat_pangkat_dosen::update_riwayat_pangkat_dosen)
                        .delete(riwayat_pangkat_dosen::delete_riwayat_pangkat_dosen),
                ),
        )
        .push(
            Router::with_path("riwayat-pendidikan-dosen")
                .get(riwayat_pendidikan_dosen::list_riwayat_pendidikan_dosen)
                .post(riwayat_pendidikan_dosen::create_riwayat_pendidikan_dosen)
                .push(
                    Router::with_path("{id}")
                        .get(riwayat_pendidikan_dosen::get_riwayat_pendidikan_dosen)
                        .put(riwayat_pendidikan_dosen::update_riwayat_pendidikan_dosen)
                        .delete(riwayat_pendidikan_dosen::delete_riwayat_pendidikan_dosen),
                ),
        )
        .push(
            Router::with_path("riwayat-pendidikan-mahasiswa")
                .get(riwayat_pendidikan_mahasiswa::list_riwayat_pendidikan_mahasiswa)
                .post(riwayat_pendidikan_mahasiswa::create_riwayat_pendidikan_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(riwayat_pendidikan_mahasiswa::get_riwayat_pendidikan_mahasiswa)
                        .put(riwayat_pendidikan_mahasiswa::update_riwayat_pendidikan_mahasiswa)
                        .delete(riwayat_pendidikan_mahasiswa::delete_riwayat_pendidikan_mahasiswa),
                ),
        )
        .push(
            Router::with_path("riwayat-penelitian-dosen")
                .get(riwayat_penelitian_dosen::list_riwayat_penelitian_dosen)
                .post(riwayat_penelitian_dosen::create_riwayat_penelitian_dosen)
                .push(
                    Router::with_path("{id}")
                        .get(riwayat_penelitian_dosen::get_riwayat_penelitian_dosen)
                        .put(riwayat_penelitian_dosen::update_riwayat_penelitian_dosen)
                        .delete(riwayat_penelitian_dosen::delete_riwayat_penelitian_dosen),
                ),
        )
        .push(
            Router::with_path("riwayat-sertifikasi-dosen")
                .get(riwayat_sertifikasi_dosen::list_riwayat_sertifikasi_dosen)
                .post(riwayat_sertifikasi_dosen::create_riwayat_sertifikasi_dosen)
                .push(
                    Router::with_path("{id}")
                        .get(riwayat_sertifikasi_dosen::get_riwayat_sertifikasi_dosen)
                        .put(riwayat_sertifikasi_dosen::update_riwayat_sertifikasi_dosen)
                        .delete(riwayat_sertifikasi_dosen::delete_riwayat_sertifikasi_dosen),
                ),
        )
        .push(
            Router::with_path("skala-nilai-program-studi")
                .get(skala_nilai_program_studi::list_skala_nilai_program_studi)
                .post(skala_nilai_program_studi::create_skala_nilai_program_studi)
                .push(
                    Router::with_path("{id}")
                        .get(skala_nilai_program_studi::get_skala_nilai_program_studi)
                        .put(skala_nilai_program_studi::update_skala_nilai_program_studi)
                        .delete(skala_nilai_program_studi::delete_skala_nilai_program_studi),
                ),
        )
        .push(
            Router::with_path("substansi-matakuliah")
                .get(substansi_matakuliah::list_substansi_matakuliah)
                .post(substansi_matakuliah::create_substansi_matakuliah)
                .push(
                    Router::with_path("{id}")
                        .get(substansi_matakuliah::get_substansi_matakuliah)
                        .put(substansi_matakuliah::update_substansi_matakuliah)
                        .delete(substansi_matakuliah::delete_substansi_matakuliah),
                ),
        )
        .push(
            Router::with_path("transkrip-mahasiswa")
                .get(transkrip_mahasiswa::list_transkrip_mahasiswa)
                .post(transkrip_mahasiswa::create_transkrip_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(transkrip_mahasiswa::get_transkrip_mahasiswa)
                        .put(transkrip_mahasiswa::update_transkrip_mahasiswa)
                        .delete(transkrip_mahasiswa::delete_transkrip_mahasiswa),
                ),
        )
        .push(
            Router::with_path("uji-mahasiswa")
                .get(uji_mahasiswa::list_uji_mahasiswa)
                .post(uji_mahasiswa::create_uji_mahasiswa)
                .push(
                    Router::with_path("{id}")
                        .get(uji_mahasiswa::get_uji_mahasiswa)
                        .put(uji_mahasiswa::update_uji_mahasiswa)
                        .delete(uji_mahasiswa::delete_uji_mahasiswa),
                ),
        )
}
