// This file is auto-generated by vite.config.ts. Do not edit directly.
export const availableLogoCodes = [
  "091017",
  "091074",
  "092010"
] as const;

export const availableFaviconCodes = [
  "091017",
  "091074",
  "092010"
] as const;
