//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::electronic_mail_types::Entity as ContactReferenceElectronicMailTypes;
pub use super::phone_types::Entity as ContactReferencePhoneTypes;
pub use super::residence_types::Entity as ContactReferenceResidenceTypes;
pub use super::website_types::Entity as ContactReferenceWebsiteTypes;
