//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::electronic_mail_types::Entity as ElectronicMailTypes;
pub use super::phone_types::Entity as PhoneTypes;
pub use super::residence_types::Entity as ResidenceTypes;
pub use super::website_types::Entity as WebsiteTypes;
