//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_general_reference",
    table_name = "academic_years"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: i32,
    pub year: i32,
    pub name: String,
    pub feeder_name: String,
    pub academic_year_category_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub is_active: Option<bool>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    #[sea_orm(belongs_to, from = "academic_year_category_id", to = "id")]
    pub academic_year_category: BelongsTo<crate::models::academic::general::reference::academic_year_categories::Entity>,
    #[sea_orm(has_many)]
    pub institutions: HasMany<crate::models::institution::master::institutions::Entity>,
    #[sea_orm(has_many)]
    pub activities: HasMany<crate::models::academic::campaign::transaction::activities::Entity>,
    #[sea_orm(has_many)]
    pub calendars: HasMany<crate::models::academic::campaign::transaction::calendars::Entity>,
    #[sea_orm(has_many)]
    pub candidates: HasMany<crate::models::academic::candidate::master::candidates::Entity>,
    #[sea_orm(has_many)]
    pub curriculums: HasMany<crate::models::academic::course::master::curriculums::Entity>,
    #[sea_orm(has_many)]
    pub convertions: HasMany<crate::models::academic::student::campaign::convertions::Entity>,
    #[sea_orm(has_many)]
    pub students: HasMany<crate::models::academic::student::master::students::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
