//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_candidate_master", table_name = "candidates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub thread: Option<i32>,
    pub code: Option<String>,
    pub name: String,
    pub student_national_number: Option<String>,
    pub school_name: Option<String>,
    pub school_regency_id: Option<Uuid>,
    pub state_smart_card_number: Option<String>,
    pub individual_id: Option<Uuid>,
    pub academic_year_id: Option<Uuid>,
    pub student_id: Option<Uuid>,
    pub user_id: Uuid,
    pub registration_type_id: Uuid,
    pub institution_id: Uuid,
    pub guidence_name: Option<String>,
    pub guidence_phone_number: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
