//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_candidate_master", table_name = "candidates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub thread: Option<i32>,
    pub code: Option<String>,
    pub name: String,
    pub student_national_number: Option<String>,
    pub school_name: Option<String>,
    pub school_regency_id: Option<Uuid>,
    pub state_smart_card_number: Option<String>,
    pub individual_id: Option<Uuid>,
    pub academic_year_id: Option<Uuid>,
    pub student_id: Option<Uuid>,
    pub user_id: Uuid,
    pub registration_type_id: Uuid,
    pub institution_id: Uuid,
    pub guidence_name: Option<String>,
    pub guidence_phone_number: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "individual_id", to = "id")]
    pub individual: BelongsTo<Option<crate::models::person::master::individual::Entity>>,
    #[sea_orm(belongs_to, from = "academic_year_id", to = "id")]
    pub academic_year: BelongsTo<Option<crate::models::academic::general::reference::academic_years::Entity>>,
    #[sea_orm(belongs_to, from = "student_id", to = "id")]
    pub student: BelongsTo<Option<crate::models::academic::student::master::students::Entity>>,
    #[sea_orm(belongs_to, from = "user_id", to = "id")]
    pub user: BelongsTo<crate::models::auth::user::Entity>,
    #[sea_orm(belongs_to, from = "registration_type_id", to = "id")]
    pub registration_type: BelongsTo<crate::models::academic::candidate::reference::registration_types::Entity>,
    #[sea_orm(belongs_to, from = "institution_id", to = "id")]
    pub institution: BelongsTo<crate::models::institution::master::institutions::Entity>,
    #[sea_orm(has_many)]
    pub candidate_unit: HasMany<crate::models::academic::candidate::master::candidate_unit::Entity>,
    #[sea_orm(has_many)]
    pub candidate_unit_choices: HasMany<crate::models::academic::candidate::transaction::candidate_unit_choices::Entity>,
    #[sea_orm(has_many)]
    pub documents: HasMany<crate::models::academic::candidate::transaction::documents::Entity>,
    #[sea_orm(has_many)]
    pub exams: HasMany<crate::models::academic::candidate::transaction::exams::Entity>,
    #[sea_orm(has_many)]
    pub recognitions: HasMany<crate::models::academic::prior_learning_recognition::transaction::recognitions::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}

pub struct CandidateToRole;

impl Linked for CandidateToRole {
    type FromEntity = Entity;
    type ToEntity = crate::models::auth::role::Entity;

    fn link(&self) -> Vec<RelationDef> {
        let rel: RelationDef = crate::models::auth::role::Entity::belongs_to(Entity)
            .from(crate::models::auth::role::Column::RoleableId)
            .to(Column::Id)
            .on_condition(|_left, _right| {
                crate::models::auth::role::Column::RoleableType.eq("Candidate").into()
            })
            .into();
        vec![rel.rev()]
    }
}
