//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_candidate_master", table_name = "exam_classes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: Option<i32>,
    pub alphabet_code: Option<String>,
    pub name: String,
    pub phase_id: Option<Uuid>,
    pub start_date: DateTime,
    pub end_date: Option<DateTime>,
    pub start_time: Option<Time>,
    pub end_time: Option<Time>,
    pub capacity: i32,
    pub lms_category: Option<i32>,
    pub is_online: Option<bool>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "phase_id", to = "id")]
    pub phase: BelongsTo<Option<crate::models::academic::candidate::reference::phases::Entity>>,
    #[sea_orm(has_many)]
    pub exams: HasMany<crate::models::academic::candidate::transaction::exams::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
