//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::candidate_unit::Entity as CandidateUnit;
pub use super::candidates::Entity as Candidates;
pub use super::exam_classes::Entity as ExamClasses;
