//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::candidate_unit::Entity as AcademicCandidateMasterCandidateUnit;
pub use super::candidates::Entity as AcademicCandidateMasterCandidates;
pub use super::exam_classes::Entity as AcademicCandidateMasterExamClasses;
