export interface LocationSubDistrict {
    id: string;
    code: string|null,
    name: string|null,
    dikti_code: string|null,
    regency_id: string|null,
    slug: string|null,
    alt_slug: string|null,
    state_ministry_code: string|null,
    state_ministry_full_code: string|null,
    state_post_department_code: string|null,
    state_ministry_name: string|null,
    dikti_name: string|null,
    validation_code: string|null,
    agriculture_department_name: string|null,
    latitude: number|null,
    longitude: number|null,
    zoom: number|null,
    created_at: Date|null,
    updated_at: Date|null,
    deleted_at: Date|null,
    created_by: string|null,
    updated_by: string|null
}

export var initialLocationSubDistrict: LocationSubDistrict = {
    id: "",
    code: "",
    name: "",
    dikti_code: null,
    regency_id: "",
    slug: "",
    alt_slug: null,
    state_ministry_code: null,
    state_ministry_full_code: null,
    state_post_department_code: null,
    state_ministry_name: null,
    dikti_name: null,
    validation_code: null,
    agriculture_department_name: null,
    latitude: 0,
    longitude: 0,
    zoom: 0,
    created_at: null,
    updated_at: null,
    deleted_at: null,
    created_by: null,
    updated_by: null,
};