//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_candidate_transaction",
    table_name = "candidate_unit_choices"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub candidate_id: Uuid,
    pub unit_id: Option<Uuid>,
    pub student_registration_id: Option<Uuid>,
    pub registration_category_id: Option<Uuid>,
    pub phase_id: Option<Uuid>,
    pub priority: i32,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "candidate_id", to = "id")]
    pub candidate: BelongsTo<crate::models::academic::candidate::master::candidates::Entity>,
    #[sea_orm(belongs_to, from = "unit_id", to = "id")]
    pub unit: BelongsTo<Option<crate::models::institution::master::units::Entity>>,
    #[sea_orm(belongs_to, from = "registration_category_id", to = "id")]
    pub registration_category: BelongsTo<Option<crate::models::academic::candidate::reference::registration_categories::Entity>>,
    #[sea_orm(belongs_to, from = "phase_id", to = "id")]
    pub phase: BelongsTo<Option<crate::models::academic::candidate::reference::phases::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
