//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_candidate_transaction",
    table_name = "documents"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub candidate_id: Uuid,
    pub document_type_id: Uuid,
    pub filename: Option<String>,
    pub dir: Option<String>,
    pub r#type: Option<String>,
    pub size: Option<i32>,
    pub is_verified: Option<bool>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "candidate_id", to = "id")]
    pub candidate: BelongsTo<crate::models::academic::candidate::master::candidates::Entity>,
    #[sea_orm(belongs_to, from = "document_type_id", to = "id")]
    pub document_type: BelongsTo<crate::models::academic::candidate::reference::document_types::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
