//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_candidate_transaction", table_name = "exams")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub candidate_id: Uuid,
    pub exam_class_id: Uuid,
    #[sea_orm(column_type = "Double")]
    pub score: f64,
    pub is_present: Option<bool>,
    pub is_pass: bool,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "candidate_id", to = "id")]
    pub candidate: BelongsTo<crate::models::academic::candidate::master::candidates::Entity>,
    #[sea_orm(belongs_to, from = "exam_class_id", to = "id")]
    pub exam_class: BelongsTo<crate::models::academic::candidate::master::exam_classes::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
