//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::candidate_unit_choices::Entity as CandidateUnitChoices;
pub use super::documents::Entity as Documents;
pub use super::exams::Entity as Exams;
