//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::candidate_unit_choices::Entity as AcademicCandidateTransactionCandidateUnitChoices;
pub use super::documents::Entity as AcademicCandidateTransactionDocuments;
pub use super::exams::Entity as AcademicCandidateTransactionExams;
