//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::contracts::Entity as Contracts;
pub use super::groups::Entity as Groups;
pub use super::ranks::Entity as Ranks;
pub use super::statuses::Entity as Statuses;
