//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::contracts::Entity as AcademicLecturerReferenceContracts;
pub use super::groups::Entity as AcademicLecturerReferenceGroups;
pub use super::ranks::Entity as AcademicLecturerReferenceRanks;
pub use super::statuses::Entity as AcademicLecturerReferenceStatuses;
