//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_lecturer_reference", table_name = "statuses")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: i32,
    pub alphabet_code: Option<String>,
    pub name: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(has_many)]
    pub lecturers: HasMany<crate::models::academic::lecturer::master::lecturers::Entity>,
    #[sea_orm(has_many)]
    pub homebases: HasMany<crate::models::academic::lecturer::transaction::homebases::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
