//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod competences;
pub mod course_evaluation_bases;
pub mod curriculum_types;
pub mod encounter_types;
pub mod evaluation_types;
pub mod groups;
pub mod semesters;
pub mod varieties;
