//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::competences::Entity as AcademicCourseReferenceCompetences;
pub use super::course_evaluation_bases::Entity as AcademicCourseReferenceCourseEvaluationBases;
pub use super::curriculum_types::Entity as AcademicCourseReferenceCurriculumTypes;
pub use super::encounter_types::Entity as AcademicCourseReferenceEncounterTypes;
pub use super::evaluation_types::Entity as AcademicCourseReferenceEvaluationTypes;
pub use super::groups::Entity as AcademicCourseReferenceGroups;
pub use super::semesters::Entity as AcademicCourseReferenceSemesters;
pub use super::varieties::Entity as AcademicCourseReferenceVarieties;
