//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::competences::Entity as Competences;
pub use super::course_evaluation_bases::Entity as CourseEvaluationBases;
pub use super::curriculum_types::Entity as CurriculumTypes;
pub use super::encounter_types::Entity as EncounterTypes;
pub use super::evaluation_types::Entity as EvaluationTypes;
pub use super::groups::Entity as Groups;
pub use super::semesters::Entity as Semesters;
pub use super::varieties::Entity as Varieties;
