//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_course_master",
    table_name = "course_learn_plannings"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: i32,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub decription_indonesian: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub decription_english: Option<String>,
    pub course_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub feeder_id_rencana_ajar: Option<Uuid>,
    #[sea_orm(belongs_to, from = "course_id", to = "id")]
    pub course: BelongsTo<crate::models::academic::course::master::courses::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
