//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_course_master", table_name = "courses")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub implementation_method: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub total_credit: f64,
    #[sea_orm(column_type = "Double")]
    pub lecture_credit: f64,
    #[sea_orm(column_type = "Double")]
    pub practice_credit: f64,
    #[sea_orm(column_type = "Double")]
    pub field_practice_credit: f64,
    #[sea_orm(column_type = "Double")]
    pub simulation_credit: f64,
    pub has_unit: bool,
    pub has_syllabus: bool,
    pub has_material: bool,
    pub has_practice: bool,
    pub has_dictation: bool,
    pub group_id: Option<Uuid>,
    pub variety_id: Uuid,
    pub unit_id: Uuid,
    pub competence_id: Option<Uuid>,
    pub feeder_course_group_id: Option<Uuid>,
    pub feeder_course_type_id: Option<Uuid>,
    pub feeder_course_id: Option<Uuid>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
