//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_course_master", table_name = "curriculums")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub unit_id: Uuid,
    pub academic_year_id: Uuid,
    pub curriculum_type_id: Uuid,
    #[sea_orm(column_type = "Double", nullable)]
    pub total_credit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub mandatory_course_credit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub optional_course_credit: Option<f64>,
    pub feeder_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub is_active: bool,
    #[sea_orm(belongs_to, from = "unit_id", to = "id")]
    pub unit: BelongsTo<crate::models::institution::master::units::Entity>,
    #[sea_orm(belongs_to, from = "academic_year_id", to = "id")]
    pub academic_year: BelongsTo<crate::models::academic::general::reference::academic_years::Entity>,
    #[sea_orm(belongs_to, from = "curriculum_type_id", to = "id")]
    pub curriculum_type: BelongsTo<crate::models::academic::course::reference::curriculum_types::Entity>,
    #[sea_orm(has_many)]
    pub curriculum_details: HasMany<crate::models::academic::course::master::curriculum_details::Entity>,
    #[sea_orm(has_many)]
    pub recognitions: HasMany<crate::models::academic::prior_learning_recognition::transaction::recognitions::Entity>,
    #[sea_orm(has_many)]
    pub students: HasMany<crate::models::academic::student::master::students::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
