//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_course_master",
    table_name = "curriculum_details"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: Option<i32>,
    pub curriculum_id: Uuid,
    pub semester_id: Uuid,
    pub course_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(column_type = "Double", nullable)]
    pub credit: Option<f64>,
    pub name: Option<String>,
    pub concentration_id: Option<Uuid>,
    pub is_convertable_to_mbkm: Option<bool>,
    pub feeder_id: Option<Uuid>,
    pub is_convertable_to_prior_learning_recognition: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
