//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod concentrations;
pub mod course_evaluation_plannings;
pub mod course_learn_plannings;
pub mod courses;
pub mod curriculum_details;
pub mod curriculums;
