//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::concentrations::Entity as Concentrations;
pub use super::course_evaluation_plannings::Entity as CourseEvaluationPlannings;
pub use super::course_learn_plannings::Entity as CourseLearnPlannings;
pub use super::courses::Entity as Courses;
pub use super::curriculum_details::Entity as CurriculumDetails;
pub use super::curriculums::Entity as Curriculums;
