//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::concentrations::Entity as AcademicCourseMasterConcentrations;
pub use super::course_evaluation_plannings::Entity as AcademicCourseMasterCourseEvaluationPlannings;
pub use super::course_learn_plannings::Entity as AcademicCourseMasterCourseLearnPlannings;
pub use super::courses::Entity as AcademicCourseMasterCourses;
pub use super::curriculum_details::Entity as AcademicCourseMasterCurriculumDetails;
pub use super::curriculums::Entity as AcademicCourseMasterCurriculums;
