//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::evaluator_types::Entity as AcademicPriorLearningRecognitionReferenceEvaluatorTypes;
pub use super::evidence_categories::Entity as AcademicPriorLearningRecognitionReferenceEvidenceCategories;
pub use super::evidence_types::Entity as AcademicPriorLearningRecognitionReferenceEvidenceTypes;
pub use super::professionalisms::Entity as AcademicPriorLearningRecognitionReferenceProfessionalisms;
