//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::evaluator_types::Entity as EvaluatorTypes;
pub use super::evidence_categories::Entity as EvidenceCategories;
pub use super::evidence_types::Entity as EvidenceTypes;
pub use super::professionalisms::Entity as Professionalisms;
