//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "building_master", table_name = "buildings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub alphabet_code: Option<String>,
    pub name: String,
    #[sea_orm(column_type = "Float", nullable)]
    pub long: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub wide: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub high: Option<f32>,
    pub variety_id: Uuid,
    pub category_id: Uuid,
    pub total_floor: Option<i32>,
    pub residence_id: Uuid,
    pub condition_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "variety_id", to = "id")]
    pub variety: BelongsTo<crate::models::building::reference::varieties::Entity>,
    #[sea_orm(belongs_to, from = "category_id", to = "id")]
    pub category: BelongsTo<crate::models::building::reference::categories::Entity>,
    #[sea_orm(belongs_to, from = "condition_id", to = "id")]
    pub condition: BelongsTo<crate::models::building::reference::conditions::Entity>,
    #[sea_orm(belongs_to, from = "residence_id", to = "id")]
    pub residence: BelongsTo<crate::models::contact::master::residences::Entity>,
    #[sea_orm(has_many)]
    pub rooms: HasMany<crate::models::building::master::rooms::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
