//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "building_master", table_name = "rooms")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub alphabet_code: Option<String>,
    pub name: String,
    #[sea_orm(column_type = "Float", nullable)]
    pub long: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub wide: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub high: Option<f32>,
    pub room_type_id: Uuid,
    pub unit_id: Option<Uuid>,
    pub building_id: Uuid,
    pub condition_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
