//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "location", table_name = "countries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: String,
    pub name: String,
    pub alpha2_code: String,
    pub alpha3_code: String,
    pub iso3166_2_code: String,
    pub dikti_code: Option<String>,
    pub continent_id: Option<Uuid>,
    pub region_id: Option<Uuid>,
    pub slug: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "continent_id", to = "id")]
    pub continent: BelongsTo<crate::models::location::continents::Entity>,
    #[sea_orm(belongs_to, from = "region_id", to = "id")]
    pub region: BelongsTo<crate::models::location::regions::Entity>,
    #[sea_orm(has_many)]
    pub provinces: HasMany<crate::models::location::provinces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
