//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::continents::Entity as LocationContinents;
pub use super::countries::Entity as LocationCountries;
pub use super::provinces::Entity as LocationProvinces;
pub use super::regencies::Entity as LocationRegencies;
pub use super::regency_types::Entity as LocationRegencyTypes;
pub use super::regions::Entity as LocationRegions;
pub use super::sub_districts::Entity as LocationSubDistricts;
pub use super::villages::Entity as LocationVillages;
