//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::continents::Entity as Continents;
pub use super::countries::Entity as Countries;
pub use super::provinces::Entity as Provinces;
pub use super::regencies::Entity as Regencies;
pub use super::regency_types::Entity as RegencyTypes;
pub use super::regions::Entity as Regions;
pub use super::sub_districts::Entity as SubDistricts;
pub use super::villages::Entity as Villages;
