//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_student_adviser", table_name = "counsellors")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub decree_id: Uuid,
    pub student_id: Uuid,
    pub lecturer_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "decree_id", to = "id")]
    pub decree: BelongsTo<crate::models::academic::student::adviser::decrees::Entity>,
    #[sea_orm(belongs_to, from = "student_id", to = "id")]
    pub student: BelongsTo<crate::models::academic::student::master::students::Entity>,
    #[sea_orm(belongs_to, from = "lecturer_id", to = "id")]
    pub lecturer: BelongsTo<crate::models::academic::lecturer::master::lecturers::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
