//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

pub type NullableUuid = Option<Uuid>;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "aktifitas_mahasiswa")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub asal_data: Option<String>,
    pub nm_asaldata: Option<String>,
    pub id_aktivitas: NullableUuid,
    pub jenis_anggota: Option<String>,
    pub nama_jenis_anggota: Option<String>,
    pub id_jenis_aktivitas: NullableUuid,
    pub nama_jenis_aktivitas: Option<String>,
    pub id_prodi: NullableUuid,
    pub nama_prodi: Option<String>,
    pub id_semester: NullableUuid,
    pub nama_semester: Option<String>,
    pub judul: Option<String>,
    pub keterangan: Option<String>,
    pub lokasi: Option<String>,
    pub sk_tugas: Option<String>,
    pub tanggal_sk_tugas: Option<Date>,
    pub untuk_kampus_merdeka: Option<i32>,
    pub tanggal_mulai: Option<Date>,
    pub tanggal_selesai: Option<Date>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_semester", to = "id")]
    pub semester: BelongsTo<crate::models::feeder::referensi::semester::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
