//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

pub type NullableUuid = Option<Uuid>;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(
    schema_name = "feeder_master",
    table_name = "bidang_minat_perguruan_tinggi"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_bidang_minat: NullableUuid,
    pub nm_bidang_minat: Option<String>,
    pub id_prodi: NullableUuid,
    pub nama_program_studi: Option<String>,
    pub smt_dimulai: Option<i32>,
    pub sk_bidang_minat: Option<i32>,
    pub tamat_sk_bidang_minat: Option<i32>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
