//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "bimbing_mahasiswa")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_aktivitas: NullableUuid,
    pub judul: Option<String>,
    pub id_bimbing_mahasiswa: NullableUuid,
    pub id_kategori_kegiatan: NullableUuid,
    pub nama_kategori_kegiatan: Option<String>,
    pub id_dosen: NullableUuid,
    pub nidn: Option<String>,
    pub nama_dosen: Option<String>,
    pub pembimbing_ke: Option<i32>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_kategori_kegiatan", to = "id")]
    pub kategori_kegiatan: BelongsTo<crate::models::feeder::referensi::kategori_kegiatan::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_dosen", to = "id")]
    pub dosen: BelongsTo<crate::models::feeder::master::dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub mahasiswa_bimbingan_dosens: HasMany<crate::models::feeder::master::mahasiswa_bimbingan_dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_kategori_kegiatan", to = "id")]
    pub kategori_kegiatan_rel: BelongsTo<Option<crate::models::feeder::referensi::kategori_kegiatan::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_dosen", to = "id")]
    pub dosen_rel: BelongsTo<Option<crate::models::feeder::master::dosen::Entity>>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub mahasiswa_bimbingan_dosens_rel: HasMany<crate::models::feeder::master::mahasiswa_bimbingan_dosen::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
