//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
pub type NullableI32 = Option<i32>;
pub type NullableString = Option<String>;

pub type NullableUuid = Option<Uuid>;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "biodata_mahasiswa")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub nama_mahasiswa: Option<String>,
    pub jenis_kelamin: Option<String>,
    pub tempat_lahir: Option<String>,
    pub tanggal_lahir: Option<Date>,
    pub id_mahasiswa: NullableUuid,
    pub id_agama: NullableI32,
    pub nama_agama: Option<String>,
    pub nik: Option<String>,
    pub nisn: Option<String>,
    pub npwp: Option<String>,
    pub id_negara: NullableString,
    pub kewarganegaraan: Option<String>,
    pub jalan: Option<String>,
    pub dusun: Option<String>,
    pub rt: Option<i32>,
    pub rw: Option<i32>,
    pub kelurahan: Option<String>,
    pub kode_pos: Option<String>,
    pub id_wilayah: NullableString,
    pub nama_wilayah: Option<String>,
    pub id_jenis_tinggal: NullableString,
    pub nama_jenis_tinggal: Option<String>,
    pub id_alat_transportasi: NullableString,
    pub nama_alat_transportasi: Option<String>,
    pub telepon: Option<String>,
    pub handphone: Option<String>,
    pub email: Option<String>,
    pub penerima_kps: Option<bool>,
    pub nomor_kps: Option<String>,
    pub nik_ayah: Option<String>,
    pub nama_ayah: Option<String>,
    pub tanggal_lahir_ayah: Option<Date>,
    pub id_pendidikan_ayah: NullableI32,
    pub nama_pendidikan_ayah: Option<String>,
    pub id_pekerjaan_ayah: NullableI32,
    pub nama_pekerjaan_ayah: Option<String>,
    pub id_penghasilan_ayah: NullableI32,
    pub nama_penghasilan_ayah: Option<String>,
    pub nik_ibu: Option<String>,
    pub nama_ibu_kandung: Option<String>,
    pub tanggal_lahir_ibu: Option<Date>,
    pub id_pendidikan_ibu: NullableI32,
    pub nama_pendidikan_ibu: Option<String>,
    pub id_pekerjaan_ibu: NullableI32,
    pub nama_pekerjaan_ibu: Option<String>,
    pub id_penghasilan_ibu: NullableI32,
    pub nama_penghasilan_ibu: Option<String>,
    pub nama_wali: Option<String>,
    pub tanggal_lahir_wali: Option<Date>,
    pub id_pendidikan_wali: NullableI32,
    pub nama_pendidikan_wali: Option<String>,
    pub id_pekerjaan_wali: NullableI32,
    pub nama_pekerjaan_wali: Option<String>,
    pub id_penghasilan_wali: NullableI32,
    pub nama_penghasilan_wali: Option<String>,
    pub id_kebutuhan_khusus_mahasiswa: NullableI32,
    pub nama_kebutuhan_khusus_mahasiswa: Option<String>,
    pub id_kebutuhan_khusus_ayah: NullableI32,
    pub nama_kebutuhan_khusus_ayah: Option<String>,
    pub id_kebutuhan_khusus_ibu: NullableI32,
    pub nama_kebutuhan_khusus_ibu: Option<String>,
    pub status_sync: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_mahasiswa", to = "id")]
    pub mahasiswa: BelongsTo<crate::models::feeder::master::mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_agama", to = "id")]
    pub agama: BelongsTo<crate::models::feeder::referensi::agama::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_negara", to = "id")]
    pub negara: BelongsTo<crate::models::feeder::referensi::negara::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_wilayah", to = "id")]
    pub wilayah: BelongsTo<crate::models::feeder::referensi::wilayah::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_jenis_tinggal", to = "id")]
    pub jenis_tinggal: BelongsTo<crate::models::feeder::referensi::jenis_tinggal::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_alat_transportasi", to = "id")]
    pub alat_transportasi: BelongsTo<crate::models::feeder::referensi::alat_transportasi::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
