//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(
    schema_name = "feeder_master",
    table_name = "detail_nilai_perkuliahan_kelas"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub id_prodi: NullableUuid,
    pub nama_program_studi: Option<String>,
    pub id_semester: NullableString,
    pub nama_semester: Option<String>,
    pub id_matkul: NullableUuid,
    pub kode_mata_kuliah: Option<String>,
    pub nama_mata_kuliah: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_mata_kuliah: Option<f32>,
    pub id_kelas_kuliah: NullableUuid,
    pub nama_kelas_kuliah: Option<String>,
    pub id_registrasi_mahasiswa: NullableUuid,
    pub id_mahasiswa: NullableUuid,
    pub nim: Option<String>,
    pub nama_mahasiswa: Option<String>,
    pub jurusan: Option<String>,
    pub angkatan: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub nilai_angka: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub nilai_indeks: Option<f32>,
    pub nilai_huruf: Option<String>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_semester", to = "id")]
    pub semester: BelongsTo<crate::models::feeder::referensi::semester::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_kelas_kuliah", to = "id")]
    pub kelas_kuliah: BelongsTo<crate::models::feeder::master::kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_mahasiswa", to = "id")]
    pub mahasiswa: BelongsTo<crate::models::feeder::master::mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi_rel: BelongsTo<Option<crate::models::feeder::master::program_studi::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_semester", to = "id")]
    pub semester_rel: BelongsTo<Option<crate::models::feeder::referensi::semester::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_kelas_kuliah", to = "id")]
    pub kelas_kuliah_rel: BelongsTo<Option<crate::models::feeder::master::kelas_kuliah::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_mahasiswa", to = "id")]
    pub mahasiswa_rel: BelongsTo<Option<crate::models::feeder::master::mahasiswa::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
