//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(
    schema_name = "feeder_master",
    table_name = "dosen_pengajar_kelas_kuliah"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_aktivitas_mengajar: Option<Uuid>,
    pub id_registrasi_dosen: Option<Uuid>,
    pub id_dosen: Option<Uuid>,
    pub nidn: Option<String>,
    pub nuptk: Option<String>,
    pub nama_dosen: Option<String>,
    pub id_kelas_kuliah: Option<Uuid>,
    pub nama_kelas_kuliah: Option<String>,
    pub id_substansi: Option<Uuid>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_substansi_total: Option<f32>,
    pub rencana_minggu_pertemuan: Option<i32>,
    pub realisasi_minggu_pertemuan: Option<i32>,
    pub id_jenis_evaluasi: Option<String>,
    pub nama_jenis_evaluasi: Option<String>,
    pub id_prodi: Option<Uuid>,
    pub id_semester: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_dosen", to = "id")]
    pub dosen: BelongsTo<crate::models::feeder::master::dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_kelas_kuliah", to = "id")]
    pub kelas_kuliah: BelongsTo<crate::models::feeder::master::kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_jenis_evaluasi", to = "id")]
    pub jenis_evaluasi: BelongsTo<crate::models::feeder::referensi::jenis_evaluasi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_semester", to = "id")]
    pub semester: BelongsTo<crate::models::feeder::referensi::semester::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_dosen", to = "id")]
    pub dosen_rel: BelongsTo<Option<crate::models::feeder::master::dosen::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_kelas_kuliah", to = "id")]
    pub kelas_kuliah_rel: BelongsTo<Option<crate::models::feeder::master::kelas_kuliah::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_jenis_evaluasi", to = "id")]
    pub jenis_evaluasi_rel: BelongsTo<Option<crate::models::feeder::referensi::jenis_evaluasi::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi_rel: BelongsTo<Option<crate::models::feeder::master::program_studi::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_semester", to = "id")]
    pub semester_rel: BelongsTo<Option<crate::models::feeder::referensi::semester::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
