//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "kelas_kuliah")]
pub struct Model {
    pub id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id_kelas_kuliah: Uuid,
    pub id_prodi: NullableUuid,
    pub nama_program_studi: Option<String>,
    pub id_semester: NullableString,
    pub nama_semester: Option<String>,
    pub id_matkul: NullableUuid,
    pub kode_mata_kuliah: Option<String>,
    pub nama_mata_kuliah: Option<String>,
    pub nama_kelas_kuliah: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_mk: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_tm: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_prak: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_prak_lap: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_sim: Option<f32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bahasan: Option<String>,
    pub tanggal_mulai_efektif: Option<Date>,
    pub tanggal_akhir_efektif: Option<Date>,
    pub kapasitas: Option<i32>,
    pub tanggal_tutup_daftar: Option<Date>,
    pub prodi_penyelenggara: Option<String>,
    pub perguruan_tinggi_penyelenggara: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks: Option<f32>,
    pub id_dosen: NullableString,
    #[sea_orm(column_type = "Text", nullable)]
    pub nama_dosen: Option<String>,
    pub jumlah_mahasiswa: Option<i32>,
    pub apa_untuk_pditt: Option<bool>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub detail_nilai_perkuliahan_kelass: HasMany<crate::models::feeder::master::detail_nilai_perkuliahan_kelas::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub dosen_pengajar_kelas_kuliahs: HasMany<crate::models::feeder::master::dosen_pengajar_kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_semester", to = "id")]
    pub semester: BelongsTo<crate::models::feeder::referensi::semester::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_dosen", to = "id")]
    pub dosen: BelongsTo<crate::models::feeder::master::dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub komponen_evaluasi_kelass: HasMany<crate::models::feeder::master::komponen_evaluasi_kelas::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub nilai_perkuliahan_kelass: HasMany<crate::models::feeder::master::nilai_perkuliahan_kelas::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub peserta_kelas_kuliahs: HasMany<crate::models::feeder::master::peserta_kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub transkrip_mahasiswas: HasMany<crate::models::feeder::master::transkrip_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub detail_nilai_perkuliahan_kelass_rel: HasMany<crate::models::feeder::master::detail_nilai_perkuliahan_kelas::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub dosen_pengajar_kelas_kuliahs_rel: HasMany<crate::models::feeder::master::dosen_pengajar_kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi_rel: BelongsTo<Option<crate::models::feeder::master::program_studi::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_semester", to = "id")]
    pub semester_rel: BelongsTo<Option<crate::models::feeder::referensi::semester::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_dosen", to = "id")]
    pub dosen_rel: BelongsTo<Option<crate::models::feeder::master::dosen::Entity>>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub komponen_evaluasi_kelass_rel: HasMany<crate::models::feeder::master::komponen_evaluasi_kelas::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub nilai_perkuliahan_kelass_rel: HasMany<crate::models::feeder::master::nilai_perkuliahan_kelas::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub peserta_kelas_kuliahs_rel: HasMany<crate::models::feeder::master::peserta_kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub transkrip_mahasiswas_rel: HasMany<crate::models::feeder::master::transkrip_mahasiswa::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
