//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "komponen_evaluasi_kelas")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_komponen_evaluasi: Option<Uuid>,
    pub id_kelas_kuliah: Option<Uuid>,
    pub id_jenis_evaluasi: Option<i32>,
    pub nama: Option<String>,
    pub nama_inggris: Option<String>,
    pub nomor_urut: Option<i32>,
    pub bobot_evaluasi: Option<String>,
    pub last_update: Option<Date>,
    pub tgl_create: Option<Date>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}


impl ActiveModelBehavior for ActiveModel {}
