//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "konversi_kampus_merdeka")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_semester: NullableUuid,
    pub nama_semester: Option<String>,
    pub id_konversi_aktivitas: NullableUuid,
    pub id_matkul: NullableUuid,
    pub nama_mata_kuliah: Option<String>,
    pub id_aktivitas: NullableUuid,
    pub judul: Option<String>,
    pub id_anggota: NullableUuid,
    pub nama_mahasiswa: Option<String>,
    pub nim: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_mata_kuliah: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub nilai_angka: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub nilai_indeks: Option<f32>,
    pub nilai_huruf: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_semester", to = "id")]
    pub semester: BelongsTo<crate::models::feeder::referensi::semester::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_semester", to = "id")]
    pub semester_rel: BelongsTo<Option<crate::models::feeder::referensi::semester::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
