//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
pub type NullableI32 = Option<i32>;
pub type NullableString = Option<String>;

pub type NullableUuid = Option<Uuid>;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "kurikulum")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub id_kurikulum: NullableUuid,
    pub nama_kurikulum: Option<String>,
    pub id_prodi: NullableUuid,
    pub nama_program_studi: Option<String>,
    pub id_jenj_didik: NullableI32,
    pub jml_sem_normal: Option<i32>,
    pub id_semester: NullableString,
    pub semester_mulai_berlaku: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub jumlah_sks_lulus: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub jumlah_sks_wajib: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub jumlah_sks_pilihan: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub jumlah_sks_mata_kuliah_wajib: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub jumlah_sks_mata_kuliah_pilihan: Option<f32>,
    pub status_sync: Option<String>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_semester", to = "id")]
    pub semester: BelongsTo<crate::models::feeder::referensi::semester::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub matakuliah_kurikulums: HasMany<crate::models::feeder::master::matakuliah_kurikulum::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
