//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
pub type NullableI32 = Option<i32>;
pub type NullableString = Option<String>;

pub type NullableUuid = Option<Uuid>;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "mahasiswa")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub nama_mahasiswa: Option<String>,
    pub jenis_kelamin: Option<String>,
    pub tanggal_lahir: Option<Date>,
    pub id_perguruan_tinggi: NullableUuid,
    pub nipd: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub ipk: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub total_sks: Option<f32>,
    pub id_sms: NullableUuid,
    pub id_mahasiswa: NullableUuid,
    pub id_agama: NullableI32,
    pub nama_agama: Option<String>,
    pub nama_program_studi: Option<String>,
    pub id_status_mahasiswa: NullableI32,
    pub nama_status_mahasiswa: Option<String>,
    pub nim: Option<String>,
    pub id_periode: NullableString,
    pub nama_periode_masuk: Option<String>,
    pub id_registrasi_mahasiswa: NullableUuid,
    pub id_periode_keluar: NullableString,
    pub tanggal_keluar: Option<Date>,
    pub last_update: Option<Date>,
    pub tgl_create: Option<Date>,
    pub status_sync: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub id_prodi: NullableUuid,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub aktifitas_kuliah_mahasiswas: HasMany<crate::models::feeder::master::aktifitas_kuliah_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub biodata_mahasiswas: HasMany<crate::models::feeder::master::biodata_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub detail_nilai_perkuliahan_kelass: HasMany<crate::models::feeder::master::detail_nilai_perkuliahan_kelas::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_perguruan_tinggi", to = "id")]
    pub perguruan_tinggi: BelongsTo<crate::models::feeder::master::perguruan_tinggi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_agama", to = "id")]
    pub agama: BelongsTo<crate::models::feeder::referensi::agama::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_status_mahasiswa", to = "id")]
    pub status_mahasiswa: BelongsTo<crate::models::feeder::referensi::status_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub mahasiswa_lulusan_dropouts: HasMany<crate::models::feeder::master::mahasiswa_lulusan_dropout::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub peserta_kelas_kuliahs: HasMany<crate::models::feeder::master::peserta_kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub prestasi_mahasiswas: HasMany<crate::models::feeder::master::prestasi_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub riwayat_pendidikan_mahasiswas: HasMany<crate::models::feeder::master::riwayat_pendidikan_mahasiswa::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
