//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "feeder_master",
    table_name = "mahasiswa_lulusan_dropout"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub id_registrasi_mahasiswa: Option<Uuid>,
    pub id_mahasiswa: Option<Uuid>,
    pub id_perguruan_tinggi: Option<Uuid>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub nim: Option<String>,
    pub nama_mahasiswa: Option<String>,
    pub angkatan: Option<String>,
    pub tgl_masuk_sp: Option<Date>,
    pub tgl_create: Option<Date>,
    pub tgl_keluar: Option<Date>,
    pub tanggal_keluar: Option<Date>,
    pub id_jenis_keluar: String,
    pub nama_jenis_keluar: String,
    pub id_periode_keluar: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub keterangan: Option<String>,
    pub nomor_sk_yudisium: Option<String>,
    pub tanggal_sk_yudisium: Option<Date>,
    #[sea_orm(column_type = "Float", nullable)]
    pub ipk: Option<f32>,
    pub nomor_ijazah: Option<String>,
    pub asal_ijazah: String,
    pub no_sertifikat_profesi: Option<String>,
    pub tanggal_terbit_ijazah: Option<Date>,
    pub jalur_skripsi: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub judul_skripsi: Option<String>,
    pub bulan_awal_bimbingan: Option<String>,
    pub bulan_akhir_bimbingan: Option<String>,
    pub id_dosen: Option<Uuid>,
    pub nidn: Option<String>,
    pub nuptk: Option<String>,
    pub nama_dosen: Option<String>,
    pub pembimbing_ke: Option<i32>,
    pub skhun: Option<String>,
    pub no_peserta_ujian: Option<String>,
    pub sks_diakui: Option<String>,
    pub id_jns_daftar: Option<String>,
    pub nm_jns_daftar: Option<String>,
    pub id_jalur_masuk: Option<String>,
    pub id_pembiayaan: Option<String>,
    pub biaya_masuk_kuliah: Option<String>,
    pub id_minat_bidang: Option<String>,
    pub bidang_mayor: Option<String>,
    pub bidang_minor: Option<String>,
    pub a_pindah_mhs_asing: Option<String>,
    pub id_pt_asal: Option<Uuid>,
    pub id_prodi_asal: Option<Uuid>,
    pub nm_pt_asal: Option<String>,
    pub nm_prodi_asal: Option<String>,
    pub namapt: Option<String>,
    pub id_jur: Option<String>,
    pub nm_smt: Option<String>,
    pub status_sync: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
