//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "matakuliah_kurikulum")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tgl_create: Option<Date>,
    pub id_kurikulum: Option<Uuid>,
    pub nama_kurikulum: Option<String>,
    pub id_matkul: Option<Uuid>,
    pub kode_mata_kuliah: Option<String>,
    pub nama_mata_kuliah: Option<String>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub id_semester: Option<String>,
    pub semester_mulai_berlaku: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_mata_kuliah: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_tatap_muka: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_praktek: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_praktek_lapangan: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_simulasi: Option<f32>,
    pub apakah_wajib: Option<bool>,
    pub status_sync: Option<String>,
    pub sync_at: Option<DateTime>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub semester: Option<i32>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_kurikulum", to = "id")]
    pub kurikulum: BelongsTo<crate::models::feeder::master::kurikulum::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_semester", to = "id")]
    pub semester_rel: BelongsTo<crate::models::feeder::referensi::semester::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
