//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "nilai_perkuliahan_kelas")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub id_matkul: NullableUuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub kode_mata_kuliah: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub nama_mata_kuliah: Option<String>,
    pub id_kelas_kuliah: NullableUuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub nama_kelas_kuliah: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_mata_kuliah: Option<f32>,
    pub jumlah_mahasiswa_krs: Option<i32>,
    pub jumlah_mahasiswa_dapat_nilai: Option<i32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_tm: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_prak: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_prak_lap: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_sim: Option<f32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bahasan_case: Option<String>,
    pub a_selenggara_pditt: Option<i32>,
    pub a_pengguna_pditt: Option<i32>,
    pub kuota_pditt: Option<i32>,
    pub tgl_mulai_koas: Option<Date>,
    pub tgl_selesai_koas: Option<Date>,
    pub id_mou: NullableUuid,
    pub id_kls_pditt: NullableUuid,
    pub id_sms: NullableUuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub id_smt: NullableString,
    pub tgl_create: Option<Date>,
    pub lingkup_kelas: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mode_kuliah: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub nm_smt: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub nama_prodi: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub status_sync: Option<String>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_kelas_kuliah", to = "id")]
    pub kelas_kuliah: BelongsTo<crate::models::feeder::master::kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_kelas_kuliah", to = "id")]
    pub kelas_kuliah_rel: BelongsTo<Option<crate::models::feeder::master::kelas_kuliah::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
