//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "penugasan_dosen")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub id_registrasi_dosen: Option<Uuid>,
    pub id_dosen: Option<Uuid>,
    pub nama_dosen: Option<String>,
    pub jenis_kelamin: Option<String>,
    pub nidn: Option<String>,
    pub nuptk: Option<String>,
    pub id_tahun_ajaran: Option<String>,
    pub nama_tahun_ajaran: Option<String>,
    pub id_perguruan_tinggi: Option<Uuid>,
    pub nama_perguruan_tinggi: Option<String>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub nomor_surat_tugas: Option<String>,
    pub tanggal_surat_tugas: Option<String>,
    pub mulai_surat_tugas: Option<String>,
    pub tgl_create: Option<String>,
    pub tgl_ptk_keluar: Option<String>,
    pub id_stat_pegawai: Option<i32>,
    pub id_jns_keluar: Option<i32>,
    pub id_ikatan_kerja: Option<String>,
    pub apakah_homebase: Option<bool>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_dosen", to = "id")]
    pub dosen: BelongsTo<crate::models::feeder::master::dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_tahun_ajaran", to = "id")]
    pub tahun_ajaran: BelongsTo<crate::models::feeder::referensi::tahun_ajaran::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_perguruan_tinggi", to = "id")]
    pub perguruan_tinggi: BelongsTo<crate::models::feeder::master::perguruan_tinggi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_dosen", to = "id")]
    pub dosen_rel: BelongsTo<Option<crate::models::feeder::master::dosen::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_tahun_ajaran", to = "id")]
    pub tahun_ajaran_rel: BelongsTo<Option<crate::models::feeder::referensi::tahun_ajaran::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_perguruan_tinggi", to = "id")]
    pub perguruan_tinggi_rel: BelongsTo<Option<crate::models::feeder::master::perguruan_tinggi::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi_rel: BelongsTo<Option<crate::models::feeder::master::program_studi::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
