//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "perguruan_tinggi")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_perguruan_tinggi: NullableUuid,
    pub kode_perguruan_tinggi: Option<String>,
    pub nama_perguruan_tinggi: Option<String>,
    pub nama_singkat: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub mahasiswas: HasMany<crate::models::feeder::master::mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub mahasiswa_lulusan_dropouts: HasMany<crate::models::feeder::master::mahasiswa_lulusan_dropout::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub nilai_transfer_pendidikan_mahasiswas: HasMany<crate::models::feeder::master::nilai_transfer_pendidikan_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub penugasan_dosens: HasMany<crate::models::feeder::master::penugasan_dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub profil_perguruan_tinggis: HasMany<crate::models::feeder::master::profil_perguruan_tinggi::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub program_studis: HasMany<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub riwayat_pendidikan_dosens: HasMany<crate::models::feeder::master::riwayat_pendidikan_dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub riwayat_pendidikan_mahasiswas: HasMany<crate::models::feeder::master::riwayat_pendidikan_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub mahasiswas_rel: HasMany<crate::models::feeder::master::mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub mahasiswa_lulusan_dropouts_rel: HasMany<crate::models::feeder::master::mahasiswa_lulusan_dropout::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub nilai_transfer_pendidikan_mahasiswas_rel: HasMany<crate::models::feeder::master::nilai_transfer_pendidikan_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub penugasan_dosens_rel: HasMany<crate::models::feeder::master::penugasan_dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub profil_perguruan_tinggis_rel: HasMany<crate::models::feeder::master::profil_perguruan_tinggi::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub program_studis_rel: HasMany<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub riwayat_pendidikan_dosens_rel: HasMany<crate::models::feeder::master::riwayat_pendidikan_dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub riwayat_pendidikan_mahasiswas_rel: HasMany<crate::models::feeder::master::riwayat_pendidikan_mahasiswa::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
