//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "perkuliahan_mahasiswa")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub id_registrasi_mahasiswa: Option<Uuid>,
    pub nim: Option<String>,
    pub nama_mahasiswa: Option<String>,
    pub angkatan: Option<String>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub id_periode_masuk: Option<String>,
    pub id_semester: Option<String>,
    pub nama_semester: Option<String>,
    pub id_status_mahasiswa: Option<String>,
    pub nama_status_mahasiswa: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub ips: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub ipk: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_semester: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_total: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub biaya_kuliah_smt: Option<f32>,
    pub id_pembiayaan: Option<String>,
    pub status_sync: Option<String>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_semester", to = "id")]
    pub semester: BelongsTo<crate::models::feeder::referensi::semester::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_status_mahasiswa", to = "id")]
    pub status_mahasiswa: BelongsTo<crate::models::feeder::referensi::status_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_pembiayaan", to = "id")]
    pub pembiayaan: BelongsTo<crate::models::feeder::referensi::pembiayaan::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
