//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "feeder_master", table_name = "prestasi_mahasiswa")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_prestasi: Option<Uuid>,
    pub id_mahasiswa: Option<Uuid>,
    pub nama_mahasiswa: Option<String>,
    pub id_jenis_prestasi: Option<Uuid>,
    pub nama_jenis_prestasi: Option<String>,
    pub id_tingkat_prestasi: Option<Uuid>,
    pub nama_tingkat_prestasi: Option<String>,
    pub nama_prestasi: Option<String>,
    pub tahun_prestasi: Option<i32>,
    pub penyelenggara: Option<String>,
    pub peringkat: Option<i32>,
    pub id_aktivitas: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}


impl ActiveModelBehavior for ActiveModel {}
