//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "prestasi_mahasiswa")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_prestasi: NullableUuid,
    pub id_mahasiswa: NullableUuid,
    pub nama_mahasiswa: Option<String>,
    pub id_jenis_prestasi: NullableUuid,
    pub nama_jenis_prestasi: Option<String>,
    pub id_tingkat_prestasi: NullableUuid,
    pub nama_tingkat_prestasi: Option<String>,
    pub nama_prestasi: Option<String>,
    pub tahun_prestasi: Option<i32>,
    pub penyelenggara: Option<String>,
    pub peringkat: Option<i32>,
    pub id_aktivitas: NullableUuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_mahasiswa", to = "id")]
    pub mahasiswa: BelongsTo<crate::models::feeder::master::mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_jenis_prestasi", to = "id")]
    pub jenis_prestasi: BelongsTo<crate::models::feeder::referensi::jenis_prestasi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_tingkat_prestasi", to = "id")]
    pub tingkat_prestasi: BelongsTo<crate::models::feeder::referensi::tingkat_prestasi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_mahasiswa", to = "id")]
    pub mahasiswa_rel: BelongsTo<Option<crate::models::feeder::master::mahasiswa::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_jenis_prestasi", to = "id")]
    pub jenis_prestasi_rel: BelongsTo<Option<crate::models::feeder::referensi::jenis_prestasi::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_tingkat_prestasi", to = "id")]
    pub tingkat_prestasi_rel: BelongsTo<Option<crate::models::feeder::referensi::tingkat_prestasi::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
