//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "profil_perguruan_tinggi")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_perguruan_tinggi: NullableUuid,
    pub kode_perguruan_tinggi: Option<String>,
    pub nama_perguruan_tinggi: Option<String>,
    pub telepon: Option<String>,
    pub faximile: Option<String>,
    pub email: Option<String>,
    pub website: Option<String>,
    pub jalan: Option<String>,
    pub dusun: Option<String>,
    pub kelurahan: Option<String>,
    pub kode_pos: Option<String>,
    pub id_wilayah: NullableString,
    pub nama_wilayah: Option<String>,
    pub lintang_bujur: Option<String>,
    pub bank: Option<String>,
    pub unit_cabang: Option<String>,
    pub nomor_rekening: Option<String>,
    pub mbs: Option<String>,
    pub luas_tanah_milik: Option<String>,
    pub luas_tanah_bukan_milik: Option<String>,
    pub sk_pendirian: Option<String>,
    pub id_status_milik: NullableString,
    pub nama_status_milik: Option<String>,
    pub status_perguruan_tinggi: Option<String>,
    pub sk_izin_operasional: Option<String>,
    pub tanggal_izin_operasional: Option<Date>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub nama_singkat: Option<String>,
    pub rt_rw: Option<String>,
    pub tanggal_sk_pendirian: Option<DateTime>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_perguruan_tinggi", to = "id")]
    pub perguruan_tinggi: BelongsTo<crate::models::feeder::master::perguruan_tinggi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_wilayah", to = "id")]
    pub wilayah: BelongsTo<crate::models::feeder::referensi::wilayah::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_perguruan_tinggi", to = "id")]
    pub perguruan_tinggi_rel: BelongsTo<Option<crate::models::feeder::master::perguruan_tinggi::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_wilayah", to = "id")]
    pub wilayah_rel: BelongsTo<Option<crate::models::feeder::referensi::wilayah::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
