//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "rencana_evaluasi")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_jenis_evaluasi: Option<String>,
    pub id_rencana_evaluasi: Option<Uuid>,
    pub jenis_evaluasi: Option<String>,
    pub id_matkul: Option<Uuid>,
    pub nama_mata_kuliah: Option<String>,
    pub kode_mata_kuliah: Option<String>,
    pub sks_mata_kuliah: Option<String>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub nama_evaluasi: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub deskripsi_indonesia: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub deskrips_inggris: Option<String>,
    pub nomor_urut: Option<String>,
    pub bobot_evaluasi: Option<String>,
    pub status_sync: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_jenis_evaluasi", to = "id")]
    pub jenis_evaluasi_rel: BelongsTo<crate::models::feeder::referensi::jenis_evaluasi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi_rel: BelongsTo<Option<crate::models::feeder::master::program_studi::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
