//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
pub type NullableString = Option<String>;

pub type NullableUuid = Option<Uuid>;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "riwayat_nilai_mahasiswa")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_registrasi_mahasiswa: NullableUuid,
    pub id_prodi: NullableUuid,
    pub nama_program_studi: Option<String>,
    pub id_periode: NullableString,
    pub id_matkul: NullableUuid,
    pub nama_mata_kuliah: Option<String>,
    pub id_kelas: NullableUuid,
    pub nama_kelas_kuliah: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_mata_kuliah: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub nilai_angka: Option<f32>,
    pub nilai_huruf: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub nilai_indeks: Option<f32>,
    pub nim: Option<String>,
    pub nama_mahasiswa: Option<String>,
    pub angkatan: Option<String>,
    pub status_sync: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
