//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "feeder_master", table_name = "riwayat_pendidikan_dosen")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_dosen: Option<Uuid>,
    pub nidn: Option<String>,
    pub nama_dosen: Option<String>,
    pub id_bidang_studi: Option<String>,
    pub nama_bidang_studi: Option<String>,
    pub id_jenjang_pendidikan: Option<String>,
    pub nama_jenjang_pendidikan: Option<String>,
    pub id_gelar_akademik: Option<String>,
    pub nama_gelar_akademik: Option<String>,
    pub id_perguruan_tinggi: Option<Uuid>,
    pub nama_perguruan_tinggi: Option<String>,
    pub fakultas: Option<String>,
    pub tahun_lulus: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_lulus: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub ipk: Option<f32>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub nuptk: Option<String>,
}


impl ActiveModelBehavior for ActiveModel {}
