//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
pub type NullableString = Option<String>;

pub type NullableUuid = Option<Uuid>;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "riwayat_pendidikan_dosen")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_dosen: NullableUuid,
    pub nidn: Option<String>,
    pub nama_dosen: Option<String>,
    pub id_bidang_studi: NullableString,
    pub nama_bidang_studi: Option<String>,
    pub id_jenjang_pendidikan: NullableString,
    pub nama_jenjang_pendidikan: Option<String>,
    pub id_gelar_akademik: NullableString,
    pub nama_gelar_akademik: Option<String>,
    pub id_perguruan_tinggi: NullableUuid,
    pub nama_perguruan_tinggi: Option<String>,
    pub fakultas: Option<String>,
    pub tahun_lulus: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_lulus: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub ipk: Option<f32>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub nuptk: Option<String>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_dosen", to = "id")]
    pub dosen: BelongsTo<crate::models::feeder::master::dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_jenjang_pendidikan", to = "id")]
    pub jenjang_pendidikan: BelongsTo<crate::models::feeder::referensi::jenjang_pendidikan::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_perguruan_tinggi", to = "id")]
    pub perguruan_tinggi: BelongsTo<crate::models::feeder::master::perguruan_tinggi::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
