//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(
    schema_name = "feeder_master",
    table_name = "riwayat_sertifikasi_dosen"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_dosen: Option<Uuid>,
    pub nidn: Option<String>,
    pub nama_dosen: Option<String>,
    pub nomor_peserta: Option<String>,
    pub id_bidang_studi: Option<String>,
    pub nama_bidang_studi: Option<String>,
    pub id_jenis_sertifikasi: Option<String>,
    pub nama_jenis_sertifikasi: Option<String>,
    pub tahun_sertifikasi: Option<String>,
    pub sk_sertifikasi: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub nuptk: Option<String>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_dosen", to = "id")]
    pub dosen: BelongsTo<crate::models::feeder::master::dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_jenis_sertifikasi", to = "id")]
    pub jenis_sertifikasi: BelongsTo<crate::models::feeder::referensi::jenis_sertifikasi::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
