//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(
    schema_name = "feeder_master",
    table_name = "riwayat_pendidikan_mahasiswa"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_registrasi_mahasiswa: Option<Uuid>,
    pub id_mahasiswa: Option<Uuid>,
    pub nim: Option<String>,
    pub nama_mahasiswa: Option<String>,
    pub id_jenis_daftar: Option<i32>,
    pub nama_jenis_daftar: Option<String>,
    pub id_jalur_daftar: Option<i32>,
    pub id_periode_masuk: Option<String>,
    pub nama_periode_masuk: Option<String>,
    pub id_jenis_keluar: Option<i32>,
    pub keterangan_keluar: Option<String>,
    pub id_perguruan_tinggi: Option<Uuid>,
    pub nama_perguruan_tinggi: Option<String>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_diakui: Option<f32>,
    pub id_perguruan_tinggi_asal: Option<Uuid>,
    pub nama_perguruan_tinggi_asal: Option<String>,
    pub id_prodi_asal: Option<Uuid>,
    pub nama_program_studi_asal: Option<String>,
    pub jenis_kelamin: Option<String>,
    pub tanggal_daftar: Option<Date>,
    pub nama_ibu_kandung: Option<String>,
    pub id_pembiayaan: Option<i32>,
    pub biaya_masuk: Option<i32>,
    pub id_bidang_minat: Option<String>,
    pub nm_bidang_minat: Option<String>,
    pub id_periode_keluar: Option<String>,
    pub tanggal_keluar: Option<Date>,
    pub last_update: Option<Date>,
    pub tgl_create: Option<Date>,
    pub status_sync: Option<String>,
    pub nama_pembiayaan_awal: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_mahasiswa", to = "id")]
    pub mahasiswa: BelongsTo<crate::models::feeder::master::mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_jenis_keluar", to = "id")]
    pub jenis_keluar: BelongsTo<crate::models::feeder::referensi::jenis_keluar::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_perguruan_tinggi", to = "id")]
    pub perguruan_tinggi: BelongsTo<crate::models::feeder::master::perguruan_tinggi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_pembiayaan", to = "id")]
    pub pembiayaan: BelongsTo<crate::models::feeder::referensi::pembiayaan::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
