//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

pub type NullableUuid = Option<Uuid>;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "riwayat_pangkat_dosen")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_dosen: NullableUuid,
    pub nidn: Option<String>,
    pub nama_dosen: Option<String>,
    pub id_pangkat_golongan: NullableUuid,
    pub nama_pangkat_golongan: Option<String>,
    pub sk_pangkat: Option<String>,
    pub tanggal_sk_pangkat: Option<Date>,
    pub mulai_sk_pangkat: Option<Date>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub nuptk: Option<String>,
    pub masa_kerja_dalam_tahun: Option<i32>,
    pub masa_kerja_dalam_bulan: Option<i32>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_dosen", to = "id")]
    pub dosen: BelongsTo<crate::models::feeder::master::dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_pangkat_golongan", to = "id")]
    pub pangkat_golongan: BelongsTo<crate::models::feeder::referensi::pangkat_golongan::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
