//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "riwayat_penelitian_dosen")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_dosen: Option<Uuid>,
    pub nidn: Option<String>,
    pub nama_dosen: Option<String>,
    pub id_penelitian: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub judul_penelitian: Option<String>,
    pub id_kelompok_bidang: Option<Uuid>,
    pub kode_kelompok_bidang: Option<String>,
    pub nama_kelompok_bidang: Option<String>,
    pub id_lembaga_iptek: Option<Uuid>,
    pub nama_lembaga_iptek: Option<String>,
    pub tahun_kegiatan: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub nuptk: Option<String>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_dosen", to = "id")]
    pub dosen: BelongsTo<crate::models::feeder::master::dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_dosen", to = "id")]
    pub dosen_rel: BelongsTo<Option<crate::models::feeder::master::dosen::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
