//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "feeder_master",
    table_name = "skala_nilai_program_studi"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tgl_create: Option<Date>,
    pub id_bobot_nilai: Option<Uuid>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub nilai_huruf: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub nilai_indeks: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub bobot_minimum: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub bobot_maksimum: Option<f32>,
    pub tanggal_mulai_efektif: Option<Date>,
    pub tanggal_akhir_efektif: Option<Date>,
    pub status_sync: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}


impl ActiveModelBehavior for ActiveModel {}
