//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "substansi_matakuliah")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_substansi: NullableUuid,
    pub id_prodi: NullableUuid,
    pub nama_program_studi: Option<String>,
    pub nama_substansi: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_mata_kuliah: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_tatap_muka: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_praktek: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_praktek_lapangan: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_simulasi: Option<f32>,
    pub id_jenis_substansi: NullableUuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi: BelongsTo<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_jenis_substansi", to = "id")]
    pub jenis_substansi: BelongsTo<crate::models::feeder::referensi::jenis_substansi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_prodi", to = "id")]
    pub prodi_rel: BelongsTo<Option<crate::models::feeder::master::program_studi::Entity>>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_jenis_substansi", to = "id")]
    pub jenis_substansi_rel: BelongsTo<Option<crate::models::feeder::referensi::jenis_substansi::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
