//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "substansi_matakuliah")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_substansi: Option<Uuid>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub nama_substansi: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_mata_kuliah: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_tatap_muka: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_praktek: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_praktek_lapangan: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_simulasi: Option<f32>,
    pub id_jenis_substansi: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}


impl ActiveModelBehavior for ActiveModel {}
