//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_master", table_name = "transkrip_mahasiswa")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_registrasi_mahasiswa: NullableUuid,
    pub id_matkul: NullableUuid,
    pub id_kelas_kuliah: NullableUuid,
    pub id_nilai_transfer: NullableString,
    pub id_konversi_aktivitas: NullableString,
    pub smt_diambil: Option<String>,
    pub kode_mata_kuliah: Option<String>,
    pub nama_mata_kuliah: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sks_mata_kuliah: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub nilai_angka: Option<f32>,
    pub nilai_huruf: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub nilai_indeks: Option<f32>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_kelas_kuliah", to = "id")]
    pub kelas_kuliah: BelongsTo<crate::models::feeder::master::kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_kelas_kuliah", to = "id")]
    pub kelas_kuliah_rel: BelongsTo<Option<crate::models::feeder::master::kelas_kuliah::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
