//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_lecturer_master", table_name = "lecturers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: String,
    pub name: Option<String>,
    pub individual_id: Uuid,
    pub institution_id: Option<Uuid>,
    pub alternative_code: Option<String>,
    pub accessor_number: Option<String>,
    pub identification_number: Option<String>,
    pub status_id: Option<Uuid>,
    pub contract_id: Option<Uuid>,
    pub rank_id: Option<Uuid>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub front_title: Option<String>,
    pub last_title: Option<String>,
    pub id_dosen: Option<Uuid>,
    pub group_id: Option<Uuid>,
    pub nuptk: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
