//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_lecturer_master", table_name = "lecturers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: String,
    pub name: Option<String>,
    pub individual_id: Uuid,
    pub institution_id: Option<Uuid>,
    pub alternative_code: Option<String>,
    pub accessor_number: Option<String>,
    pub identification_number: Option<String>,
    pub status_id: Option<Uuid>,
    pub contract_id: Option<Uuid>,
    pub rank_id: Option<Uuid>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub front_title: Option<String>,
    pub last_title: Option<String>,
    pub id_dosen: Option<Uuid>,
    pub group_id: Option<Uuid>,
    pub nuptk: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "individual_id", to = "id")]
    pub individual: BelongsTo<crate::models::person::master::individual::Entity>,
    #[sea_orm(belongs_to, from = "institution_id", to = "id")]
    pub institution: BelongsTo<Option<crate::models::institution::master::institutions::Entity>>,
    #[sea_orm(belongs_to, from = "status_id", to = "id")]
    pub status: BelongsTo<Option<crate::models::academic::lecturer::reference::statuses::Entity>>,
    #[sea_orm(belongs_to, from = "contract_id", to = "id")]
    pub contract: BelongsTo<Option<crate::models::academic::lecturer::reference::contracts::Entity>>,
    #[sea_orm(belongs_to, from = "rank_id", to = "id")]
    pub rank: BelongsTo<Option<crate::models::academic::lecturer::reference::ranks::Entity>>,
    #[sea_orm(belongs_to, from = "group_id", to = "id")]
    pub group: BelongsTo<Option<crate::models::academic::lecturer::reference::groups::Entity>>,
    #[sea_orm(has_many)]
    pub teach_lecturers: HasMany<crate::models::academic::campaign::transaction::teach_lecturers::Entity>,
    #[sea_orm(has_many)]
    pub academic_groups: HasMany<crate::models::academic::lecturer::transaction::academic_groups::Entity>,
    #[sea_orm(has_many)]
    pub academic_ranks: HasMany<crate::models::academic::lecturer::transaction::academic_ranks::Entity>,
    #[sea_orm(has_many)]
    pub homebases: HasMany<crate::models::academic::lecturer::transaction::homebases::Entity>,
    #[sea_orm(has_many)]
    pub counsellors: HasMany<crate::models::academic::student::adviser::counsellors::Entity>,
    #[sea_orm(has_many)]
    pub advisers: HasMany<crate::models::academic::student::final_assignment::transaction::advisers::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
