//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "document_transaction", table_name = "archives")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub dir: String,
    pub mimetype: String,
    pub size: Option<i32>,
    pub archiveable_id: Option<Uuid>,
    pub archiveable_type: Option<String>,
    pub archive_type_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub is_knowledge: bool,
    #[sea_orm(belongs_to, from = "archive_type_id", to = "id")]
    pub archive_type: BelongsTo<crate::models::document::reference::archive_types::Entity>,
    #[sea_orm(has_many)]
    pub evaluation_details: HasMany<crate::models::academic::prior_learning_recognition::transaction::evaluation_details::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
