//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "document_transaction", table_name = "archives")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub dir: String,
    pub mimetype: String,
    pub size: Option<i32>,
    pub archiveable_id: Option<Uuid>,
    pub archiveable_type: Option<String>,
    pub archive_type_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub is_knowledge: bool,
    #[sea_orm(belongs_to, from = "archive_type_id", to = "id")]
    pub archive_type: BelongsTo<crate::models::document::reference::archive_types::Entity>,
    #[sea_orm(has_many)]
    pub evaluation_details: HasMany<crate::models::academic::prior_learning_recognition::transaction::evaluation_details::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}

pub struct ArchiveToIndividual;

impl Linked for ArchiveToIndividual {
    type FromEntity = Entity;
    type ToEntity = crate::models::person::master::individual::Entity;

    fn link(&self) -> Vec<RelationDef> {
        let rel: RelationDef = Entity::belongs_to(crate::models::person::master::individual::Entity)
            .from(Column::ArchiveableId)
            .to(crate::models::person::master::individual::Column::Id)
            .on_condition(|_left, _right| {
                Column::ArchiveableType.eq("Individual").into()
            })
            .into();
        vec![rel]
    }
}

pub struct ArchiveToInstitution;

impl Linked for ArchiveToInstitution {
    type FromEntity = Entity;
    type ToEntity = crate::models::institution::master::institutions::Entity;

    fn link(&self) -> Vec<RelationDef> {
        let rel: RelationDef = Entity::belongs_to(crate::models::institution::master::institutions::Entity)
            .from(Column::ArchiveableId)
            .to(crate::models::institution::master::institutions::Column::Id)
            .on_condition(|_left, _right| {
                Column::ArchiveableType.eq("Institution").into()
            })
            .into();
        vec![rel]
    }
}
