//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_candidate_reference", table_name = "phases")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: i32,
    pub alphabet_code: String,
    pub name: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(has_many)]
    pub exam_classes: HasMany<crate::models::academic::candidate::master::exam_classes::Entity>,
    #[sea_orm(has_many)]
    pub candidate_unit_choices: HasMany<crate::models::academic::candidate::transaction::candidate_unit_choices::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
