//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::document_types::Entity as DocumentTypes;
pub use super::phases::Entity as Phases;
pub use super::registration_categories::Entity as RegistrationCategories;
pub use super::registration_types::Entity as RegistrationTypes;
