//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::document_types::Entity as AcademicCandidateReferenceDocumentTypes;
pub use super::phases::Entity as AcademicCandidateReferencePhases;
pub use super::registration_categories::Entity as AcademicCandidateReferenceRegistrationCategories;
pub use super::registration_types::Entity as AcademicCandidateReferenceRegistrationTypes;
