//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_candidate_reference",
    table_name = "registration_types"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: Option<i32>,
    pub alphabet_code: Option<String>,
    pub name: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub student_registration_id: Option<Uuid>,
    pub unit_id: Option<Uuid>,
    pub registration_category_id: Option<Uuid>,
    pub institution_id: Option<Uuid>,
    #[sea_orm(belongs_to, from = "unit_id", to = "id")]
    pub unit: BelongsTo<Option<crate::models::institution::master::units::Entity>>,
    #[sea_orm(belongs_to, from = "registration_category_id", to = "id")]
    pub registration_category: BelongsTo<Option<crate::models::academic::candidate::reference::registration_categories::Entity>>,
    #[sea_orm(belongs_to, from = "institution_id", to = "id")]
    pub institution: BelongsTo<Option<crate::models::institution::master::institutions::Entity>>,
    #[sea_orm(has_many)]
    pub candidates: HasMany<crate::models::academic::candidate::master::candidates::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
