//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "institution_master", table_name = "institutions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: Option<String>,
    pub name: Option<String>,
    pub alphabet_code: Option<String>,
    pub is_active: bool,
    pub variety_id: Uuid,
    pub category_id: Uuid,
    pub country_id: Uuid,
    pub parent_id: Option<Uuid>,
    pub feeder_id: Option<Uuid>,
    pub academic_year_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "variety_id", to = "id")]
    pub variety: BelongsTo<crate::models::institution::reference::varieties::Entity>,
    #[sea_orm(belongs_to, from = "category_id", to = "id")]
    pub category: BelongsTo<crate::models::institution::reference::categories::Entity>,
    #[sea_orm(has_many)]
    pub units: HasMany<crate::models::institution::master::units::Entity>,
    #[sea_orm(has_many)]
    pub employees: HasMany<crate::models::institution::master::employees::Entity>,
    #[sea_orm(belongs_to, from = "country_id", to = "id")]
    pub country: BelongsTo<crate::models::location::countries::Entity>,
    #[sea_orm(belongs_to, from = "academic_year_id", to = "id")]
    pub academic_year: BelongsTo<Option<crate::models::academic::general::reference::academic_years::Entity>>,
    #[sea_orm(has_many)]
    pub estimasi: HasMany<crate::models::feeder::akumulasi::estimasi::Entity>,
    #[sea_orm(has_many)]
    pub jumlah_data: HasMany<crate::models::feeder::akumulasi::jumlah_data::Entity>,
    #[sea_orm(has_many)]
    pub kredential: HasMany<crate::models::feeder::akun::kredential::Entity>,
    #[sea_orm(has_many)]
    pub calendars: HasMany<crate::models::academic::campaign::transaction::calendars::Entity>,
    #[sea_orm(has_many)]
    pub candidates: HasMany<crate::models::academic::candidate::master::candidates::Entity>,
    #[sea_orm(has_many)]
    pub registration_types: HasMany<crate::models::academic::candidate::reference::registration_types::Entity>,
    #[sea_orm(has_many)]
    pub lecturers: HasMany<crate::models::academic::lecturer::master::lecturers::Entity>,
    #[sea_orm(has_many)]
    pub homebases: HasMany<crate::models::academic::lecturer::transaction::homebases::Entity>,
    #[sea_orm(has_many)]
    pub bundles: HasMany<crate::models::academic::survey::master::bundles::Entity>,
    #[sea_orm(has_many)]
    pub questions: HasMany<crate::models::academic::survey::master::questions::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}

pub struct InstitutionToArchive;

impl Linked for InstitutionToArchive {
    type FromEntity = Entity;
    type ToEntity = crate::models::document::transaction::archives::Entity;

    fn link(&self) -> Vec<RelationDef> {
        let rel: RelationDef = crate::models::document::transaction::archives::Entity::belongs_to(Entity)
            .from(crate::models::document::transaction::archives::Column::ArchiveableId)
            .to(Column::Id)
            .on_condition(|_left, _right| {
                crate::models::document::transaction::archives::Column::ArchiveableType.eq("Institution").into()
            })
            .into();
        vec![rel.rev()]
    }
}
