//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::employees::Entity as Employees;
pub use super::institutions::Entity as Institutions;
pub use super::staffes::Entity as Staffes;
pub use super::units::Entity as Units;
