//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::employees::Entity as InstitutionMasterEmployees;
pub use super::institutions::Entity as InstitutionMasterInstitutions;
pub use super::staffes::Entity as InstitutionMasterStaffes;
pub use super::units::Entity as InstitutionMasterUnits;
