//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "institution_master", table_name = "staffes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: Option<String>,
    pub name: Option<String>,
    pub decree_number: Option<String>,
    pub decree_date: Option<Date>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub employee_id: Uuid,
    pub unit_id: Uuid,
    pub position_type_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "employee_id", to = "id")]
    pub employee: BelongsTo<crate::models::institution::master::employees::Entity>,
    #[sea_orm(belongs_to, from = "unit_id", to = "id")]
    pub unit: BelongsTo<crate::models::institution::master::units::Entity>,
    #[sea_orm(belongs_to, from = "position_type_id", to = "id")]
    pub position_type: BelongsTo<Option<crate::models::institution::reference::position_type::Entity>>,
    #[sea_orm(has_many)]
    pub teach_decrees: HasMany<crate::models::academic::campaign::transaction::teach_decrees::Entity>,
    #[sea_orm(has_many)]
    pub decrees: HasMany<crate::models::academic::student::adviser::decrees::Entity>,
    #[sea_orm(has_many)]
    pub final_assignment_decrees: HasMany<crate::models::academic::student::final_assignment::transaction::final_assignment_decrees::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}

pub struct StaffToRole;

impl Linked for StaffToRole {
    type FromEntity = Entity;
    type ToEntity = crate::models::auth::role::Entity;

    fn link(&self) -> Vec<RelationDef> {
        let rel: RelationDef = crate::models::auth::role::Entity::belongs_to(Entity)
            .from(crate::models::auth::role::Column::RoleableId)
            .to(Column::Id)
            .on_condition(|_left, _right| {
                crate::models::auth::role::Column::RoleableType.eq("Staff").into()
            })
            .into();
        vec![rel.rev()]
    }
}
