//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "institution_master", table_name = "units")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: Option<String>,
    pub name: Option<String>,
    pub is_active: bool,
    pub unit_type_id: Uuid,
    pub institution_id: Uuid,
    pub parent_id: Option<Uuid>,
    pub education_id: Uuid,
    pub feeder_id: Option<Uuid>,
    pub lft: Option<i64>,
    pub rght: Option<i64>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "unit_type_id", to = "id")]
    pub unit_type: BelongsTo<crate::models::institution::reference::unit_types::Entity>,
    #[sea_orm(belongs_to, from = "institution_id", to = "id")]
    pub institution: BelongsTo<crate::models::institution::master::institutions::Entity>,
    #[sea_orm(has_many)]
    pub staffes: HasMany<crate::models::institution::master::staffes::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
