//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "feeder_referensi", table_name = "agama")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_agama: Option<i32>,
    pub nama_agama: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub biodata_dosens: HasMany<crate::models::feeder::master::biodata_dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub biodata_mahasiswas: HasMany<crate::models::feeder::master::biodata_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub dosens: HasMany<crate::models::feeder::master::dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub mahasiswas: HasMany<crate::models::feeder::master::mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub biodata_dosens_rel: HasMany<crate::models::feeder::master::biodata_dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub biodata_mahasiswas_rel: HasMany<crate::models::feeder::master::biodata_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub dosens_rel: HasMany<crate::models::feeder::master::dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub mahasiswas_rel: HasMany<crate::models::feeder::master::mahasiswa::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
