//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "feeder_referensi",
    table_name = "jenis_aktifitas_mahasiswa"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_jenis_aktivitas_mahasiswa: Option<String>,
    pub nama_jenis_aktivitas_mahasiswa: Option<String>,
    pub untuk_kampus_merdeka: Option<String>,
    pub jenis_aktivitas_mahasiswa: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}


impl ActiveModelBehavior for ActiveModel {}
