//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "feeder_referensi", table_name = "jenis_keluar")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_jenis_keluar: Option<String>,
    pub jenis_keluar: Option<String>,
    pub apa_mahasiswa: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub mahasiswa_lulusan_dropouts: HasMany<crate::models::feeder::master::mahasiswa_lulusan_dropout::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub riwayat_pendidikan_mahasiswas: HasMany<crate::models::feeder::master::riwayat_pendidikan_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub mahasiswa_lulusan_dropouts_rel: HasMany<crate::models::feeder::master::mahasiswa_lulusan_dropout::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub riwayat_pendidikan_mahasiswas_rel: HasMany<crate::models::feeder::master::riwayat_pendidikan_mahasiswa::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
