//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "feeder_referensi", table_name = "jenis_evaluasi")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_jenis_evaluasi: Option<i32>,
    pub nama_jenis_evaluasi: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub dosen_pengajar_kelas_kuliahs: HasMany<crate::models::feeder::master::dosen_pengajar_kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub komponen_evaluasi_kelass: HasMany<crate::models::feeder::master::komponen_evaluasi_kelas::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub rencana_evaluasis: HasMany<crate::models::feeder::master::rencana_evaluasi::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub dosen_pengajar_kelas_kuliahs_rel: HasMany<crate::models::feeder::master::dosen_pengajar_kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub komponen_evaluasi_kelass_rel: HasMany<crate::models::feeder::master::komponen_evaluasi_kelas::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub rencana_evaluasis_rel: HasMany<crate::models::feeder::master::rencana_evaluasi::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
