//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "feeder_referensi", table_name = "jenjang_pendidikan")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_jenjang_didik: Option<String>,
    pub nama_jenjang_didik: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub fakultass: HasMany<crate::models::feeder::master::fakultas::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub program_studis: HasMany<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub riwayat_pendidikan_dosens: HasMany<crate::models::feeder::master::riwayat_pendidikan_dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub fakultass_rel: HasMany<crate::models::feeder::master::fakultas::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub program_studis_rel: HasMany<crate::models::feeder::master::program_studi::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub riwayat_pendidikan_dosens_rel: HasMany<crate::models::feeder::master::riwayat_pendidikan_dosen::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
