//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

pub type NullableUuid = Option<Uuid>;
pub type NullableString = Option<String>;
pub type NullableI32 = Option<i32>;
pub type NullableF32 = Option<f32>;
pub type NullableDateTime = Option<DateTime>;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_referensi", table_name = "kategori_kegiatan")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_kategori_kegiatan: NullableI32,
    #[sea_orm(column_type = "Text", nullable)]
    pub nama_kategori_kegiatan: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub bimbing_mahasiswas: HasMany<crate::models::feeder::master::bimbing_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub mahasiswa_bimbingan_dosens: HasMany<crate::models::feeder::master::mahasiswa_bimbingan_dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub uji_mahasiswas: HasMany<crate::models::feeder::master::uji_mahasiswa::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
