//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "feeder_referensi", table_name = "level_wilayah")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_level_wilayah: Option<String>,
    pub nama_level_wilayah: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub wilayahs: HasMany<crate::models::feeder::referensi::wilayah::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub wilayahs_rel: HasMany<crate::models::feeder::referensi::wilayah::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
