//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "feeder_referensi", table_name = "periode_lampau")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_program_studi: Option<String>,
    pub program_studi: Option<String>,
    pub id_semester: Option<String>,
    pub semester: Option<String>,
    pub tanggal_mulai_perkuliahan: Option<Date>,
    pub tanggal_selesai_perkuliahan: Option<Date>,
    pub tipe_periode: Option<String>,
    pub sync_at: Option<DateTime>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}


impl ActiveModelBehavior for ActiveModel {}
