//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "feeder_referensi", table_name = "semester")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_semester: Option<String>,
    pub id_tahun_ajaran: Option<String>,
    pub nama_semester: Option<String>,
    pub semester: Option<String>,
    pub a_periode_aktif: Option<String>,
    pub tanggal_mulai: Option<Date>,
    pub tanggal_selesai: Option<Date>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub aktifitas_kuliah_mahasiswas: HasMany<crate::models::feeder::master::aktifitas_kuliah_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub aktifitas_mahasiswas: HasMany<crate::models::feeder::master::aktifitas_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub detail_nilai_perkuliahan_kelass: HasMany<crate::models::feeder::master::detail_nilai_perkuliahan_kelas::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub dosen_pengajar_kelas_kuliahs: HasMany<crate::models::feeder::master::dosen_pengajar_kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub kelas_kuliahs: HasMany<crate::models::feeder::master::kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub konversi_kampus_merdekas: HasMany<crate::models::feeder::master::konversi_kampus_merdeka::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub kurikulums: HasMany<crate::models::feeder::master::kurikulum::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub matakuliah_kurikulums: HasMany<crate::models::feeder::master::matakuliah_kurikulum::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub nilai_transfer_pendidikan_mahasiswas: HasMany<crate::models::feeder::master::nilai_transfer_pendidikan_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub periode_perkuliahans: HasMany<crate::models::feeder::master::periode_perkuliahan::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub perkuliahan_mahasiswas: HasMany<crate::models::feeder::master::perkuliahan_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub periode_lampaus: HasMany<crate::models::feeder::referensi::periode_lampau::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_tahun_ajaran", to = "id")]
    pub tahun_ajaran: BelongsTo<crate::models::feeder::referensi::tahun_ajaran::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub aktifitas_mahasiswas_rel: HasMany<crate::models::feeder::master::aktifitas_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub detail_nilai_perkuliahan_kelass_rel: HasMany<crate::models::feeder::master::detail_nilai_perkuliahan_kelas::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub dosen_pengajar_kelas_kuliahs_rel: HasMany<crate::models::feeder::master::dosen_pengajar_kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub kelas_kuliahs_rel: HasMany<crate::models::feeder::master::kelas_kuliah::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub konversi_kampus_merdekas_rel: HasMany<crate::models::feeder::master::konversi_kampus_merdeka::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub kurikulums_rel: HasMany<crate::models::feeder::master::kurikulum::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub matakuliah_kurikulums_rel: HasMany<crate::models::feeder::master::matakuliah_kurikulum::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub nilai_transfer_pendidikan_mahasiswas_rel: HasMany<crate::models::feeder::master::nilai_transfer_pendidikan_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub periode_perkuliahans_rel: HasMany<crate::models::feeder::master::periode_perkuliahan::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub perkuliahan_mahasiswas_rel: HasMany<crate::models::feeder::master::perkuliahan_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub aktifitas_kuliah_mahasiswas_rel: HasMany<crate::models::feeder::master::aktifitas_kuliah_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub periode_lampaus_rel: HasMany<crate::models::feeder::referensi::periode_lampau::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_tahun_ajaran", to = "id")]
    pub tahun_ajaran_rel: BelongsTo<Option<crate::models::feeder::referensi::tahun_ajaran::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
