//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

pub type NullableUuid = Option<Uuid>;
pub type NullableString = Option<String>;
pub type NullableI32 = Option<i32>;
pub type NullableF32 = Option<f32>;
pub type NullableDateTime = Option<DateTime>;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "feeder_referensi", table_name = "status_mahasiswa")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_status_mahasiswa: NullableString,
    pub nama_status_mahasiswa: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub aktifitas_kuliah_mahasiswas: HasMany<crate::models::feeder::master::aktifitas_kuliah_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub mahasiswas: HasMany<crate::models::feeder::master::mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub perkuliahan_mahasiswas: HasMany<crate::models::feeder::master::perkuliahan_mahasiswa::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
