//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

pub type NullableUuid = Option<Uuid>;
pub type NullableString = Option<String>;
pub type NullableI32 = Option<i32>;
pub type NullableF32 = Option<f32>;
pub type NullableDateTime = Option<DateTime>;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "feeder_referensi", table_name = "tingkat_prestasi")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_tingkat_prestasi: NullableI32,
    pub nama_tingkat_prestasi: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub prestasi_mahasiswas: HasMany<crate::models::feeder::master::prestasi_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub prestasi_mahasiswas_rel: HasMany<crate::models::feeder::master::prestasi_mahasiswa::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
