//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "feeder_referensi", table_name = "wilayah")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_level_wilayah: Option<i32>,
    pub id_wilayah: Option<String>,
    pub id_negara: Option<String>,
    pub nama_wilayah: Option<String>,
    pub id_induk_wilayah: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub biodata_dosens: HasMany<crate::models::feeder::master::biodata_dosen::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub biodata_mahasiswas: HasMany<crate::models::feeder::master::biodata_mahasiswa::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub profil_perguruan_tinggis: HasMany<crate::models::feeder::master::profil_perguruan_tinggi::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_level_wilayah", to = "id")]
    pub level_wilayah: BelongsTo<crate::models::feeder::referensi::level_wilayah::Entity>,
    #[serde(skip)]
    #[sea_orm(belongs_to, from = "id_negara", to = "id")]
    pub negara: BelongsTo<crate::models::feeder::referensi::negara::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
