//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::bundle_categories::Entity as AcademicSurveyReferenceBundleCategories;
pub use super::question_varieties::Entity as AcademicSurveyReferenceQuestionVarieties;
