//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod attend_types;
pub mod calendar_categories;
pub mod encounter_categories;
pub mod implementations;
pub mod scopes;
pub mod substances;
