//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::attend_types::Entity as AcademicCampaignReferenceAttendTypes;
pub use super::calendar_categories::Entity as AcademicCampaignReferenceCalendarCategories;
pub use super::encounter_categories::Entity as AcademicCampaignReferenceEncounterCategories;
pub use super::implementations::Entity as AcademicCampaignReferenceImplementations;
pub use super::scopes::Entity as AcademicCampaignReferenceScopes;
pub use super::substances::Entity as AcademicCampaignReferenceSubstances;
