//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_campaign_transaction",
    table_name = "activities"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub week_quantity: Option<i32>,
    pub student_target: i32,
    pub candidate_number: i32,
    pub candidate_pass: i32,
    pub became_student: i32,
    pub transfer_student: i32,
    pub total_class_member: Option<i32>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub start_transaction: Option<Date>,
    pub end_transaction: Option<Date>,
    pub unit_id: Uuid,
    pub academic_year_id: Uuid,
    pub is_active: Option<bool>,
    pub feeder_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "unit_id", to = "id")]
    pub unit: BelongsTo<crate::models::institution::master::units::Entity>,
    #[sea_orm(belongs_to, from = "academic_year_id", to = "id")]
    pub academic_year: BelongsTo<crate::models::academic::general::reference::academic_years::Entity>,
    #[sea_orm(has_many)]
    pub class_codes: HasMany<crate::models::academic::campaign::transaction::class_codes::Entity>,
    #[sea_orm(has_many)]
    pub teach_decrees: HasMany<crate::models::academic::campaign::transaction::teach_decrees::Entity>,
    #[sea_orm(has_many)]
    pub teaches: HasMany<crate::models::academic::campaign::transaction::teaches::Entity>,
    #[sea_orm(has_many)]
    pub detail_activities: HasMany<crate::models::academic::student::campaign::detail_activities::Entity>,
    #[sea_orm(has_many)]
    pub final_assignment_decrees: HasMany<crate::models::academic::student::final_assignment::transaction::final_assignment_decrees::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
