//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_campaign_transaction",
    table_name = "calendar_details"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub calendar_category_id: Uuid,
    pub calendar_id: Uuid,
    pub start_date: Date,
    pub end_date: Date,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "calendar_category_id", to = "id")]
    pub calendar_category: BelongsTo<crate::models::academic::campaign::reference::calendar_categories::Entity>,
    #[sea_orm(belongs_to, from = "calendar_id", to = "id")]
    pub calendar: BelongsTo<crate::models::academic::campaign::transaction::calendars::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
