//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_campaign_transaction", table_name = "grades")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: Option<i32>,
    pub alphabet_code: Option<String>,
    pub name: String,
    #[sea_orm(column_type = "Double")]
    pub grade: f64,
    #[sea_orm(column_type = "Double")]
    pub minimum: f64,
    #[sea_orm(column_type = "Double")]
    pub maximum: f64,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub unit_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub feeder_id: Option<Uuid>,
    #[sea_orm(belongs_to, from = "unit_id", to = "id")]
    pub unit: BelongsTo<crate::models::institution::master::units::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
