//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::activities::Entity as AcademicCampaignTransactionActivities;
pub use super::calendar_details::Entity as AcademicCampaignTransactionCalendarDetails;
pub use super::calendars::Entity as AcademicCampaignTransactionCalendars;
pub use super::class_codes::Entity as AcademicCampaignTransactionClassCodes;
pub use super::grades::Entity as AcademicCampaignTransactionGrades;
pub use super::schedules::Entity as AcademicCampaignTransactionSchedules;
pub use super::teach_decrees::Entity as AcademicCampaignTransactionTeachDecrees;
pub use super::teach_evaluations::Entity as AcademicCampaignTransactionTeachEvaluations;
pub use super::teach_lecturers::Entity as AcademicCampaignTransactionTeachLecturers;
pub use super::teaches::Entity as AcademicCampaignTransactionTeaches;
