//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::activities::Entity as Activities;
pub use super::calendar_details::Entity as CalendarDetails;
pub use super::calendars::Entity as Calendars;
pub use super::class_codes::Entity as ClassCodes;
pub use super::grades::Entity as Grades;
pub use super::schedules::Entity as Schedules;
pub use super::teach_decrees::Entity as TeachDecrees;
pub use super::teach_evaluations::Entity as TeachEvaluations;
pub use super::teach_lecturers::Entity as TeachLecturers;
pub use super::teaches::Entity as Teaches;
