//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_campaign_transaction",
    table_name = "teach_evaluations"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub thread: Option<i32>,
    pub name: Option<String>,
    pub english_name: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub evaluation_weight: Option<f32>,
    pub evaluation_type_id: Option<Uuid>,
    pub feeder_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub teach_id: Option<Uuid>,
    #[sea_orm(belongs_to, from = "evaluation_type_id", to = "id")]
    pub evaluation_type: BelongsTo<Option<crate::models::academic::course::reference::evaluation_types::Entity>>,
    #[sea_orm(belongs_to, from = "teach_id", to = "id")]
    pub teach: BelongsTo<Option<crate::models::academic::campaign::transaction::teaches::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
