//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_campaign_transaction",
    table_name = "teach_lecturers"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: Option<String>,
    pub planning: i32,
    pub realization: i32,
    #[sea_orm(column_type = "Decimal(Some((3, 1)))", nullable)]
    pub credit: Option<Decimal>,
    pub is_lecturer_home_base: bool,
    pub lecturer_id: Uuid,
    pub teach_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub feeder_id: Option<Uuid>,
    #[sea_orm(belongs_to, from = "lecturer_id", to = "id")]
    pub lecturer: BelongsTo<crate::models::academic::lecturer::master::lecturers::Entity>,
    #[sea_orm(belongs_to, from = "teach_id", to = "id")]
    pub teach: BelongsTo<crate::models::academic::campaign::transaction::teaches::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
