//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_campaign_transaction", table_name = "teaches")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    pub class_code_id: Uuid,
    pub course_id: Uuid,
    pub activity_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub practice_start_date: Option<Date>,
    pub practice_end_date: Option<Date>,
    pub curriculum_detail_id: Option<Uuid>,
    pub teach_decree_id: Uuid,
    pub is_lecturer_credit_sum_problem: Option<bool>,
    pub is_lock: Option<bool>,
    pub encounter_category_id: Option<Uuid>,
    pub scope_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub max_member: Option<i32>,
    pub feeder_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
