//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "academic_campaign_transaction", table_name = "teaches")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    pub class_code_id: Uuid,
    pub course_id: Uuid,
    pub activity_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub practice_start_date: Option<Date>,
    pub practice_end_date: Option<Date>,
    pub curriculum_detail_id: Option<Uuid>,
    pub teach_decree_id: Uuid,
    pub is_lecturer_credit_sum_problem: Option<bool>,
    pub is_lock: Option<bool>,
    pub encounter_category_id: Option<Uuid>,
    pub scope_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub max_member: Option<i32>,
    pub feeder_id: Option<Uuid>,
    #[sea_orm(belongs_to, from = "class_code_id", to = "id")]
    pub class_code: BelongsTo<crate::models::academic::campaign::transaction::class_codes::Entity>,
    #[sea_orm(belongs_to, from = "course_id", to = "id")]
    pub course: BelongsTo<crate::models::academic::course::master::courses::Entity>,
    #[sea_orm(belongs_to, from = "activity_id", to = "id")]
    pub activity: BelongsTo<Option<crate::models::academic::campaign::transaction::activities::Entity>>,
    #[sea_orm(belongs_to, from = "curriculum_detail_id", to = "id")]
    pub curriculum_detail: BelongsTo<Option<crate::models::academic::course::master::curriculum_details::Entity>>,
    #[sea_orm(belongs_to, from = "teach_decree_id", to = "id")]
    pub teach_decree: BelongsTo<crate::models::academic::campaign::transaction::teach_decrees::Entity>,
    #[sea_orm(belongs_to, from = "encounter_category_id", to = "id")]
    pub encounter_category: BelongsTo<Option<crate::models::academic::campaign::reference::encounter_categories::Entity>>,
    #[sea_orm(belongs_to, from = "scope_id", to = "id")]
    pub scope: BelongsTo<Option<crate::models::academic::campaign::reference::scopes::Entity>>,
    #[sea_orm(has_many)]
    pub schedules: HasMany<crate::models::academic::campaign::transaction::schedules::Entity>,
    #[sea_orm(has_many)]
    pub teach_evaluations: HasMany<crate::models::academic::campaign::transaction::teach_evaluations::Entity>,
    #[sea_orm(has_many)]
    pub teach_lecturers: HasMany<crate::models::academic::campaign::transaction::teach_lecturers::Entity>,
    #[sea_orm(has_many)]
    pub detail_activities: HasMany<crate::models::academic::student::campaign::detail_activities::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
