//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_campaign_transaction",
    table_name = "teach_decrees"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub decree_number: String,
    pub decree_date: Date,
    pub activity_id: Uuid,
    pub staff_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub feeder_id: Option<Uuid>,
    #[sea_orm(belongs_to, from = "activity_id", to = "id")]
    pub activity: BelongsTo<crate::models::academic::campaign::transaction::activities::Entity>,
    #[sea_orm(belongs_to, from = "staff_id", to = "id")]
    pub staff: BelongsTo<Option<crate::models::institution::master::staffes::Entity>>,
    #[sea_orm(has_many)]
    pub teaches: HasMany<crate::models::academic::campaign::transaction::teaches::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
