//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::finances::Entity as Finances;
pub use super::registrations::Entity as Registrations;
pub use super::resign_statuses::Entity as ResignStatuses;
pub use super::selection_types::Entity as SelectionTypes;
pub use super::statuses::Entity as Statuses;
