//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::finances::Entity as AcademicStudentReferenceFinances;
pub use super::registrations::Entity as AcademicStudentReferenceRegistrations;
pub use super::resign_statuses::Entity as AcademicStudentReferenceResignStatuses;
pub use super::selection_types::Entity as AcademicStudentReferenceSelectionTypes;
pub use super::statuses::Entity as AcademicStudentReferenceStatuses;
