//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_student_final_assignment_transaction",
    table_name = "advisers"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub thread: i32,
    pub lecturer_id: Uuid,
    pub detail_activity_id: Uuid,
    pub submission_id: Option<Uuid>,
    pub adviser_category_id: Uuid,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "lecturer_id", to = "id")]
    pub lecturer: BelongsTo<crate::models::academic::lecturer::master::lecturers::Entity>,
    #[sea_orm(belongs_to, from = "detail_activity_id", to = "id")]
    pub detail_activity: BelongsTo<crate::models::academic::student::campaign::detail_activities::Entity>,
    #[sea_orm(belongs_to, from = "submission_id", to = "id")]
    pub submission: BelongsTo<Option<crate::models::academic::student::final_assignment::transaction::submissions::Entity>>,
    #[sea_orm(belongs_to, from = "adviser_category_id", to = "id")]
    pub adviser_category: BelongsTo<crate::models::academic::student::final_assignment::reference::adviser_categories::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
