//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_student_final_assignment_transaction",
    table_name = "final_assignment_decrees"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub decree_number: String,
    pub decree_date: Date,
    pub unit_id: Option<Uuid>,
    pub activity_id: Option<Uuid>,
    pub staff_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "unit_id", to = "id")]
    pub unit: BelongsTo<Option<crate::models::institution::master::units::Entity>>,
    #[sea_orm(belongs_to, from = "activity_id", to = "id")]
    pub activity: BelongsTo<Option<crate::models::academic::campaign::transaction::activities::Entity>>,
    #[sea_orm(belongs_to, from = "staff_id", to = "id")]
    pub staff: BelongsTo<Option<crate::models::institution::master::staffes::Entity>>,
    #[sea_orm(has_many)]
    pub submissions: HasMany<crate::models::academic::student::final_assignment::transaction::submissions::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
