//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::advisers::Entity as AcademicStudentFinalAssignmentTransactionAdvisers;
pub use super::evaluation_details::Entity as AcademicStudentFinalAssignmentTransactionEvaluationDetails;
pub use super::evaluation_summaries::Entity as AcademicStudentFinalAssignmentTransactionEvaluationSummaries;
pub use super::final_assignment_decrees::Entity as AcademicStudentFinalAssignmentTransactionFinalAssignmentDecrees;
pub use super::prerequisites::Entity as AcademicStudentFinalAssignmentTransactionPrerequisites;
pub use super::schedules::Entity as AcademicStudentFinalAssignmentTransactionSchedules;
pub use super::submissions::Entity as AcademicStudentFinalAssignmentTransactionSubmissions;
