//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::advisers::Entity as Advisers;
pub use super::evaluation_details::Entity as EvaluationDetails;
pub use super::evaluation_summaries::Entity as EvaluationSummaries;
pub use super::final_assignment_decrees::Entity as FinalAssignmentDecrees;
pub use super::prerequisites::Entity as Prerequisites;
pub use super::schedules::Entity as Schedules;
pub use super::submissions::Entity as Submissions;
