//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_student_final_assignment_transaction",
    table_name = "prerequisites"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub thread: i32,
    pub requirement_id: Uuid,
    pub submission_id: Uuid,
    pub approval_type_id: Uuid,
    pub stage_id: Uuid,
    pub filename: Option<String>,
    pub dir: Option<String>,
    pub r#type: Option<String>,
    pub filesize: Option<i32>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "requirement_id", to = "id")]
    pub requirement: BelongsTo<crate::models::academic::student::final_assignment::reference::requirements::Entity>,
    #[sea_orm(belongs_to, from = "submission_id", to = "id")]
    pub submission: BelongsTo<crate::models::academic::student::final_assignment::transaction::submissions::Entity>,
    #[sea_orm(belongs_to, from = "approval_type_id", to = "id")]
    pub approval_type: BelongsTo<crate::models::academic::student::final_assignment::reference::approval_types::Entity>,
    #[sea_orm(belongs_to, from = "stage_id", to = "id")]
    pub stage: BelongsTo<crate::models::academic::student::final_assignment::reference::stages::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
