//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_student_final_assignment_transaction",
    table_name = "schedules"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub ecree_number: Option<String>,
    pub schedule_date: Option<Date>,
    pub schedule_time: Option<Time>,
    pub submission_id: Option<Uuid>,
    pub detail_activity_id: Uuid,
    pub stage_id: Uuid,
    pub room_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub zoom_meeting: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "submission_id", to = "id")]
    pub submission: BelongsTo<Option<crate::models::academic::student::final_assignment::transaction::submissions::Entity>>,
    #[sea_orm(belongs_to, from = "detail_activity_id", to = "id")]
    pub detail_activity: BelongsTo<crate::models::academic::student::campaign::detail_activities::Entity>,
    #[sea_orm(belongs_to, from = "stage_id", to = "id")]
    pub stage: BelongsTo<crate::models::academic::student::final_assignment::reference::stages::Entity>,
    #[sea_orm(belongs_to, from = "room_id", to = "id")]
    pub room: BelongsTo<Option<crate::models::building::master::rooms::Entity>>,
}


impl ActiveModelBehavior for ActiveModel {}
