//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "academic_student_final_assignment_transaction",
    table_name = "submissions"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    pub student_id: Uuid,
    pub approval_type_id: Option<Uuid>,
    pub category_id: Option<Uuid>,
    pub stage_id: Option<Uuid>,
    pub final_assignment_decree_id: Option<Uuid>,
    pub detail_activity_id: Uuid,
    pub is_taken: Option<DateTime>,
    pub is_lock: Option<DateTime>,
    pub filename: Option<String>,
    pub dir: Option<String>,
    pub r#type: Option<String>,
    pub filesize: Option<i32>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(belongs_to, from = "student_id", to = "id")]
    pub student: BelongsTo<crate::models::academic::student::master::students::Entity>,
    #[sea_orm(belongs_to, from = "approval_type_id", to = "id")]
    pub approval_type: BelongsTo<Option<crate::models::academic::student::final_assignment::reference::approval_types::Entity>>,
    #[sea_orm(belongs_to, from = "category_id", to = "id")]
    pub category: BelongsTo<Option<crate::models::academic::student::final_assignment::reference::categories::Entity>>,
    #[sea_orm(belongs_to, from = "stage_id", to = "id")]
    pub stage: BelongsTo<Option<crate::models::academic::student::final_assignment::reference::stages::Entity>>,
    #[sea_orm(belongs_to, from = "final_assignment_decree_id", to = "id")]
    pub final_assignment_decree: BelongsTo<Option<crate::models::academic::student::final_assignment::transaction::final_assignment_decrees::Entity>>,
    #[sea_orm(belongs_to, from = "detail_activity_id", to = "id")]
    pub detail_activity: BelongsTo<crate::models::academic::student::campaign::detail_activities::Entity>,
    #[sea_orm(has_many)]
    pub advisers: HasMany<crate::models::academic::student::final_assignment::transaction::advisers::Entity>,
    #[sea_orm(has_many)]
    pub evaluation_summaries: HasMany<crate::models::academic::student::final_assignment::transaction::evaluation_summaries::Entity>,
    #[sea_orm(has_many)]
    pub prerequisites: HasMany<crate::models::academic::student::final_assignment::transaction::prerequisites::Entity>,
    #[sea_orm(has_many)]
    pub schedules: HasMany<crate::models::academic::student::final_assignment::transaction::schedules::Entity>,
}


impl ActiveModelBehavior for ActiveModel {}
